<?php

/**
 * Implements hook_menu().
 */
function slac_newsletter_builder_menu() {
	$items['newsletter-builder'] = array(
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('newletter_builder_form'),
	  'access arguments' => array('access newsletter builder'),
	  'type' => MENU_CALLBACK,
	);
  $items['newsletter-builder/autocomplete'] = array(
    'title' => t('Newsletter autocomplete'),
    'page callback' => 'slac_newsletter_builder_select_content',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
	return $items;
}

/**
 * Implements hook_permission().
 */
function slac_newsletter_builder_permission() {
  return array(
    'access newsletter builder' => array(
      'title' => t('Access newletter builder'),
      'description' => t('Allow to use newletter builder.'),
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function slac_newsletter_builder_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['newsletter_main_article'] = array(
    'label' => t('Newsletter main article'),
    'custom settings' => TRUE,
  );
  $entity_info['node']['view modes']['newsletter_secondary_article'] = array(
    'label' => t('Newsletter secondary article'),
    'custom settings' => TRUE,
  );

  // @todo: Move in other place this code.
//  $content_types = variable_get('slac_newsletter_content_types', array());
//  foreach ($content_types as $bundle) {
//    $instance_info = field_info_instance('node', 'body', $bundle);
//    if (isset($instance_info['display']['newsletter_main_article']['type'])
//      && $instance_info['display']['newsletter_main_article']['type'] == 'hidden') {
//      $instance_info['display']['newsletter_main_article'] = array(
//        'label' => 'hidden',
//        'module' => 'text',
//        'settings' => array(
//          'trim_length' => '1000',
//        ),
//        'type' => 'text_trimmed',
//        'weight' => '2',
//      );
//      field_update_instance($instance_info);
//    } elseif (isset($instance_info['display']['newsletter_secondary_article']['type'])
//      && $instance_info['display']['newsletter_secondary_article']['type'] == 'hidden') {
//      $instance_info['display']['newsletter_secondary_article'] = array(
//        'label' => 'hidden',
//        'module' => 'text',
//        'settings' => array(
//          'trim_length' => '600',
//        ),
//        'type' => 'text_summary_or_trimmed',
//        'weight' => '2',
//      );
//      field_update_instance($instance_info);
//    }
//  }
}

/**
 * Implements hook_preprocess_node().
 *
 * Add custom templates for view modes.
 */
function slac_newsletter_builder_preprocess_node(&$variables) {
  if($variables['view_mode'] == 'newsletter_main_article' || $variables['view_mode'] == 'newsletter_secondary_article') {
    $variables['theme_hook_suggestions'][] = 'node__' . $variables['view_mode'];
    $variables['theme_hook_suggestions'][] = 'node__' . $variables['type'] . '__' . $variables['view_mode'];
  }
}

/**
 * Implements hook_admin_menu_output_alter().
 */
function slac_newsletter_builder_admin_menu_output_alter(&$content) {
  if (user_access('access newsletter builder')) {
    $content['menu']['11'] = array(
      '#title' => t('Newletter builder'),
      '#href' => 'newsletter-builder',
      '#weight' => 0,
    );
  }
}

/**
 * Main builder form.
 *
 * @param type $form
 * @param type $form_state
 */
function newletter_builder_form($form, &$form_state) {

  $form['page_title'] = array(
    '#markup' => '<h2>' . t('Newletter builder') . '</h2>',
  );

  $form['content_types_fieldset'] = array(
    '#title' => t('Content types used for newsletter'),
    '#tree' => TRUE,
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#prefix' => '<div id="edit-newsletter-content_types-wrapper">',
    '#suffix' => '</div>',
  );

  $content_types = slac_newsletter_builder_get_content_types();
  $content_types_default = variable_get('slac_newsletter_content_types', array());

  $form['content_types_fieldset']['content_types'] = array(
    '#title' => '',
    '#type' => 'checkboxes',
    '#options' => $content_types,
    '#default_value' => $content_types_default,
  );

  $form['content_types_fieldset']['save_content_types'] = array(
    '#type' => 'submit',
    '#value' => 'Save',
    '#validate' => array('slac_newletter_builder_form_validate'),
    '#submit' => array('slac_newletter_builder_form_submit'),
  );

  $form['main_article'] = array(
    '#title' => t('Main article'),
    '#type' => 'textfield',
    '#default_value' => isset($form_state['values']['main_article']) ? : '',
    '#autocomplete_path' => 'newsletter-builder/autocomplete',
    '#ajax' => array(
      'callback' => 'slac_newsletter_builder_set_nid',
    ),
  );
  $number_secondary_articles = isset($form_state['values']['number_secondary_articles']) ? $form_state['values']['number_secondary_articles'] : 2;
  $form['number_secondary_articles'] = array(
    '#title' => t('Number of secondary articles'),
    '#type' => 'select',
    '#options' => range(0, 15),
    '#default_value' => $number_secondary_articles,
    '#ajax' => array(
      'callback' => 'slac_newsletter_builder_set_number_secondary_articles',
      'method' => 'replace',
      'wrapper' => 'edit-secondary-articles-wrapper',
    ),
  );

  $form['secondary_articles'] = array(
    '#title' => t('Secondary articles'),
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => TRUE,
    '#prefix' => '<div id="edit-secondary-articles-wrapper">',
    '#suffix' => '</div>',
  );

  $form['results'] = array(
    '#title' => t('Newsletter Results'),
    '#tree' => TRUE,
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#prefix' => '<div id="edit-newsletter-results-wrapper">',
    '#suffix' => '</div>',
  );

  $form['results']['newsletter_results'] = array(
    '#title' => '',
    '#type' => 'textarea',
    '#rows' => 10,
    '#default_value' => isset($form_state['results']['newsletter_results']) ? : '',
  );

  for ($i = 0; $i < $number_secondary_articles; $i++) {
    $form['secondary_articles']['article_' . $i] = array(
      '#type' => 'textfield',
      '#default_value' => isset($form_state['values']['article_' . $i]) ? : '',
      '#autocomplete_path' => 'newsletter-builder/autocomplete',
    );
  }

  drupal_add_js(drupal_get_path('module', 'slac_newsletter_builder') . '/js/slac_newsletter_builder.js');

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
    '#ajax' => array(
      'callback' => 'slac_newletter_builder_ajax_callback',
    ),
  );

  return $form;
}

function slac_newletter_builder_form_validate($form, &$form_state) {
  $values = $form_state['values'];
  if (isset($values['content_types_fieldset']['content_types'])) {
    $options_count = 0;
    foreach($values['content_types_fieldset']['content_types'] as $key => $value) {
      if ($value != '0') {
        $options_count++;
      }
    }
    if ($options_count < 1) {
      form_set_error('content_types_fieldset', t('You must specify at least one content type.'));
    }
  }
}

function slac_newletter_builder_form_submit($form, &$form_state) {
  variable_set('slac_newsletter_content_types', $form_state['values']['content_types_fieldset']['content_types']);
}

function slac_newletter_builder_ajax_callback($form, &$form_state) {
  $nids = array();
  $main_article_title = $form_state['values']['main_article'];
  $match = preg_match('/\[nid:\s(\d+)\]/', $main_article_title, $matches);
  if (isset($matches['1']) && is_numeric($matches['1'])) {
    $nids['main_article_nid'][] = $matches['1'];
  }
  if (isset($form_state['values']['article_0'])) {
    $article_number = 0;
    foreach ($form_state['values'] as $key => $value) {
      if ($key == 'article_' . $article_number) {
        $match = preg_match('/\[nid:\s(\d+)\]/', $value, $matches);
        if (isset($matches['1']) && is_numeric($matches['1'])) {
          $nids[$key][] = $matches['1'];
        }
        $article_number++;
      }
    }
  }

  $html = slac_newsletter_builder_generate_html($nids);
  $selector = '#edit-results-newsletter-results';

  $commands = array();
  $commands[] = ajax_command_invoke(NULL, "slac_newletter_builder_forms", array($selector, $html));
  $commands[] = ajax_command_html('#ajax-forms-messages', theme('status_messages'));
  return array('#type' => 'ajax', '#commands' => $commands);
}

function slac_newsletter_builder_set_number_secondary_articles($form, $form_state) {
  return $form['secondary_articles'];
}

function slac_newsletter_builder_select_content($string = '') {
  $content_types = variable_get('slac_newsletter_content_types', array());

  $result = db_select('node')
    ->fields('node', array('nid', 'title'))
    ->condition('title', db_like($string) . '%', 'LIKE')
    ->condition('type', $content_types, 'IN')
    ->range(0, 10)
    ->execute();
  $matches = array();
  foreach($result as $item) {
    $matches[$item->title . ' [nid: ' . $item->nid . ']'] = check_plain($item->title);
  }

  drupal_json_output($matches);
  exit;
}

function slac_newsletter_builder_generate_html($nids = array()) {
  $output = '';
  foreach ($nids as $key => $nid) {
    $node = node_load($nid);
    if ($key == 'main_article_nid') {
      $view = node_view($node, 'newsletter_main_article');
    }
    else {
      $view = node_view($node, 'newsletter_secondary_article');
    }
    $rendered_node = drupal_render($view);
    $output .= $rendered_node;
  }
  return $output;
}

function slac_newsletter_builder_get_content_types() {
  $content_types = node_type_get_types();
  $content_types_list = array_keys($content_types);
  return array_combine($content_types_list, $content_types_list);
}