<?php

define('SLAC_PROFILE_BIO_TYPE', 'bio');
define('SLAC_PROFILE_CONTACT_TYPE', 'contact');
define('SLAC_PROFILE_SOCIAL_MEDIA_TYPE', 'social_media');

/**
 * Implements hook_ctools_plugin_directory().
 */
function slac_profile_complete_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_username_alter().
 */
function slac_profile_complete_username_alter(&$name, $account) {
  if (function_exists('profile2_load_by_user')) {
    $contact_profile = profile2_load_by_user($account, SLAC_PROFILE_CONTACT_TYPE);
    if (isset($contact_profile->field_prf_contact_fname[LANGUAGE_NONE][0]['value'])
      && isset($contact_profile->field_prf_contact_lname[LANGUAGE_NONE][0]['value'])) {
      $name = $contact_profile->field_prf_contact_fname[LANGUAGE_NONE][0]['value'] . ' ' . $contact_profile->field_prf_contact_lname[LANGUAGE_NONE][0]['value'];
    }
    elseif (isset($contact_profile->field_prf_contact_fname[LANGUAGE_NONE][0]['value'])) {
      $name = $contact_profile->field_prf_contact_fname[LANGUAGE_NONE][0]['value'];
    }
    elseif (isset($contact_profile->field_prf_contact_lname[LANGUAGE_NONE][0]['value'])) {
      $name = $contact_profile->field_prf_contact_lname[LANGUAGE_NONE][0]['value'];
    }
  }
}
