<?php
/**
 * @file
 * Code for the SLAC demo main menu feature.
 */

include_once 'slac_demo_main_menu.features.inc';

/**
 * Implements hook_post_features_enable_feature().
 * 
 * Create page nodes menu links.
 */
function slac_demo_main_menu_post_features_enable_feature() {
  // Make sure we create all menu items once.
  $flag = variable_get('slac_demo_main_menu_post_features_enable_feature', FALSE);
  if ($flag) {
    return;
  }
  // Collect all paths in order to regenerate url aliases.
  $paths = array();

  variable_set('slac_demo_main_menu_post_features_enable_feature', TRUE);

  module_load_include('inc', 'slac_demo_main_menu', 'slac_demo_main_menu.features.uuid_node');
  $nodes = slac_demo_main_menu_uuid_features_default_content();

  // Create top leve node
  $node_top = current($nodes);
  
  $top_link = _slac_demo_main_menu__create_link($node_top['title'], array('weight' => 3), $paths);

  // Create two second level nodes.
  $node = next($nodes);
  $second_link = _slac_demo_main_menu__create_link($node['title'], array(
    'depth' => 2,
    'plid' => $top_link['mlid'],
    'p1' => $top_link['mlid']), $paths);

  $node = next($nodes);
  $second_link = _slac_demo_main_menu__create_link($node['title'], array(
    'depth' => 2,
    'plid' => $top_link['mlid'],
    'p1' => $top_link['mlid']
  ), $paths);

  while ($node = next($nodes)) {
    $link = _slac_demo_main_menu__create_link($node['title'], array(
      'depth' => 3,
      'plid' => $second_link['mlid'],
      'p1' => $top_link['mlid'],
      'p2' => $second_link['mlid']
    ), $paths);
  }

  cache_clear_all();
  foreach ($paths as $path) {
    path_delete(array('source' => $path));
    
    $nid = substr($path, strlen('node/'));
    $node = node_load($nid);
    module_load_include('inc', 'pathauto');
    pathauto_create_alias('node', 'bulk_update', $path, array('node' => $node), 'page');
  }
  
}

function _slac_demo_main_menu__load_page_by_title($title) {
  return db_query('SELECT nid FROM {node} WHERE type = :type AND title = :title', array(':type' => 'page', ':title' => $title))->fetchField();
}

function _slac_demo_main_menu__create_link($title, $options = array(), &$paths) {
  $nid = _slac_demo_main_menu__load_page_by_title($title);

  $paths[] = 'node/' . $nid;
  $link = array(
    'menu_name' => 'main-menu',
    'link_title' => $title,
    'router_path' => 'node/%',
    'link_path' => 'node/' . $nid,
    'customized' => 1,
    'module' => 'menu',
  ) + $options;
  
  menu_link_save($link);
  return $link;
}
