<?php
/**
 * @file
 * Code for the SLAC demo main menu feature.
 */

include_once 'slac_demo_main_menu.features.inc';

/**
 * Implements hook_enable().
 * 
 * Create page nodes menu links.
 */
function slac_demo_main_menu_enable() {
  module_load_include('inc', 'slac_demo_main_menu', 'slac_demo_main_menu.features.uuid_node');
  $nodes = slac_demo_main_menu_uuid_features_default_content();

  // Create top leve node
  $node_top = current($nodes);
  
  $top_link = _slac_demo_main_menu__create_link($node_top['title'], array('weight' => 3));

  // Create two second level nodes.
  $node = next($nodes);
  $second_link = _slac_demo_main_menu__create_link($node['title'], array(
    'depth' => 2,
    'plid' => $top_link['mlid'],
    'p1' => $top_link['mlid']));

  $node = next($nodes);
  $second_link = _slac_demo_main_menu__create_link($node['title'], array(
    'depth' => 2,
    'plid' => $top_link['mlid'],
    'p1' => $top_link['mlid']
  ));

  while ($node = next($nodes)) {
    $second_link = _slac_demo_main_menu__create_link($node['title'], array(
      'depth' => 3,
      'plid' => $second_link['mlid'],
      'p1' => $top_link['mlid'],
      'p2' => $second_link['mlid']
    ));
  }
}

function _slac_demo_main_menu__load_page_by_title($title) {
  return db_query('SELECT nid FROM {node} WHERE type = :type AND title = :title', array(':type' => 'page', ':title' => $title))->fetchField();
}

function _slac_demo_main_menu__create_link($title, $options = array()) {
  $nid = _slac_demo_main_menu__load_page_by_title($title);
  $link = array(
    'menu_name' => 'main-menu',
    'link_title' => $title,
    'router_path' => 'node/%',
    'link_path' => 'node/' . $nid,
  ) + $options;
  
  menu_link_save($link);
  return $link;
}
