<?php

include_once 'slac_social_media.features.inc';

/**
 * Implements hook_entity_info_alter().
 */
function slac_social_media_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['social_media'] = array(
    'label' => t('Social Media'),
    'pane category' => t('SLAC panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/social_media',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

