<?php

/**
 * Implements hook_permission().
 */
function slac_change_site_name_permission() {
  return array(
    'administer site name' => array(
      'title' => t('Administer site name'),
      'description' => t('Change site name.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function slac_change_site_name_menu() {
	$items['change-site-name'] = array(
	  'page callback' => 'slac_change_site_name_create_form',
	  'access arguments' => array('administer site name'),
	  'type' => MENU_CALLBACK,
	);
	return $items;
}

function slac_change_site_name_create_form() {
  
  return drupal_get_form('slac_change_site_name_form');

}

function slac_change_site_name_form() {
  $form = array();

  $form['new_site_name'] = array(
  '#type' => 'textfield', 
  '#title' => t('New Site Name:'), 
  '#default_value' => variable_get('site_name'),
  '#description' => t('The current site name is "' . variable_get('site_name') . '".'),
  '#size' => 60, 
  '#maxlength' => 128, 
  '#required' => TRUE,
  );

  $form['submit'] = array(
  '#type' => 'submit',
  '#value' => t('Submit'), 

  );

  return $form;

}

function slac_change_site_name_form_submit(&$form, &$form_state) {
  variable_set('site_name', $form_state['values']['new_site_name']);
}

/**
 * Implements hook_admin_menu_output_alter().
 */
function slac_change_site_name_admin_menu_output_alter(&$content) {
  
  if (user_access('administer site name')) {
    $content["menu"]['change-site-name'] = array(
      '#title' => t('Site Name'),
      '#href' => 'change-site-name',
      '#weight' => 0,
    );
  }
}




