<?php

define('SLAC_EVENT_EVENTS_PAGE_URI', 'events');

/**
 * @file
 * Code for the Events Features feature.
 */

include_once 'slac_event.features.inc';

/**
 * Preprocess function for node template.
 */
function slac_event_preprocess_node(&$vars) {
  if ($vars['type'] != 'event' || $vars['view_mode'] != 'teaser') {
    return;
  }

  $previous_event_year_month_day = &drupal_static(__FUNCTION__ . '-previous_event_year_month_day', '');
  $row_counter = &drupal_static(__FUNCTION__ . '-row_counter', 1);
  if (isset($vars['view']->result)) {
    $total_rows = count($vars['view']->result);
  }
  else {
    $total_rows = _taxonomy_term_count_nodes($vars['field_slac_event_category']['und'][0]['tid']);
  }

  $vars += array(
    'add_date_html_prefix' => FALSE,
    'add_date_html_suffix' => FALSE,
    'add_last_date_html_suffix' => FALSE,
  );

  $event_date = $vars['field_slac_event_date'][LANGUAGE_NONE][0]['value'];
  $timezone_db = $vars['field_slac_event_date'][LANGUAGE_NONE][0]['timezone_db'];
  $timezone = $vars['field_slac_event_date'][LANGUAGE_NONE][0]['timezone'];

  // Explode date value like 2013-12-24T22:00:00
  list($year_month_day, $time) = explode('T', $event_date);

  if ($year_month_day != $previous_event_year_month_day) {
    $vars['add_date_html_prefix'] = TRUE;
    if ($row_counter != 1) {
      $vars['add_date_html_suffix'] = TRUE;
    }
  }
  if ($row_counter == $total_rows) {
    $vars['add_last_date_html_suffix'] = TRUE;
  }

  $event_date_timestamp = _get_display_date($event_date, $timezone, $timezone_db);
  $vars['month'] = format_date($event_date_timestamp, 'custom', 'F');
  $vars['day'] = format_date($event_date_timestamp, 'custom', 'j');

  $event_date_end = $vars['field_slac_event_date'][LANGUAGE_NONE][0]['value2'];
  $event_date_end_timestamp = _get_display_date($event_date_end, $timezone, $timezone_db);

  $vars['period'] = t('All Day');
  if ($event_date != $event_date_end) {
    $vars['period'] = format_date($event_date_timestamp, 'custom', 'g:ia') . ' - ' . format_date($event_date_end_timestamp, 'custom', 'g:ia');
  }

  $vars['location'] = '';
  if (isset($vars['field_location'][LANGUAGE_NONE][0]['name'])) {
    $vars['location'] = ', ' . check_plain($vars['field_location'][LANGUAGE_NONE][0]['name']);
  }

  $previous_event_year_month_day = $year_month_day;
  $row_counter++;
}

/**
 * Returns the date timestamp taking into consideration the timezone.
 */
function _get_display_date($date, $timezone, $timezone_db) {
  $date_convert = new DateTime($date, new DateTimeZone($timezone_db));
  $date_convert->setTimezone(new DateTimeZone($timezone));
  return $date_convert->getTimestamp();
}

/**
 * Count the number of nodes tagged with a term.
 */
function _taxonomy_term_count_nodes($tid, $type = 0) {
  static $count;

  if (isset($count[$type][$tid])) {
    return $count[$type][$tid];
  }

  $query = db_select('taxonomy_index', 't');
  $query->condition('tid', $tid, '=');
  $query->addExpression('COUNT(*)', 'count_nodes');


  // Restrict query by Content Type.
  if (!empty($type)) {
    $query->join('node', 'n', 't.nid = n.nid');
    $query->condition('type', $type, '=');
  }

  $count[$type][$tid] = $query->execute()->fetchField();

  return $count[$type][$tid];
}

/**
 * Preprocess for calendar datebox.
 */
function slac_event_process_calendar_datebox(&$vars) {
  $view = $vars['view'];
  if ($view->name != 'events' || $view->current_display != 'panel_pane_2') {
    return;
  }
  $link = $vars['link'];
  $vars['link'] = l($vars['link'], SLAC_EVENT_EVENTS_PAGE_URI . '/' . $vars['date']);
  $vars['day'] = l($vars['day'], SLAC_EVENT_EVENTS_PAGE_URI . '/' . $vars['date']);
}

/**
 * Implements hook_views_data_alter().
 */
function slac_event_views_data_alter(&$data) {
  $data['views']['calendar_month_pager'] = array(
    'title' => t('Calendar months pager'),
    'help' => t('Allows to scroll back and forward for months.'),
    'area' => array(
      'handler' => 'views_handler_slac_events_calendar_months_pager',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function slac_event_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['calendar_teaser'] = array(
    'label' => 'Calendar teaser',
    'custom settings' => TRUE,
  );
}

function _slac_event_get_current_date() {
  $arg = arg(1);
  if (empty($arg)) {
    return REQUEST_TIME;
  }
  return strtotime($arg);
}

/**
 * Prepare argument for Event view of main content area (list of events).
 *
 * Should either pass url argument or current date in format 2014-01.
 */
function _slac_event_get_date_argument_events_main_content() {
  $arg = arg(1);
  if (!empty($arg) && (preg_match('/(\d){4}-(\d){2}$/', $arg) || preg_match('/(\d){4}-(\d){2}-(\d){2}$/', $arg))) {
    return $arg;
  }
  return format_date(REQUEST_TIME, 'custom', 'Y-m');
}

/**
 * Prepare argument for Event view of mini calendar.
 *
 * Should either pass url argument or current date in format 2014-01.
 */
function _slac_event_get_date_argument_events_calendar() {
  $arg = arg(1);
  if (!empty($arg) && preg_match('/(\d){4}-(\d){2}$/', $arg)) {
    return $arg;
  }
  return format_date(REQUEST_TIME, 'custom', 'Y-m');
}


