<?php

define('SLAC_EVENT_EVENTS_PAGE_URI', 'events');

/**
 * @file
 * Code for the Events Features feature.
 */

include_once 'slac_event.features.inc';
include_once 'slac_event.formatter.inc';

/**
 * Implements hook_menu().
 */
function slac_event_menu() {
  return array(
    'node/add/event-import' => array(
      'title' => 'Event import (single)',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'drupal_get_form',
      'page arguments' => array('slac_event_import_single'),
      'access callback' => 'node_access',
      'access arguments' => array('create', 'event'),
    ),
  );
}

/**
 * Form callback for our new single event import form.
 */
function slac_event_import_single($form, $form_state) {
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('Event page URL'),
    '#description' => t('Paste in the URL of an event on a SLAC site.'),
    '#required' => TRUE,
    '#weight' => 0,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Import'),
  );
  return $form;
}

/**
 * Form validator for our single event import form.
 *
 * @see slac_event_import_single()
 */
function slac_event_import_single_validate($form, &$form_state) {
  // Load the page.
  $page = drupal_http_request($form_state['values']['url']);
  if ($page->code <= 0) {
    form_set_error('url', t('This does not appear to be a valid URL.'));
    return;
  }
  elseif ($page->code != 200) {
    form_set_error('url', t('Loading the page at this URL failed. Error code @code (@error).', array('@code' => $page->code, '@error' => empty($page->error) ? '?' : $page->error)));
    return;
  }
  // XML parsing is easy to fail. I know it's "wrong," but use regex to find
  // our calendar link.
  if (!preg_match('/\<link rel="icalendar" href="([^"]+)"/', $page->data, $matches)) {
    form_set_error('url', t('Event information could not be found on the page.'));
    return;
  }
  $ical = drupal_http_request($matches[1]);
  if ($ical->code != 200) {
    form_set_error('url', t('Loading the event information for this event failed. Error code @code (@error).', array('@code' => $page->code, '@error' => empty($page->error) ? '?' : $page->error)));
    return;
  }
  libraries_load('iCalcreator');
  $calendar = new vcalendar();
  if (!$calendar->parse($ical->data)) {
    form_set_error('url', t('Parsing the event information for this event failed.'));
    return;
  }
  $form_state['ical'] = $calendar->components[1];
}

/**
 * Form submission function for our single event import form.
 *
 * @see slac_event_import_single()
 */
function slac_event_import_single_submit($form, &$form_state) {
  // Ideally, we could leverage already-configured stuff (mappings, etc) for
  // this, but I can't find a way to do so - it doesn't seem very modular.
  $node = new stdClass();
  $node->type = 'event';
  node_object_prepare($node);
  $node->title = empty($form_state['ical']->summary) ? '' : $form_state['ical']->summary['value'];
  $node->field_slac_event_date[LANGUAGE_NONE][] = array(
    'value' => $form_state['ical']->dtstart['value']['year'] . '-'
      . $form_state['ical']->dtstart['value']['month'] . '-'
      . $form_state['ical']->dtstart['value']['day'] . 'T'
      . $form_state['ical']->dtstart['value']['hour'] . ':'
      . $form_state['ical']->dtstart['value']['min'] . ':'
      . $form_state['ical']->dtstart['value']['sec'],
    'value2' => $form_state['ical']->dtend['value']['year'] . '-'
      . $form_state['ical']->dtend['value']['month'] . '-'
      . $form_state['ical']->dtend['value']['day'] . 'T'
      . $form_state['ical']->dtend['value']['hour'] . ':'
      . $form_state['ical']->dtend['value']['min'] . ':'
      . $form_state['ical']->dtend['value']['sec'],
    'timezone' => $form_state['ical']->dtstart['params']['TZID'],
    'timezone_db' => $form_state['ical']->dtstart['params']['TZID'],
    'date_type' => 'date',
  );
  if (!empty($form_state['ical']->description)) {
    // Why is this one a numeric array?
    $node->body[LANGUAGE_NONE][] = array('value' => $form_state['ical']->description[0]['value']);
  }
  if (!empty($form_state['ical']->location)) {
    $node->field_slac_event_scientific_area[LANGUAGE_NONE][] = array('value' => $form_state['ical']->location['value']);
  }
  node_save($node);
  // Let's redirect the user to the node edit form for the node we just created.
  $form_state['redirect'] = "node/{$node->nid}/edit";
  drupal_set_message(t('Event imported. Edit it below if necessary.'));
}

/**
 * Preprocess function for node template.
 */
function slac_event_preprocess_node(&$vars) {
  if ($vars['type'] != 'event' || $vars['view_mode'] != 'teaser') {
    return;
  }

  $vars['event_link'] = '';
  if (isset($vars['field_slac_event_link']['und'][0]['url'])) {
    $vars['event_link'] = $vars['field_slac_event_link']['und'][0]['url'];
  }

  $previous_event_year_month_day = &drupal_static(__FUNCTION__ . '-previous_event_year_month_day', '');
  $row_counter = &drupal_static(__FUNCTION__ . '-row_counter', 1);
  if (isset($vars['view']->result)) {
    $total_rows = count($vars['view']->result);
  }
  else {
    $total_rows = _taxonomy_term_count_nodes($vars['field_slac_event_category']['und'][0]['tid']);
  }

  $vars += array(
    'add_date_html_prefix' => FALSE,
    'add_date_html_suffix' => FALSE,
    'add_last_date_html_suffix' => FALSE,
  );

  $event_date = $vars['field_slac_event_date'][LANGUAGE_NONE][0]['value'];

  // Explode date value like 2013-12-24T22:00:00
  list($year_month_day, $time) = explode('T', $event_date);

  if ($year_month_day != $previous_event_year_month_day) {
    $vars['add_date_html_prefix'] = TRUE;
    if ($row_counter != 1) {
      $vars['add_date_html_suffix'] = TRUE;
    }
  }
  if ($row_counter == $total_rows) {
    $vars['add_last_date_html_suffix'] = TRUE;
  }

  $event_date_timestamp = strtotime($event_date);
  $vars['month'] = format_date($event_date_timestamp, 'custom', 'M');
  $vars['day'] = format_date($event_date_timestamp, 'custom', 'j');

  $event_date_end = $vars['field_slac_event_date'][LANGUAGE_NONE][0]['value2'];
  $event_date_end_timestamp = strtotime($event_date_end);

  $vars['period'] = t('All Day');
  if ($event_date != $event_date_end) {
    $vars['period'] = format_date($event_date_timestamp, 'custom', 'g:ia') . ' - ' . format_date($event_date_end_timestamp, 'custom', 'g:ia');
  }

  $vars['location'] = '';
  if (isset($vars['field_location'][LANGUAGE_NONE][0]['name'])) {
    $vars['location'] = ', ' . check_plain($vars['field_location'][LANGUAGE_NONE][0]['name']);
  }

  $previous_event_year_month_day = $year_month_day;
  $row_counter++;
}

/**
 * Preprocess function for event date and time field.
 */
function slac_preprocess_field (&$variables) {

  if (isset($variables['element']['#field_name']) && $variables['element']['#field_name'] == 'field_slac_event_date') {

    $variables['items'][0]['#markup'] .= ' PST';
  }
}

/**
 * Count the number of nodes tagged with a term.
 */
function _taxonomy_term_count_nodes($tid, $type = 0) {
  static $count;

  if (isset($count[$type][$tid])) {
    return $count[$type][$tid];
  }

  $query = db_select('taxonomy_index', 't');
  $query->condition('tid', $tid, '=');
  $query->addExpression('COUNT(*)', 'count_nodes');


  // Restrict query by Content Type.
  if (!empty($type)) {
    $query->join('node', 'n', 't.nid = n.nid');
    $query->condition('type', $type, '=');
  }

  $count[$type][$tid] = $query->execute()->fetchField();

  return $count[$type][$tid];
}

/**
 * Preprocess for calendar datebox.
 */
function slac_event_process_calendar_datebox(&$vars) {
  $view = $vars['view'];
  if ($view->name != 'events' || $view->current_display != 'panel_pane_2') {
    return;
  }
  $link_class = '';
  if ($vars['date'] == _slac_event_get_date_from_event_node_with_day()) {
    $link_class = 'active';
  }
  $link = $vars['link'];
  $vars['link'] = l($vars['link'], SLAC_EVENT_EVENTS_PAGE_URI . '/' . $vars['date'], array('attributes' => array('class' => $link_class)));
  $vars['day'] = l($vars['day'], SLAC_EVENT_EVENTS_PAGE_URI . '/' . $vars['date'], array('attributes' => array('class' => $link_class)));
}

/**
 * Implements hook_views_data_alter().
 */
function slac_event_views_data_alter(&$data) {
  $data['views']['calendar_month_pager'] = array(
    'title' => t('Calendar months pager'),
    'help' => t('Allows to scroll back and forward for months.'),
    'area' => array(
      'handler' => 'views_handler_slac_events_calendar_months_pager',
    ),
  );
  $data['views']['calendar_footer'] = array(
    'title' => t('Calendar footer'),
    'help' => t('Display Month / Day view links.'),
    'area' => array(
      'handler' => 'views_handler_slac_events_calendar_footer',
    ),
  );
  $data['views']['calendar_main_area_title'] = array(
    'title' => t('Calendar main area title'),
    'help' => t('Display title for a calendar main area.'),
    'area' => array(
      'handler' => 'views_handler_slac_events_calendar_main_area_title',
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function slac_event_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['calendar_teaser'] = array(
    'label' => 'Calendar teaser',
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_views_pre_view().
 */
function slac_event_views_pre_view(&$view) {
  $arg0 = arg(0);
  $arg1 = arg(1);
  if ($view->name == 'events' && $view->current_display == 'panel_pane_1') {
    if ($arg0 == SLAC_EVENT_EVENTS_PAGE_URI && !empty($arg1)
      && isset($view->display['panel_pane_1']->handler->options['filters']['field_slac_event_date_value'])) {
      $view_filters = $view->display['panel_pane_1']->handler->options['filters'];
      if (isset($view_filters['field_slac_event_date_value'])) {
        unset($view_filters['field_slac_event_date_value']);
      }
      $view->display_handler->override_option('filters', $view_filters);
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function slac_event_views_pre_render(&$view) {
  $arg0 = arg(0);
  $arg1 = arg(1);
  $url_date_with_day = _slac_event_get_date_from_url_with_day();
  if ($view->name == 'events' && $view->current_display == 'panel_pane_1' && !$url_date_with_day) {
    $view->empty['area']->options['content'] = t('No events planned for this month.');
    if ($arg0 == SLAC_EVENT_EVENTS_PAGE_URI && empty($arg1)) {
      $view->empty['area']->options['content'] = t('No events planned for next months.');
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function slac_event_views_query_alter(&$view) {
  $arg0 = arg(0);
  $arg1 = arg(1);
  if ($view->name == 'events' && $view->current_display == 'panel_pane_1') {
    if ($arg0 == SLAC_EVENT_EVENTS_PAGE_URI && empty($arg1)) {
      unset($view->query->where['date']);
      $pager = array(
        'type' => 'full',
        'options' => array(
          'items_per_page' => 10,
          'total_pages' => 1,
        ),
      );
      $handler = &$view->display['panel_pane_1']->handler;
      $handler->set_option('pager', $pager);
      $view->display_handler->handlers['header'] = array();
    }
  }
}

/**
 * Prepare argument for Event view of main content area (list of events).
 *
 * Should either pass url argument or current date in format 2014-01.
 */
function _slac_event_get_date_argument_events_main_content() {
  $url_date_with_day = _slac_event_get_date_from_url_with_day();
  if (!empty($url_date_with_day)) {
    return $url_date_with_day;
  }

  return _slac_event_get_date_from_url_month_only();
}

/**
 * Prepare argument for Event view of mini calendar.
 *
 * Should either pass url argument or current date in format 2014-01.
 */
function _slac_event_get_date_argument_events_calendar() {
  if ($date = _slac_event_get_current_date()) {
    return date('Y-m', $date);
  }
  elseif (arg(0) == SLAC_EVENT_EVENTS_PAGE_URI) {
    $url_date = _slac_event_get_date_argument_events_main_content();
    return _slac_event_convert_date_with_day_to_date_without_day($url_date);
  }
}

/**
 * Return date for Calendar's pager. It can be either arg(1) in case we are on events
 * page, or date of the event if we are on full node view page.
 */
function _slac_event_get_current_date() {
  if ($date = _slac_event_get_date_from_event_node_with_day()) {
    return $date;
  }
  elseif ($date = _slac_event_get_date_from_url_month_only()) {
    return strtotime($date);
  }
}

function _slac_event_get_date_from_event_node_with_day() {
  if ($node = menu_get_object()) {
    if ($node->type === 'event') {
      if ($dates = field_get_items('node', $node, 'field_slac_event_date')) {
        return strtotime($dates[0]['value']);
      }
    }
  }
}

function _slac_event_get_date_from_url_month_only() {
  $arg0 = arg(0);
  $arg1 = arg(1);
  if ($arg0 == SLAC_EVENT_EVENTS_PAGE_URI) {
    if (!empty($arg1) && preg_match('/^(\d+)-(\d+)/', $arg1)) {
      return $arg1;
    }
  }
  return format_date(REQUEST_TIME, 'custom', 'Y-m');
}

function _slac_event_get_date_from_url_with_day() {
  $arg0 = arg(0);
  $arg1 = arg(1);
  if ($arg0 == SLAC_EVENT_EVENTS_PAGE_URI) {
    if (!empty($arg1) && preg_match('/^(\d+)-(\d+)-(\d+)$/', $arg1)) {
      return $arg1;
    }
  }
}

function _slac_event_convert_date_with_day_to_date_without_day($date_string) {
  return date('Y-m', strtotime($date_string));
}

/**
 * Implements hook_panels_post_render().
 */
function slac_event_panels_post_render($display, $renderer) {
  // If an event node is being viewed, add a link to its iCalendar display. Now
  // normally, we'd do this in hook_node_view, easy peasy. But no, because this
  // site uses Panels, and Panels doesn't have much respect for standard core
  // hooks. So instead, I use this undocumented Panels hook. Is this the right
  // way to do this? Asciishrug. Panels is *never* the right way to do
  // *anything,* but here we are, so here we go.
  if (isset($display->context['argument_entity_id:node_1'])
    && $display->context['argument_entity_id:node_1']->data->type === 'event'
  ) {
    $event_ics = url("event/{$display->context['argument_entity_id:node_1']->data->nid}/calendar.ics",
      array('absolute' => TRUE)
    );
    drupal_add_html_head_link(array(
      'rel' => 'icalendar',
      'href' => $event_ics,
      'type' => 'text/icalendar',
    ));

    // Hmm, the iCalendar approach isn't giving us enough info. Let's try this
    // silly trick.
    $fields = array('title', 'body', 'field_slac_event_date', 'field_location', 'field_slac_event_link');
    $blob = array();
    foreach ($fields as $field) {
      if (isset($display->context['argument_entity_id:node_1']->data->{$field})) {
        $blob[$field] = $display->context['argument_entity_id:node_1']->data->{$field};
      }
    }
    $tag = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'name' => 'slac-event-data',
        'content' => drupal_json_encode($blob),
      ),
    );
    drupal_add_html_head($tag, 'slac-event-data');
    
  }
}
