<?php

/**
 * Implemanted hook_form_alter()
 * 
 * @param type $form
 * @param type $form_state
 * @param type $form_id 
 */
function slac_site_variables_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $form['site_information']['site_name_abbreviation'] = array(
      '#type' => 'textfield',
      '#title' => t('Site name abbreviation'),
      '#description' => t('The site name abbreviation will be appear in header.'),
      '#default_value' => (variable_get('site_name_abbreviation')) ? variable_get('site_name_abbreviation') : '',
    );
    $form['site_information']['site_url_address'] = array(
      '#type' => 'textfield',
      '#title' => t('Site address'),
      '#description' => t('This address is used by link from footer.'),
      '#default_value' => (variable_get('site_url_address')) ? variable_get('site_url_address') : '',
    );
    $form['#submit'][] = 'slac_site_variables_form_submit';
  }
}
/**
 *
 * @param type $form
 * @param type $form_state 
 */
function slac_site_variables_form_submit(&$form, &$form_state){
  variable_set('site_name_abbreviation', $form_state['values']['site_name_abbreviation']);
  variable_set('site_url_address', $form_state['values']['site_url_address']);
}

/**
 * Implemented hook_form_system_theme_settings_alter()
 * 
 * @param type $form
 * @param type $form_state 
 */
function slac_site_variables_form_system_theme_settings_alter(&$form, &$form_state) {
  $form['theme_settings']['site_name_abbreviation'] = array(
    '#type' => 'checkbox',
    '#title' => t('Site name abbreviation'),
    '#default_value' => theme_get_setting('site_name_abbreviation'),
  );
  $form['theme_settings']['site_url_address'] = array(
    '#type' => 'checkbox',
    '#title' => t('Site address'),
    '#default_value' => theme_get_setting('site_url_address'),
  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function slac_site_variables_ctools_plugin_directory($module, $plugin) {
//  if ($module === 'panels') {
    return 'plugins/' . $plugin;
  //}
}

/**
 * Implements hook_ctools_plugin_api().
 */
function slac_site_variables_ctools_plugin_api($module, $api) {
//  if ($module == 'slac_site_variables') {
    return array('version' => 1);
//  }
}
