<?php

/**
 * Implemanted hook_form_alter()
 *
 * @param type $form
 * @param type $form_state
 * @param type $form_id
 */
function slac_site_variables_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $form['site_information']['site_url_address'] = array(
      '#type' => 'textarea',
      '#title' => t('Site address'),
      '#description' => t('This address is used by link from footer.'),
      '#default_value' => (variable_get('site_url_address')) ? variable_get('site_url_address') : '',
    );
    $form['site_information']['site_footer_address'] = array(
      '#type' => 'textarea',
      '#title' => t('Footer Address'),
      '#description' => t('This address is used by link from Secondary footer.'),
      '#default_value' => (variable_get('site_footer_address')) ? variable_get('site_footer_address') : '',
    );
    $form['#submit'][] = 'slac_site_variables_form_submit';
  }
}

/**
 *
 * @param type $form
 * @param type $form_state
 */
function slac_site_variables_form_submit(&$form, &$form_state) {
  variable_set('site_url_address', $form_state['values']['site_url_address']);
  variable_set('site_footer_address', $form_state['values']['site_footer_address']);
}

/**
 * Implemented hook_form_system_theme_settings_alter()
 *
 * @param type $form
 * @param type $form_state
 */
function slac_site_variables_form_system_theme_settings_alter(&$form, &$form_state) {
  $form['theme_settings']['site_url_address'] = array(
      '#type' => 'checkbox',
      '#title' => t('Site address'),
      '#default_value' => theme_get_setting('site_url_address'),

  );
  $form['theme_settings']['site_footer_address'] = array(
    '#type' => 'checkbox',
    '#title' => t('Site Footer address'),
    '#default_value' => theme_get_setting('site_footer_address'),

  );
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function slac_site_variables_ctools_plugin_directory($owner, $plugin) {
  if ($owner === 'ctools') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function slac_site_variables_ctools_plugin_api($module, $api) {
  if ($module == 'slac_site_variables') {
    return array('version' => 1);
  }
}
