<?php

/**
 * Implementation of hook_install.
 */
function slac_site_variables_install() {
  variable_set('site_url_address', '');
  variable_set('site_footer_address','');
}

/**
 * Implementation of hook_uninstall.
 */
function slac_site_variables_uninstall() {
  variable_del('site_url_address');
  variable_del('site_footer_address');
}

/**
 * Remove site_name_abbreviation.
 */
function slac_site_variables_update_7001() {
  variable_del('site_name_abbreviation');
}
