<?php
/**
 * @file
 * Code for the SLAC FAQ feature.
 */

include_once 'slac_faq.features.inc';


/**
 * Preprocess function.
 */
function slac_faq_preprocess_views_view(&$vars) {
  if ($vars['view']->name == 'slac_faq') {
    drupal_add_js(drupal_get_path('module', 'slac_faq') . '/slac_faq.js');
  } 
  
}

/**
 * Preprocess function.
 */
function slac_faq_preprocess_views_view_fields(&$vars) {

  if (isset($vars['fields']['title']->content)) {
    $vars['faq_title'] = $vars['fields']['title']->content;
  }

  if (isset($vars['fields']['body']->content)) {
    $vars['faq_answer'] = $vars['fields']['body']->content;
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function slac_faq_form_faq_node_form_alter(&$form, &$form_state) {
  if(isset($form['detailed_question'])) {
    unset($form['detailed_question']);
  }
}
