<?php
/**
 * @file
 * Code for the SLAC News feature.
 */

include_once 'slac_news.features.inc';

//Add more view modes for Media formatting.
function slac_news_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['crop_crop_news_landscape'] = array(
    'label' => t('Crop News Landscape'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_node_view().
 */
function slac_news_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'slac_news' && $view_mode == 'full') {
    menu_set_active_item(drupal_get_normal_path('news'));
  }
}

/**
 * Implements hook_ctools_block_content_type_pre_render().
 *
 * Set different current path.
 */
function slac_news_ctools_block_content_type_pre_render($subtype, $conf) {
  $arg0 = arg(0);
  $alias = drupal_get_path_alias(current_path());
  $alias_array = explode('/', $alias);
  if ($arg0 != 'news' && $alias_array['0'] != 'news') {
    return;
  }
  $current_path = &drupal_static(__FUNCTION__);
  $current_path = current_path();

  $nid = _slac_news_get_news_node_nid();
  menu_set_active_item('node/' . $nid);
}

/**
 * Implements hook_ctools_block_content_type_post_render().
 *
 * Restore previous path.
 */
function slac_news_ctools_block_content_type_post_render($subtype, $conf) {
  $current_path = &drupal_static('slac_news_ctools_block_content_type_pre_render');
  if (empty($current_path)) {
    return;
  }

  menu_set_active_item($current_path);
  $current_path = '';
}

/**
 * Get nid of the News node.
 */
function _slac_news_get_news_node_nid() {
  $query = new EntityFieldQuery();
  $news_node = $query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'landing_page')
    ->propertyCondition('title', 'News and Press Releases')
    ->range(0, 1)
    ->execute();

  $news_node = reset($news_node['node']);

  return $news_node->nid;
}