<?php
/**
 * @file
 * Code for the SLAC News feature.
 */

include_once 'slac_news.features.inc';

//Add more view modes for Media formatting.
function slac_news_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['crop_crop_news_landscape'] = array(
    'label' => t('Crop News Landscape'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_node_view().
 */
function slac_news_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'slac_news' && $view_mode == 'full') {
    menu_set_active_item(drupal_get_normal_path("news"));
  }
}