<?php

/**
 * @file
 * Tweaks public facing file URLs to fit the SLAC AFS file storage scheme.
 */

/**
 * Implements hook_stream_wrappers_alter().
 */
function slac_files_rewrite_stream_wrappers_alter(&$wrappers) {
  if ($wrappers['public']['class'] = 'DrupalPublicStreamWrapper') {
    $wrappers['public']['class'] = 'SlacPublicStreamWrapper';
  }
}

class SlacPublicStreamWrapper extends DrupalPublicStreamWrapper {
  /**
   * Return the HTML URI of a public file.
   */
  function getExternalUrl() {
    $path = str_replace('\\', '/', $this->getTarget());
    return $GLOBALS['base_url'] . '/files/' . drupal_encode_path($path);
  }
}
