<?php
/**
 * @file
 * Code for the SLAC Wiki feature.
 */

include_once 'slac_wiki.features.inc';

/**
 * Implements hook_form_FORM_ID_alter
 */
function slac_wiki_form_slac_wiki_page_node_form_alter(&$form, &$form_state, $form_id) {
  $form['body'][LANGUAGE_NONE][0]['#format'] = 'markdown';
  $form['#attached']['js'] = array(
  drupal_get_path('module', 'slac_wiki') . '/slac_wiki.js',
  );
}

function slac_wiki_entry_validate($form, &$form_state) {
  dpm($form_state['values']);
  form_set_error('aaa', 'bbb');
}