<?php

function slac_panelizer_roles_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'panels_common_settings') {
    $form['content_types']['roles'] =
        array(
          '#type' => 'fieldset',
          '#group' => 'additional_settings',
          '#title' => t('Roles'),
          'options' => array(
            '#prefix' => '<div class="panels-page-type-container">',
            '#suffix' => '</div>',
            '#type' => 'checkboxes',
            '#options' => user_roles(),
          )
    );
  }
}