<?php

/**
* Implementation of hook_ctools_plugin_directory().
*/
function slac_block_style_ctools_plugin_directory($module, $plugin) {
  if ($module === 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_form_alter
 * @param type $form
 * @param type $form_state
 * @param type $form_id 
 */
function slac_block_style_form_alter(&$form, &$form_state, $form_id) {
  // Unset default style from panels.
  if($form_id == 'panels_edit_style_type_form') {
    unset($form['style']['#options']['block']);
    unset($form['style']['#options']['naked']);
    unset($form['style']['#options']['rounded_corners']);
  }
}