<?php
/**
 * @file
 * slac_service_catalog_demo.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function slac_service_catalog_demo_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Enterprise application group',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'f823d367-8481-4c52-b3d7-51cefc6baa15',
  'type' => 'slac_sc_catalog_item',
  'language' => 'und',
  'created' => 1377535764,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0809a5ec-f056-410f-ab72-bda63b0bed4c',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<div class="field field-name-field-service-overview field-type-text-long field-label-hidden" style="margin-bottom: 20px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">
	<div class="field-items">
		<div class="field-item even">
			<p style="margin-top: 0px;">Our goal is to provide superior client support while helping our partners maximize their IT investment. We work closely with Computer Resource Consulting (CRC) Desktop Support to provide comprehensive, responsive technology assistance for your entire organization.</p>
		</div>
	</div>
</div>
<div class="field field-name-body field-type-text-with-summary field-label-hidden" style="margin-bottom: 20px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">
	<div class="field-items">
		<div class="field-item even">
			<h2 style="margin-top: 0px; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Features and benefits</h2>
			<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px;">
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Campus infrastructure integration</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Regular and scheduled maintenance</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Prioritized HelpSU problem resolution</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Security auditing and system hardening</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">User and workgroup management</li>
			</ul>
			<h2 style="margin-top: 1.4em; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Getting started</h2>
			<p style="margin-top: 0px;">To learn more about contract server support, please contact&nbsp;<a href="https://stanfordwho.stanford.edu/SWApp/auth/lookup?search=Noah%20Abrahamson" style="color: rgb(130, 114, 82); border-bottom-style: dotted; border-bottom-width: 1px; border-bottom-color: rgb(130, 114, 82);">Noah Abrahamson</a>&nbsp;or&nbsp;<a href="http://helpsu.stanford.edu/" style="color: rgb(130, 114, 82); border-bottom-style: dotted; border-bottom-width: 1px; border-bottom-color: rgb(130, 114, 82);">submit a HelpSU request</a>.</p>
			<h2 style="margin-top: 1.4em; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Learn more</h2>
			<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px;">
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;"><a href="https://itservices.stanford.edu/service/contract-support/server" style="color: rgb(130, 114, 82); border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: rgb(130, 114, 82);">Server Group (CRC)</a></li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;"><a href="https://itservices.stanford.edu/service/server-support/businessdocuments" style="color: rgb(130, 114, 82); border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: rgb(130, 114, 82);">Business Documents for Contract Support &mdash; Server Support</a></li>
			</ul>
		</div>
	</div>
</div>
<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<div class="field field-name-field-service-overview field-type-text-long field-label-hidden" style="margin-bottom: 20px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">
<div class="field-items">
<div class="field-item even">
<p style="margin-top: 0px;">Our goal is to provide superior client support while helping our partners maximize their IT investment. We work closely with Computer Resource Consulting (CRC) Desktop Support to provide comprehensive, responsive technology assistance for your entire organization.</p>
</div>
</div>
</div>
<div class="field field-name-body field-type-text-with-summary field-label-hidden" style="margin-bottom: 20px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">
<div class="field-items">
<div class="field-item even">
<h2 style="margin-top: 0px; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Features and benefits</h2>
<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px;"><li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Campus infrastructure integration</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Regular and scheduled maintenance</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Prioritized HelpSU problem resolution</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Security auditing and system hardening</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">User and workgroup management</li>
</ul><h2 style="margin-top: 1.4em; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Getting started</h2>
<p style="margin-top: 0px;">To learn more about contract server support, please contact <a href="https://stanfordwho.stanford.edu/SWApp/auth/lookup?search=Noah%20Abrahamson" style="color: rgb(130, 114, 82); border-bottom-style: dotted; border-bottom-width: 1px; border-bottom-color: rgb(130, 114, 82);">Noah Abrahamson</a> or <a href="http://helpsu.stanford.edu/" style="color: rgb(130, 114, 82); border-bottom-style: dotted; border-bottom-width: 1px; border-bottom-color: rgb(130, 114, 82);">submit a HelpSU request</a>.</p>
<h2 style="margin-top: 1.4em; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Learn more</h2>
<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px;"><li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;"><a href="https://itservices.stanford.edu/service/contract-support/server" style="color: rgb(130, 114, 82); border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: rgb(130, 114, 82);">Server Group (CRC)</a></li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;"><a href="https://itservices.stanford.edu/service/server-support/businessdocuments" style="color: rgb(130, 114, 82); border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: rgb(130, 114, 82);">Business Documents for Contract Support — Server Support</a></li>
</ul></div>
</div>
</div>
<p> </p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_slac_sc_service_overview' => array(
    'und' => array(
      0 => array(
        'value' => 'The Server Support service provides complete server management, including installation and stabilization, monitoring, security, user management, and integration with the campus infrastructure, for systems running modern Mac OS X Server and Windows Server operating systems.',
        'format' => NULL,
        'safe_value' => 'The Server Support service provides complete server management, including installation and stabilization, monitoring, security, user management, and integration with the campus infrastructure, for systems running modern Mac OS X Server and Windows Server operating systems.',
      ),
    ),
  ),
  'field_slac_sc_eligibility' => array(
    'und' => array(
      0 => array(
        'tid' => 62,
        'uuid' => '9d88d219-f7e7-4354-b6ce-accadf586640',
      ),
      1 => array(
        'tid' => 60,
        'uuid' => '00e2fef3-0966-49ed-8f3d-e3f8d1cd46c0',
      ),
    ),
  ),
  'field_slac_sc_requirements' => array(
    'und' => array(
      0 => array(
        'value' => 'Demonstrate need for support',
        'format' => NULL,
        'safe_value' => 'Demonstrate need for support',
      ),
      1 => array(
        'value' => 'L2 Access or above',
        'format' => NULL,
        'safe_value' => 'L2 Access or above',
      ),
    ),
  ),
  'field_slac_sc_support' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Support is provided by SLAC IT services.</p>
',
        'format' => 'full_html',
        'safe_value' => '<p>Support is provided by SLAC IT services.</p>
',
      ),
    ),
  ),
  'field_slac_sc_rate' => array(),
  'field_slac_sc_request_link' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.slac.stanford.edu',
        'title' => NULL,
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_sc_category' => array(
    'und' => array(
      0 => array(
        'tid' => 45,
        'uuid' => 'cf2ef1a1-ee93-434b-a103-a0a123dcc6aa',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-26 09:49:24 -0700',
  'author_uuid' => '2f4dc695-a129-4c43-8441-07db6781150a',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Contract Support',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '00caf1e7-6cb5-4072-8796-fcced531fb7b',
  'type' => 'slac_sc_catalog_item',
  'language' => 'und',
  'created' => 1377536170,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '3e9cb6c4-dd27-4d28-966e-2bbb5c462b9d',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<div class="field field-name-field-service-overview field-type-text-long field-label-hidden" style="margin-bottom: 20px;">
	<div class="field-items">
		<div class="field-item even">
			<p style="margin-top: 0px;">OnCall Services is a great way for departments to supplement existing support staff during vacations and other leaves, or to handle special projects. For small groups that don&rsquo;t need full-time support, we can offer scheduled or pre-arranged occasional support in your office. For faculty, staff, and students, OnCall Services offers a cost-effective way to get expert computer assistance from highly knowledgeable technical staff who understand Stanford&rsquo;s unique computing environment.</p>
		</div>
	</div>
</div>
<div class="field field-name-body field-type-text-with-summary field-label-hidden" style="margin-bottom: 20px;">
	<div class="field-items">
		<div class="field-item even">
			<h2 style="margin-top: 0px; margin-bottom: 12px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; border-bottom-width: medium; border-bottom-style: none; background-color: rgb(251, 251, 249);">Features</h2>
			<p style="margin-top: 0px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">We offer a wide range of services, including:</p>
			<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Diagnose and troubleshoot almost any computer problem</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Proactive system security checkups and updates</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Setup and installation of new machines</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Install and upgrade Mac and Windows operating systems</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Install and troubleshoot Stanford-supported applications or licensed third-party applications (you supply the license)</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Add peripherals such as printers or scanners</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Help protect and backup important data</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Remove prying spyware and contain virus outbreaks</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">PDA setup and configuration</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Project work, such as computer upgrades or departmental moves</li>
				<li>&nbsp;</li>
			</ul>
		</div>
	</div>
</div>
<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<div class="field field-name-field-service-overview field-type-text-long field-label-hidden" style="margin-bottom: 20px;">
<div class="field-items">
<div class="field-item even">
<p style="margin-top: 0px;">OnCall Services is a great way for departments to supplement existing support staff during vacations and other leaves, or to handle special projects. For small groups that don’t need full-time support, we can offer scheduled or pre-arranged occasional support in your office. For faculty, staff, and students, OnCall Services offers a cost-effective way to get expert computer assistance from highly knowledgeable technical staff who understand Stanford’s unique computing environment.</p>
</div>
</div>
</div>
<div class="field field-name-body field-type-text-with-summary field-label-hidden" style="margin-bottom: 20px;">
<div class="field-items">
<div class="field-item even">
<h2 style="margin-top: 0px; margin-bottom: 12px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; border-bottom-width: medium; border-bottom-style: none; background-color: rgb(251, 251, 249);">Features</h2>
<p style="margin-top: 0px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">We offer a wide range of services, including:</p>
<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);"><li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Diagnose and troubleshoot almost any computer problem</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Proactive system security checkups and updates</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Setup and installation of new machines</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Install and upgrade Mac and Windows operating systems</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Install and troubleshoot Stanford-supported applications or licensed third-party applications (you supply the license)</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Add peripherals such as printers or scanners</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Help protect and backup important data</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Remove prying spyware and contain virus outbreaks</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">PDA setup and configuration</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">Project work, such as computer upgrades or departmental moves</li>
<li> </li>
</ul></div>
</div>
</div>
<p> </p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_slac_sc_service_overview' => array(
    'und' => array(
      0 => array(
        'value' => 'OnCall Services is a great way for departments to supplement existing support staff during vacations and other leaves, or to handle special projects. For small groups that don’t need full-time support, we can offer scheduled or pre-arranged occasional support in your office. For faculty, staff, and students, OnCall Services offers a cost-effective way to get expert computer assistance from highly knowledgeable technical staff who understand Stanford’s unique computing environment.',
        'format' => NULL,
        'safe_value' => 'OnCall Services is a great way for departments to supplement existing support staff during vacations and other leaves, or to handle special projects. For small groups that don’t need full-time support, we can offer scheduled or pre-arranged occasional support in your office. For faculty, staff, and students, OnCall Services offers a cost-effective way to get expert computer assistance from highly knowledgeable technical staff who understand Stanford’s unique computing environment.',
      ),
    ),
  ),
  'field_slac_sc_eligibility' => array(),
  'field_slac_sc_requirements' => array(),
  'field_slac_sc_support' => array(
    'und' => array(
      0 => array(
        'value' => '<p>If you have questions about how OnCall Services can assist you, please submit a HelpSU request or call or 5-HELP (725-4357).</p>
',
        'format' => 'full_html',
        'safe_value' => '<p>If you have questions about how OnCall Services can assist you, please submit a HelpSU request or call or 5-HELP (725-4357).</p>
',
      ),
      1 => array(
        'value' => 'Services are available either in your campus office or at our offices on campus. Carry-In services are performed by appointment and need to be arranged in advance.',
        'format' => 'full_html',
        'safe_value' => '<p>Services are available either in your campus office or at our offices on campus. Carry-In services are performed by appointment and need to be arranged in advance.</p>
',
      ),
    ),
  ),
  'field_slac_sc_rate' => array(
    'und' => array(
      0 => array(
        'value' => 'Please see table',
        'format' => NULL,
        'safe_value' => 'Please see table',
      ),
    ),
  ),
  'field_slac_sc_request_link' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.slac.stanford.edu',
        'title' => NULL,
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_sc_category' => array(
    'und' => array(
      0 => array(
        'tid' => 48,
        'uuid' => '04690b24-a63c-403b-a4ee-b0f96929f27b',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-26 09:56:10 -0700',
  'author_uuid' => '2f4dc695-a129-4c43-8441-07db6781150a',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'MySQL & Oracle',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '3bf1b2cc-f232-4b57-ac7f-cb4fdcf75c64',
  'type' => 'slac_sc_catalog_item',
  'language' => 'und',
  'created' => 1377536036,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '6a46ab90-371c-490f-9b48-7679886d1764',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<div class="field field-name-field-service-overview field-type-text-long field-label-hidden" style="margin-bottom: 20px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">
	<div class="field-items">
		<div class="field-item even">
			<p style="margin-top: 0px;">A variety of complementary Database Administration-related services such as Oracle Real Application Cluster (RAC) support are also available via Ntirety. The Database Administration service provides reliable, secure, and cost-effective database administration, including maintenance, monitoring, and backup.</p>
			<p style="margin-top: 0px;">24x7 support is provided for production or critical development databases. In addition to standard, day-to-day administrative and maintenance activities, production or critical development databases are continuously monitored to detect potential problems, proactively addressing problems before they can affect service delivery.</p>
			<p style="margin-top: 0px;">The Database Administration service is available by subscription and is charged monthly to your department&rsquo;s IT Services bill.</p>
		</div>
	</div>
</div>
<div class="field field-name-body field-type-text-with-summary field-label-hidden" style="margin-bottom: 20px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">
	<div class="field-items">
		<div class="field-item even">
			<h2 style="margin-top: 0px; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Features</h2>
			<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px;">
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">monitors and tunes production database environments</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">rapidly responds to critical issues</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">provides backup and recovery, prevents database outage</li>
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">works directly with clients to solve database issues</li>
			</ul>
			<h2 style="margin-top: 1.4em; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Getting started</h2>
			<p style="margin-top: 0px;">To order the Database Administration service use&nbsp;<a href="http://orderit.stanford.edu/" style="color: rgb(130, 114, 82); border-bottom-style: dotted; border-bottom-width: 1px; border-bottom-color: rgb(130, 114, 82);">OrderIT</a>&nbsp;or submit a&nbsp;<a href="http://helpsu.stanford.edu/?pcat=dba" style="color: rgb(130, 114, 82); border-bottom-style: dotted; border-bottom-width: 1px; border-bottom-color: rgb(130, 114, 82);">HelpSU request</a>&nbsp;under the Request Category: Billable Services and the Request Type: Database Administration Services.</p>
			<h2 style="margin-top: 1.4em; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Learn more</h2>
			<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px;">
				<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;"><a href="https://itservices.stanford.edu/service/databaseadministration/businessdocuments" style="color: rgb(130, 114, 82); border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: rgb(130, 114, 82);">Business Documents for Database Administration</a></li>
			</ul>
		</div>
	</div>
</div>
<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<div class="field field-name-field-service-overview field-type-text-long field-label-hidden" style="margin-bottom: 20px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">
<div class="field-items">
<div class="field-item even">
<p style="margin-top: 0px;">A variety of complementary Database Administration-related services such as Oracle Real Application Cluster (RAC) support are also available via Ntirety. The Database Administration service provides reliable, secure, and cost-effective database administration, including maintenance, monitoring, and backup.</p>
<p style="margin-top: 0px;">24x7 support is provided for production or critical development databases. In addition to standard, day-to-day administrative and maintenance activities, production or critical development databases are continuously monitored to detect potential problems, proactively addressing problems before they can affect service delivery.</p>
<p style="margin-top: 0px;">The Database Administration service is available by subscription and is charged monthly to your department’s IT Services bill.</p>
</div>
</div>
</div>
<div class="field field-name-body field-type-text-with-summary field-label-hidden" style="margin-bottom: 20px; font-family: \'Source Sans Pro\', Arial, Helvetica, sans-serif; font-size: 14px; line-height: 19.59375px; background-color: rgb(251, 251, 249);">
<div class="field-items">
<div class="field-item even">
<h2 style="margin-top: 0px; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Features</h2>
<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px;"><li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">monitors and tunes production database environments</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">rapidly responds to critical issues</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">provides backup and recovery, prevents database outage</li>
<li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;">works directly with clients to solve database issues</li>
</ul><h2 style="margin-top: 1.4em; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Getting started</h2>
<p style="margin-top: 0px;">To order the Database Administration service use <a href="http://orderit.stanford.edu/" style="color: rgb(130, 114, 82); border-bottom-style: dotted; border-bottom-width: 1px; border-bottom-color: rgb(130, 114, 82);">OrderIT</a> or submit a <a href="http://helpsu.stanford.edu/?pcat=dba" style="color: rgb(130, 114, 82); border-bottom-style: dotted; border-bottom-width: 1px; border-bottom-color: rgb(130, 114, 82);">HelpSU request</a> under the Request Category: Billable Services and the Request Type: Database Administration Services.</p>
<h2 style="margin-top: 1.4em; margin-bottom: 12px; font-family: inherit; font-weight: normal; line-height: 1.2em; color: rgb(130, 0, 0); text-rendering: optimizelegibility; font-size: 20px; letter-spacing: 0.01em; border-bottom-width: medium; border-bottom-style: none;">Learn more</h2>
<ul style="margin-top: 0px; margin-bottom: 10px; margin-left: 25px;"><li style="line-height: 20px; list-style-type: square; list-style-image: url(https://itservices.stanford.edu/sites/all/themes/stanford_wilbur/images/bullet.gif); margin-bottom: 0.25em;"><a href="https://itservices.stanford.edu/service/databaseadministration/businessdocuments" style="color: rgb(130, 114, 82); border-bottom-width: 1px; border-bottom-style: dotted; border-bottom-color: rgb(130, 114, 82);">Business Documents for Database Administration</a></li>
</ul></div>
</div>
</div>
<p> </p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_slac_sc_service_overview' => array(
    'und' => array(
      0 => array(
        'value' => 'IT Services has partnered with Ntirety Corporation to support Oracle and Microsoft SQL databases for the Stanford community. This service is available to faculty and staff in academic and administrative departments that require database administration for applications, or standalone databases operating on Stanford infrastructure.',
        'format' => NULL,
        'safe_value' => 'IT Services has partnered with Ntirety Corporation to support Oracle and Microsoft SQL databases for the Stanford community. This service is available to faculty and staff in academic and administrative departments that require database administration for applications, or standalone databases operating on Stanford infrastructure.',
      ),
    ),
  ),
  'field_slac_sc_eligibility' => array(
    'und' => array(
      0 => array(
        'tid' => 62,
        'uuid' => '9d88d219-f7e7-4354-b6ce-accadf586640',
      ),
      1 => array(
        'tid' => 60,
        'uuid' => '00e2fef3-0966-49ed-8f3d-e3f8d1cd46c0',
      ),
    ),
  ),
  'field_slac_sc_requirements' => array(),
  'field_slac_sc_support' => array(
    'und' => array(
      0 => array(
        'value' => '24x7 support for production or critical development databases.
',
        'format' => 'plain_text',
        'safe_value' => '<p>24x7 support for production or critical development databases.</p>
',
      ),
      1 => array(
        'value' => 'Notification to an administrator within 15 minutes of an alert or emergency declaration by the customer. Response back to customer within 30 minutes of receipt of the alert by the administrator.',
        'format' => 'plain_text',
        'safe_value' => '<p>Notification to an administrator within 15 minutes of an alert or emergency declaration by the customer. Response back to customer within 30 minutes of receipt of the alert by the administrator.</p>
',
      ),
      2 => array(
        'value' => 'Standard development and test database support is provided Monday through Friday, 8 a.m. to 5 p.m.',
        'format' => 'plain_text',
        'safe_value' => '<p>Standard development and test database support is provided Monday through Friday, 8 a.m. to 5 p.m.</p>
',
      ),
    ),
  ),
  'field_slac_sc_rate' => array(
    'und' => array(
      0 => array(
        'value' => '$50 per database',
        'format' => NULL,
        'safe_value' => '$50 per database',
      ),
    ),
  ),
  'field_slac_sc_request_link' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.slac.stanford.edu',
        'title' => NULL,
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_sc_category' => array(
    'und' => array(
      0 => array(
        'tid' => 47,
        'uuid' => 'ac074ab7-4b52-4911-a6b0-3d92f247aa2a',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-26 09:53:56 -0700',
  'author_uuid' => '2f4dc695-a129-4c43-8441-07db6781150a',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Conference computing for visitors',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'def6fb0a-cb97-4191-907e-455a79766407',
  'type' => 'slac_sc_catalog_item',
  'language' => 'und',
  'created' => 1377535854,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '7cd09391-5cdc-42a2-80d2-ece053ab13e8',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2 style="font-size: large; color: rgb(153, 0, 0); font-family: Arial, Helvetica, sans-serif; line-height: normal;">Computing Resources for Short Term Visitors</h2>
<p style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">Visitors of SLAC who are attending conferences, meetings, or short collaborations should review the following computing resources that are available for public use. Visitors staying longer than a few days or those requiring access to SLAC-only resources should register as an Active User with the&nbsp;<a href="http://www.slac.stanford.edu/grp/rd/sluo/SLUO.html#SLUO" style="text-decoration: underline; color: rgb(102, 51, 102);">SLAC Users Organization</a>&nbsp;to become eligible to open a SLAC computer account.<br />
	&nbsp;</p>
<table border="0" cellpadding="5" cellspacing="0" style="font-size: 1em; font-family: Verdana, Helvetica, Arial, sans-serif; list-style-position: inside;" width="100%">
	<tbody>
		<tr style="font-size: 1em; list-style-position: inside;">
			<td style="font-size: 1em; list-style-position: inside;" width="10"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
			<td style="font-size: 1em; list-style-position: inside;" width="200"><a href="http://www2.slac.stanford.edu/comp/net/wireless/visitor_net.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">SLAC Visitor Network</a></td>
			<td style="font-size: 1em; list-style-position: inside;">:: Information about the public computing network at SLAC</td>
		</tr>
		<tr style="font-size: 1em; list-style-position: inside;">
			<td style="font-size: 1em; list-style-position: inside;"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
			<td style="font-size: 1em; list-style-position: inside;"><a href="http://www2.slac.stanford.edu/comp/net/wireless/" style="text-decoration: underline; color: rgb(102, 51, 102);">Wireless Networking</a></td>
			<td style="font-size: 1em; list-style-position: inside;">:: Wireless ( 802.11b ) network access at SLAC</td>
		</tr>
		<tr style="font-size: 1em; list-style-position: inside;">
			<td style="font-size: 1em; list-style-position: inside;"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
			<td style="font-size: 1em; list-style-position: inside;"><a href="http://www2.slac.stanford.edu/computing/helpdesk/visitor/resources.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Computing Resources</a></td>
			<td style="font-size: 1em; list-style-position: inside;">:: Computing resources for public use at SLAC</td>
		</tr>
	</tbody>
</table>
<p style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">&nbsp;</p>
<h2 style="font-size: large; color: rgb(153, 0, 0); font-family: Arial, Helvetica, sans-serif; line-height: normal;">Conference Computing Information</h2>
<p style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">Organizers of conferences held at SLAC should review the following information regarding the setup of conferences and talks.</p>
<table border="0" cellpadding="5" cellspacing="0" style="font-size: 1em; font-family: Verdana, Helvetica, Arial, sans-serif; list-style-position: inside;" width="100%">
	<tbody>
		<tr style="font-size: 1em; list-style-position: inside;">
			<td style="font-size: 1em; list-style-position: inside;" width="10"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
			<td style="font-size: 1em; list-style-position: inside;" width="200"><a href="http://www.slac.stanford.edu/grp/pao/slaconly.conference.html" style="text-decoration: underline; color: rgb(102, 51, 102);">Overview</a></td>
			<td style="font-size: 1em; list-style-position: inside;">:: General conference computing information</td>
		</tr>
		<tr style="font-size: 1em; list-style-position: inside;">
			<td style="font-size: 1em; list-style-position: inside;"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
			<td style="font-size: 1em; list-style-position: inside;"><a href="http://www2.slac.stanford.edu/computing/helpdesk/visitor/confchecklist.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Checklist</a></td>
			<td style="font-size: 1em; list-style-position: inside;">:: Issues and caveats</td>
		</tr>
		<tr style="font-size: 1em; list-style-position: inside;">
			<td style="font-size: 1em; list-style-position: inside;"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
			<td style="font-size: 1em; list-style-position: inside;"><a href="http://www2.slac.stanford.edu/computing/helpdesk/visitor/computingsetup.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Conference Room Setups</a></td>
			<td style="font-size: 1em; list-style-position: inside;">:: Conference room layouts and equipment types</td>
		</tr>
	</tbody>
</table>
<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<h2 style="font-size: large; color: rgb(153, 0, 0); font-family: Arial, Helvetica, sans-serif; line-height: normal;">Computing Resources for Short Term Visitors</h2>
<p style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">Visitors of SLAC who are attending conferences, meetings, or short collaborations should review the following computing resources that are available for public use. Visitors staying longer than a few days or those requiring access to SLAC-only resources should register as an Active User with the <a href="http://www.slac.stanford.edu/grp/rd/sluo/SLUO.html#SLUO" style="text-decoration: underline; color: rgb(102, 51, 102);">SLAC Users Organization</a> to become eligible to open a SLAC computer account.<br />
	 </p>
<table border="0" cellpadding="5" cellspacing="0" style="font-size: 1em; font-family: Verdana, Helvetica, Arial, sans-serif; list-style-position: inside;" width="100%"><tbody><tr style="font-size: 1em; list-style-position: inside;"><td style="font-size: 1em; list-style-position: inside;" width="10"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
<td style="font-size: 1em; list-style-position: inside;" width="200"><a href="http://www2.slac.stanford.edu/comp/net/wireless/visitor_net.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">SLAC Visitor Network</a></td>
<td style="font-size: 1em; list-style-position: inside;">:: Information about the public computing network at SLAC</td>
</tr><tr style="font-size: 1em; list-style-position: inside;"><td style="font-size: 1em; list-style-position: inside;"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
<td style="font-size: 1em; list-style-position: inside;"><a href="http://www2.slac.stanford.edu/comp/net/wireless/" style="text-decoration: underline; color: rgb(102, 51, 102);">Wireless Networking</a></td>
<td style="font-size: 1em; list-style-position: inside;">:: Wireless ( 802.11b ) network access at SLAC</td>
</tr><tr style="font-size: 1em; list-style-position: inside;"><td style="font-size: 1em; list-style-position: inside;"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
<td style="font-size: 1em; list-style-position: inside;"><a href="http://www2.slac.stanford.edu/computing/helpdesk/visitor/resources.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Computing Resources</a></td>
<td style="font-size: 1em; list-style-position: inside;">:: Computing resources for public use at SLAC</td>
</tr></tbody></table><p style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"> </p>
<h2 style="font-size: large; color: rgb(153, 0, 0); font-family: Arial, Helvetica, sans-serif; line-height: normal;">Conference Computing Information</h2>
<p style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">Organizers of conferences held at SLAC should review the following information regarding the setup of conferences and talks.</p>
<table border="0" cellpadding="5" cellspacing="0" style="font-size: 1em; font-family: Verdana, Helvetica, Arial, sans-serif; list-style-position: inside;" width="100%"><tbody><tr style="font-size: 1em; list-style-position: inside;"><td style="font-size: 1em; list-style-position: inside;" width="10"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
<td style="font-size: 1em; list-style-position: inside;" width="200"><a href="http://www.slac.stanford.edu/grp/pao/slaconly.conference.html" style="text-decoration: underline; color: rgb(102, 51, 102);">Overview</a></td>
<td style="font-size: 1em; list-style-position: inside;">:: General conference computing information</td>
</tr><tr style="font-size: 1em; list-style-position: inside;"><td style="font-size: 1em; list-style-position: inside;"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
<td style="font-size: 1em; list-style-position: inside;"><a href="http://www2.slac.stanford.edu/computing/helpdesk/visitor/confchecklist.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Checklist</a></td>
<td style="font-size: 1em; list-style-position: inside;">:: Issues and caveats</td>
</tr><tr style="font-size: 1em; list-style-position: inside;"><td style="font-size: 1em; list-style-position: inside;"><img src="http://www2.slac.stanford.edu/computing/helpdesk/images/arrow2.gif" /></td>
<td style="font-size: 1em; list-style-position: inside;"><a href="http://www2.slac.stanford.edu/computing/helpdesk/visitor/computingsetup.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Conference Room Setups</a></td>
<td style="font-size: 1em; list-style-position: inside;">:: Conference room layouts and equipment types</td>
</tr></tbody></table><p> </p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_slac_sc_service_overview' => array(
    'und' => array(
      0 => array(
        'value' => 'Visitors of SLAC who are attending conferences, meetings, or short collaborations should review the following computing resources that are available for public use. Visitors staying longer than a few days or those requiring access to SLAC-only resources should register as an Active User with the SLAC Users Organization to become eligible to open a SLAC computer account.',
        'format' => NULL,
        'safe_value' => 'Visitors of SLAC who are attending conferences, meetings, or short collaborations should review the following computing resources that are available for public use. Visitors staying longer than a few days or those requiring access to SLAC-only resources should register as an Active User with the SLAC Users Organization to become eligible to open a SLAC computer account.',
      ),
    ),
  ),
  'field_slac_sc_eligibility' => array(
    'und' => array(
      0 => array(
        'tid' => 61,
        'uuid' => 'db10ac33-21ec-4d40-bee7-1c34780f1b40',
      ),
      1 => array(
        'tid' => 63,
        'uuid' => 'f3037fca-b840-4394-9c4e-03ea14b6c4bf',
      ),
    ),
  ),
  'field_slac_sc_requirements' => array(
    'und' => array(
      0 => array(
        'value' => 'This service is only offered to visitor to the LAB',
        'format' => NULL,
        'safe_value' => 'This service is only offered to visitor to the LAB',
      ),
    ),
  ),
  'field_slac_sc_support' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Support is provided by SLAC IT Services</p>
',
        'format' => 'full_html',
        'safe_value' => '<p>Support is provided by SLAC IT Services</p>
',
      ),
    ),
  ),
  'field_slac_sc_rate' => array(),
  'field_slac_sc_request_link' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.slac.stanford.edu',
        'title' => NULL,
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_sc_category' => array(
    'und' => array(
      0 => array(
        'tid' => 46,
        'uuid' => '83b5b76c-6bd8-4a0c-a580-6aa8b22d9f63',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-26 09:50:54 -0700',
  'author_uuid' => '2f4dc695-a129-4c43-8441-07db6781150a',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Computer accounts',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '95871dc2-275c-4be7-8a4c-e1979c003b8a',
  'type' => 'slac_sc_catalog_item',
  'language' => 'und',
  'created' => 1377535432,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '80cf77e8-afe3-4217-874e-72d79d5d5ad7',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<dl>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Platforms</dt>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www2.slac.stanford.edu/comp/slacwide/account/account.html" style="text-decoration: underline; color: rgb(102, 51, 102);">Windows</a>&nbsp;:: Microsoft Windows Accounts.
		<ul>
			<li>There are SLAC Windows domain accounts for site-wide centrally maintained Windows applications.</li>
			<li>There are two types of COLLAB Windows domain accounts: Individual and Group. Currently only SharePoint supports COLLAB domain accounts.&nbsp;Request an account via email to&nbsp;<a href="mailto:windows-admin@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">windows-admin@slac.stanford.edu</a>
				<ul>
					<li>COLLAB Group accounts are limited to read-only access.</li>
					<li>COLLAB Individual accounts are allowed read/write access.</li>
				</ul>
			</li>
		</ul>
	</dd>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www2.slac.stanford.edu/comp/slacwide/account/account.html" style="text-decoration: underline; color: rgb(102, 51, 102);">Unix</a>&nbsp;:: Central Unix</dd>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www2.slac.stanford.edu/computing/windows/services/citrix/" style="text-decoration: underline; color: rgb(102, 51, 102);">WTS</a>&nbsp;:: Windows Terminal Server (Citrix)</dd>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Connectivity (Remote Access)</dt>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/comp/winnt/SLACONLY/pptp/default.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">VPN</a>&nbsp;:: Virtual Private Networking</dd>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www2.slac.stanford.edu/computing/windows/services/citrix/xa6/account/default.aspx" style="text-decoration: underline; color: rgb(102, 51, 102);">Citrix</a>&nbsp;:: Citrix Service</dd>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Applications</dt>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
		<p style="margin-top: 0px; margin-bottom: 2px;">Exchange :: Send mail to&nbsp;<a href="mailto:mail-admin@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">mail-admin@slac.stanford.edu</a></p>
	</dd>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
		<p style="margin-top: 0px; margin-bottom: 2px;">Oracle :: Send mail to&nbsp;<a href="mailto:db-admin@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">db-admin@slac.stanford.edu</a></p>
		<dl>
			<dd style="padding-bottom: 6px;">
				<p style="margin-top: 0px; margin-bottom: -3px;">Oracle password change&nbsp;<a href="https://oraweb.slac.stanford.edu/pls/slac/change_my_password" style="text-decoration: underline; color: rgb(102, 51, 102);">https://oraweb.slac.stanford.edu/pls/slac/change_my_password</a></p>
			</dd>
		</dl>
	</dd>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
		<p style="margin-top: 0px; margin-bottom: 0px;">PeopleSoft :: Send mail to&nbsp;<a href="mailto:ps-admin@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">ps-admin@slac.stanford.edu</a></p>
	</dd>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Stanford University Computer Accounts</dt>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www.stanford.edu/dept/as/mais/applications/sunetid/index.html" style="text-decoration: underline; color: rgb(102, 51, 102);">Getting a Stanford University ID (SUNet ID)</a></dd>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Administrative Tasks</dt>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www-group.slac.stanford.edu/bsd/sid_entry.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Getting a SLAC ID number</a>&nbsp;:: Newcomers to SLAC who need to receive an identification badge, a dosimeter, a computer account, a phone, or any other services, must be entered into the SLAC Institutional Database (SID).</dd>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/database/pages/czarlist.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Finding your Computer Czar</a>&nbsp;:: List of Computer Czar (People who can authorize comptuer accounts, changes, and deletions.)</dd>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/comp/admin/pages/account-search.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Search for accounts</a>&nbsp;:: Find computing accounts for specific users</dd>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/instdatabase/procedures/computer-accounts/account-delete.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Closing Accounts</a></dd>
	<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/instdatabase/procedures/computer-accounts/account-delete.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Terminating SLAC Employees</a>&nbsp;:: Procedures for computer accounts</dd>
</dl>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<dl><dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Platforms</dt>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www2.slac.stanford.edu/comp/slacwide/account/account.html" style="text-decoration: underline; color: rgb(102, 51, 102);">Windows</a> :: Microsoft Windows Accounts.
<ul><li>There are SLAC Windows domain accounts for site-wide centrally maintained Windows applications.</li>
<li>There are two types of COLLAB Windows domain accounts: Individual and Group. Currently only SharePoint supports COLLAB domain accounts. Request an account via email to <a href="mailto:windows-admin@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">windows-admin@slac.stanford.edu</a>
<ul><li>COLLAB Group accounts are limited to read-only access.</li>
<li>COLLAB Individual accounts are allowed read/write access.</li>
</ul></li>
</ul></dd>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www2.slac.stanford.edu/comp/slacwide/account/account.html" style="text-decoration: underline; color: rgb(102, 51, 102);">Unix</a> :: Central Unix</dd>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www2.slac.stanford.edu/computing/windows/services/citrix/" style="text-decoration: underline; color: rgb(102, 51, 102);">WTS</a> :: Windows Terminal Server (Citrix)</dd>
<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Connectivity (Remote Access)</dt>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/comp/winnt/SLACONLY/pptp/default.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">VPN</a> :: Virtual Private Networking</dd>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www2.slac.stanford.edu/computing/windows/services/citrix/xa6/account/default.aspx" style="text-decoration: underline; color: rgb(102, 51, 102);">Citrix</a> :: Citrix Service</dd>
<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Applications</dt>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
<p style="margin-top: 0px; margin-bottom: 2px;">Exchange :: Send mail to <a href="mailto:mail-admin@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">mail-admin@slac.stanford.edu</a></p>
</dd>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
<p style="margin-top: 0px; margin-bottom: 2px;">Oracle :: Send mail to <a href="mailto:db-admin@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">db-admin@slac.stanford.edu</a></p>
<dl><dd style="padding-bottom: 6px;">
<p style="margin-top: 0px; margin-bottom: -3px;">Oracle password change <a href="https://oraweb.slac.stanford.edu/pls/slac/change_my_password" style="text-decoration: underline; color: rgb(102, 51, 102);">https://oraweb.slac.stanford.edu/pls/slac/change_my_password</a></p>
</dd>
</dl></dd>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
<p style="margin-top: 0px; margin-bottom: 0px;">PeopleSoft :: Send mail to <a href="mailto:ps-admin@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">ps-admin@slac.stanford.edu</a></p>
</dd>
<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Stanford University Computer Accounts</dt>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www.stanford.edu/dept/as/mais/applications/sunetid/index.html" style="text-decoration: underline; color: rgb(102, 51, 102);">Getting a Stanford University ID (SUNet ID)</a></dd>
<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-weight: bold; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Administrative Tasks</dt>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="http://www-group.slac.stanford.edu/bsd/sid_entry.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Getting a SLAC ID number</a> :: Newcomers to SLAC who need to receive an identification badge, a dosimeter, a computer account, a phone, or any other services, must be entered into the SLAC Institutional Database (SID).</dd>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/database/pages/czarlist.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Finding your Computer Czar</a> :: List of Computer Czar (People who can authorize comptuer accounts, changes, and deletions.)</dd>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/comp/admin/pages/account-search.asp" style="text-decoration: underline; color: rgb(102, 51, 102);">Search for accounts</a> :: Find computing accounts for specific users</dd>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/instdatabase/procedures/computer-accounts/account-delete.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Closing Accounts</a></dd>
<dd style="padding-bottom: 6px; font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><a href="https://www-internal.slac.stanford.edu/instdatabase/procedures/computer-accounts/account-delete.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Terminating SLAC Employees</a> :: Procedures for computer accounts</dd>
</dl>',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_slac_sc_service_overview' => array(
    'und' => array(
      0 => array(
        'value' => 'Windows :: Microsoft Windows Accounts.
There are SLAC Windows domain accounts for site-wide centrally maintained Windows applications.
There are two types of COLLAB Windows domain accounts: Individual and Group. Currently only SharePoint supports COLLAB domain accounts. Request an account via email to windows-admin@slac.stanford.edu
COLLAB Group accounts are limited to read-only access.
COLLAB Individual accounts are allowed read/write access.
Unix :: Central Unix
WTS :: Windows Terminal Server (Citrix)',
        'format' => NULL,
        'safe_value' => 'Windows :: Microsoft Windows Accounts.
There are SLAC Windows domain accounts for site-wide centrally maintained Windows applications.
There are two types of COLLAB Windows domain accounts: Individual and Group. Currently only SharePoint supports COLLAB domain accounts. Request an account via email to windows-admin@slac.stanford.edu
COLLAB Group accounts are limited to read-only access.
COLLAB Individual accounts are allowed read/write access.
Unix :: Central Unix
WTS :: Windows Terminal Server (Citrix)',
      ),
    ),
  ),
  'field_slac_sc_eligibility' => array(
    'und' => array(
      0 => array(
        'tid' => 61,
        'uuid' => 'db10ac33-21ec-4d40-bee7-1c34780f1b40',
      ),
      1 => array(
        'tid' => 63,
        'uuid' => 'f3037fca-b840-4394-9c4e-03ea14b6c4bf',
      ),
      2 => array(
        'tid' => 62,
        'uuid' => '9d88d219-f7e7-4354-b6ce-accadf586640',
      ),
      3 => array(
        'tid' => 60,
        'uuid' => '00e2fef3-0966-49ed-8f3d-e3f8d1cd46c0',
      ),
    ),
  ),
  'field_slac_sc_requirements' => array(
    'und' => array(
      0 => array(
        'value' => 'Must finish ES&H Safety Training',
        'format' => NULL,
        'safe_value' => 'Must finish ES&amp;H Safety Training',
      ),
      1 => array(
        'value' => 'Obtain valid security badge',
        'format' => NULL,
        'safe_value' => 'Obtain valid security badge',
      ),
    ),
  ),
  'field_slac_sc_support' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Support is provided by SLAC IT services</p>
',
        'format' => 'full_html',
        'safe_value' => '<p>Support is provided by SLAC IT services</p>
',
      ),
    ),
  ),
  'field_slac_sc_rate' => array(
    'und' => array(
      0 => array(
        'value' => 'Free of charge',
        'format' => NULL,
        'safe_value' => 'Free of charge',
      ),
    ),
  ),
  'field_slac_sc_request_link' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.slac.stanford.edu',
        'title' => NULL,
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_sc_category' => array(
    'und' => array(
      0 => array(
        'tid' => 44,
        'uuid' => '40e140d3-4f65-481f-a68f-6d3f43161e13',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-26 09:43:52 -0700',
  'author_uuid' => '2f4dc695-a129-4c43-8441-07db6781150a',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'SLAC Email',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '213369af-162a-4749-a726-280e18a5531f',
  'type' => 'slac_sc_catalog_item',
  'language' => 'und',
  'created' => 1377536292,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b5a334a9-7c3c-453c-ba37-1c1a4547568d',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<dl>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Client Configurations and Forwarding</dt>
</dl>
<blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
	<table border="0" id="table6" style="font-size: 1em;" width="100%">
		<tbody>
			<tr style="font-size: 1em;">
				<td style="font-size: 1em;" width="50%"><a href="http://www2.slac.stanford.edu/comp/messaging/Installing/default.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Install &amp; Configure Pages</a></td>
				<td style="font-size: 1em;" width="50%"><a href="https://email.slac.stanford.edu/owa" style="text-decoration: underline; color: rgb(102, 51, 102);">Read E-mail via Web Now</a></td>
			</tr>
			<tr style="font-size: 1em;">
				<td style="font-size: 1em;" width="50%"><a href="http://www2.slac.stanford.edu/comp/messaging/Reference/exch2007-whattoexpect.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">What to Expect with Exchange 2007</a></td>
				<td style="font-size: 1em;" width="50%">&nbsp;</td>
			</tr>
		</tbody>
	</table>
</blockquote>
<dl>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Frequently Asked Questions</dt>
</dl>
<blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
	<table border="0" id="table7" style="font-size: 1em;" width="100%">
		<tbody>
			<tr style="font-size: 1em;">
				<td style="font-size: 1em;" width="50%"><a href="http://www2.slac.stanford.edu/comp/messaging/faq/default.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">General FAQ</a></td>
				<td style="font-size: 1em;" width="50%"><a href="http://www2.slac.stanford.edu/comp/messaging/faq/errroranswer.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Error Messages &amp; Answers</a></td>
			</tr>
		</tbody>
	</table>
</blockquote>
<dl>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Mailing Lists</dt>
</dl>
<blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
	<table border="0" id="table4" style="font-size: 1em;" width="100%">
		<tbody>
			<tr style="font-size: 1em;">
				<td style="font-size: 1em;" width="33%"><a href="http://www2.slac.stanford.edu/comp/messaging/Reference/mailinglists.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Description of Mailing Lists at SLAC</a></td>
				<td style="font-size: 1em;" width="33%"><a href="https://portal.slac.stanford.edu/public/maillist" style="text-decoration: underline; color: rgb(102, 51, 102);">LISTSERV FAQ</a></td>
			</tr>
			<tr style="font-size: 1em;">
				<td style="font-size: 1em;" width="33%"><a href="http://www.slac.stanford.edu/comp/net/email/slaconly/listserv-request.html" style="text-decoration: underline; color: rgb(102, 51, 102);">New List Request Form</a></td>
				<td style="font-size: 1em;" width="33%">&nbsp;</td>
			</tr>
		</tbody>
	</table>
</blockquote>
<dl>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Getting Help</dt>
</dl>
<blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
	<table border="0" id="table5" style="font-size: 1em;" width="100%">
		<tbody>
			<tr style="font-size: 1em;">
				<td style="font-size: 1em;" width="50%"><a href="mailto:ithelp@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">Ask Help Desk</a></td>
				<td style="font-size: 1em;" width="50%">&nbsp;</td>
			</tr>
		</tbody>
	</table>
</blockquote>
<dl>
	<dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Password Changing</dt>
</dl>
<blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;">
	<table border="0" id="table8" style="font-size: 1em;" width="100%">
		<tbody>
			<tr style="font-size: 1em;">
				<td style="font-size: 1em;"><a href="https://win-password.slac.stanford.edu/" style="text-decoration: underline; color: rgb(102, 51, 102);">Change Your Windows Password Here</a></td>
			</tr>
		</tbody>
	</table>
</blockquote>
<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<dl><dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Client Configurations and Forwarding</dt>
</dl><blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><table border="0" id="table6" style="font-size: 1em;" width="100%"><tbody><tr style="font-size: 1em;"><td style="font-size: 1em;" width="50%"><a href="http://www2.slac.stanford.edu/comp/messaging/Installing/default.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Install &amp; Configure Pages</a></td>
<td style="font-size: 1em;" width="50%"><a href="https://email.slac.stanford.edu/owa" style="text-decoration: underline; color: rgb(102, 51, 102);">Read E-mail via Web Now</a></td>
</tr><tr style="font-size: 1em;"><td style="font-size: 1em;" width="50%"><a href="http://www2.slac.stanford.edu/comp/messaging/Reference/exch2007-whattoexpect.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">What to Expect with Exchange 2007</a></td>
<td style="font-size: 1em;" width="50%"> </td>
</tr></tbody></table></blockquote>
<dl><dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Frequently Asked Questions</dt>
</dl><blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><table border="0" id="table7" style="font-size: 1em;" width="100%"><tbody><tr style="font-size: 1em;"><td style="font-size: 1em;" width="50%"><a href="http://www2.slac.stanford.edu/comp/messaging/faq/default.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">General FAQ</a></td>
<td style="font-size: 1em;" width="50%"><a href="http://www2.slac.stanford.edu/comp/messaging/faq/errroranswer.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Error Messages &amp; Answers</a></td>
</tr></tbody></table></blockquote>
<dl><dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Mailing Lists</dt>
</dl><blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><table border="0" id="table4" style="font-size: 1em;" width="100%"><tbody><tr style="font-size: 1em;"><td style="font-size: 1em;" width="33%"><a href="http://www2.slac.stanford.edu/comp/messaging/Reference/mailinglists.htm" style="text-decoration: underline; color: rgb(102, 51, 102);">Description of Mailing Lists at SLAC</a></td>
<td style="font-size: 1em;" width="33%"><a href="https://portal.slac.stanford.edu/public/maillist" style="text-decoration: underline; color: rgb(102, 51, 102);">LISTSERV FAQ</a></td>
</tr><tr style="font-size: 1em;"><td style="font-size: 1em;" width="33%"><a href="http://www.slac.stanford.edu/comp/net/email/slaconly/listserv-request.html" style="text-decoration: underline; color: rgb(102, 51, 102);">New List Request Form</a></td>
<td style="font-size: 1em;" width="33%"> </td>
</tr></tbody></table></blockquote>
<dl><dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Getting Help</dt>
</dl><blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><table border="0" id="table5" style="font-size: 1em;" width="100%"><tbody><tr style="font-size: 1em;"><td style="font-size: 1em;" width="50%"><a href="mailto:ithelp@slac.stanford.edu" style="text-decoration: underline; color: rgb(102, 51, 102);">Ask Help Desk</a></td>
<td style="font-size: 1em;" width="50%"> </td>
</tr></tbody></table></blockquote>
<dl><dt style="margin-bottom: 0.5em; margin-top: 0.5em; color: rgb(153, 0, 0); font-size: 1.3em; font-family: Verdana, Helvetica, Arial, sans-serif; line-height: normal;">Password Changing</dt>
</dl><blockquote style="font-family: Verdana, Helvetica, Arial, sans-serif; font-size: 12px; line-height: normal;"><table border="0" id="table8" style="font-size: 1em;" width="100%"><tbody><tr style="font-size: 1em;"><td style="font-size: 1em;"><a href="https://win-password.slac.stanford.edu/" style="text-decoration: underline; color: rgb(102, 51, 102);">Change Your Windows Password Here</a></td>
</tr></tbody></table></blockquote>
<p> </p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_slac_sc_service_overview' => array(
    'und' => array(
      0 => array(
        'value' => 'Email is offered to A-Z',
        'format' => NULL,
        'safe_value' => 'Email is offered to A-Z',
      ),
    ),
  ),
  'field_slac_sc_eligibility' => array(
    'und' => array(
      0 => array(
        'tid' => 61,
        'uuid' => 'db10ac33-21ec-4d40-bee7-1c34780f1b40',
      ),
      1 => array(
        'tid' => 63,
        'uuid' => 'f3037fca-b840-4394-9c4e-03ea14b6c4bf',
      ),
      2 => array(
        'tid' => 62,
        'uuid' => '9d88d219-f7e7-4354-b6ce-accadf586640',
      ),
      3 => array(
        'tid' => 60,
        'uuid' => '00e2fef3-0966-49ed-8f3d-e3f8d1cd46c0',
      ),
    ),
  ),
  'field_slac_sc_requirements' => array(),
  'field_slac_sc_support' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Support is provided by SLAC IT Services</p>
',
        'format' => 'full_html',
        'safe_value' => '<p>Support is provided by SLAC IT Services</p>
',
      ),
    ),
  ),
  'field_slac_sc_rate' => array(),
  'field_slac_sc_request_link' => array(),
  'field_slac_sc_category' => array(
    'und' => array(
      0 => array(
        'tid' => 49,
        'uuid' => '62a170f8-cfd3-4717-a589-c5f1f7910be7',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-26 09:58:12 -0700',
  'author_uuid' => '2f4dc695-a129-4c43-8441-07db6781150a',
);
  return $nodes;
}
