<?php
/**
 * @file
 * Code for the Profile feature.
 */

include_once 'slac_profile.features.inc';

if (module_exists('libraries') && file_exists(libraries_get_path('hideMaxListItem') . '/hideMaxListItem.js')) {
  define('HIDE_MAX_LIST_ITEM', TRUE);
}
else {
  define('HIDE_MAX_LIST_ITEM', FALSE);
}

/**
 * Implements hook_views_pre_view().
 */
function slac_profile_views_pre_view(&$view, &$display_id, &$args) {
  if ($view->name == 'profile_user_elements' && $display_id == 'panel_pane_4' && HIDE_MAX_LIST_ITEM) {
    drupal_add_js(libraries_get_path('hideMaxListItem') . '/hideMaxListItem.js');
    drupal_add_js(drupal_get_path('module', 'slac_profile') . '/js/slac_profile.js');
  }
}

/**
 * Implements hook_profile2_presave().
 */
function slac_profile_profile2_presave($profile) {
  $instance_info = field_info_instance('profile2', 'field_prf_contact_photo', 'contact');
  if (isset($instance_info['settings']['default_image'])
    && $instance_info['settings']['default_image'] == 0) {
    $instance_info['settings']['default_image'] = variable_get('profile_default_picture_id', 0);
    field_update_instance($instance_info);
  }
}

/**
 * Implements hook_menu_alter().
 */
function slac_profile_menu_alter(&$items) {
  if (isset($items['user/%user/edit'])) {
    $items['user/%user/edit']['title'] = 'Edit User Info';
  }

  if (isset($items['user/%user/view'])) {
    $items['user/%user/view']['title'] = 'View Profile';
  }

  $profile_types = array('bio', 'contact', 'social_media');
  foreach ($profile_types as $type) {
    if (isset($items['profile-' . $type . '/%profile2_by_uid/edit'])) {
      $items['profile-' . $type . '/%profile2_by_uid/edit']['title'] = 'Edit ' . ucwords(str_replace('_', ' ', $type));
    }
  }
}