<?php
/**
 * @file
 * slac_blog_test_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function slac_blog_test_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Everyday tools for design and theming',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'edbffbd4-f185-4304-a380-38d8ac621601',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1375270551,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0490d0e1-4e5a-422b-98c9-a1265f04b258',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p class="summary">I spend a lot of my time theming in the browser, writing CSS and testing ideas. In this blog post, I wanted to share some of my favorite tools for designing and theming.</p>
<h2>In-Browser Tools:</h2>
<ul><li><strong>Firebug</strong> (developer tools for in-browser testing and live editing of code): <a href="https://getfirebug.com/" rel="nofollow">https://getfirebug.com/</a> –<em> INVALUABLE!</em></li>
	<li><strong>Box Shadow</strong> (create box-shadow CSS for different browsers): <a href="http://css-tricks.com/snippets/css/css-box-shadow/" rel="nofollow">http://css-tricks.com/snippets/css/css-box-shadow/</a></li>
	<li><strong>Border Radius generator</strong> (create border-radius CSS for different browsers: <a href="http://border-radius.com/" rel="nofollow">http://border-radius.com/</a></li>
	<li><strong>CSS gradient generator</strong> (UI for creating CSS gradients): <a href="http://www.colorzilla.com/gradient-editor/" rel="nofollow">http://www.colorzilla.com/gradient-editor/</a></li>
	<li><strong>Web color picker</strong> (web-based color picker tool): <a href="http://www.colorpicker.com/" rel="nofollow">http://www.colorpicker.com/</a></li>
	<li><strong>Hex Color Tool</strong> (lighten/darken Hex Color codes by percentage to get shades of a color): <a href="http://hexcolortool.com/" rel="nofollow">http://hexcolortool.com/</a></li>
</ul><h2>Web References:</h2>
<ul><li><strong>CSS reference</strong> (the definitive reference for CSS): <a href="http://www.w3schools.com/cssref/" rel="nofollow">http://www.w3schools.com/cssref/</a></li>
	<li><strong>Bootstrap reference</strong> (for all your Bootstrap classes and markup): <a href="http://twitter.github.io/bootstrap/" rel="nofollow">http://twitter.github.io/bootstrap/</a></li>
	<li><strong>Font Awesome reference</strong> (for awesome icons): <a href="http://fortawesome.github.io/Font-Awesome/%C2%A0" rel="nofollow">http://fortawesome.github.io/Font-Awesome/</a></li>
</ul><h2>Desktop Tools:</h2>
<ul><li><strong>Little Ipsum</strong> (create lorem ipsum text): <a href="http://littleipsum.com/" rel="nofollow">http://littleipsum.com/</a></li>
	<li><strong>Frank DeLoupe</strong> (pick colors from any pixel on your desktop screen): <a href="http://www.jumpzero.com/frank/" rel="nofollow">www.jumpzero.com/frank/</a></li>
	<li><strong>Anvil for Mac</strong> (easy, one-click local dev environment): <a href="http://anvilformac.com/" rel="nofollow">http://anvilformac.com/</a></li>
	<li><strong>Balsamiq</strong> (wireframing software with built-in UI pattern libraries): <a href="http://www.balsamiq.com/" rel="nofollow">http://www.balsamiq.com/</a> (also available online)</li>
	<li><strong>Creately</strong> (great tool for creating site maps): <a href="http://creately.com/" rel="nofollow">http://creately.com/</a> (also available online)</li>
	<li><strong>Sublime Text</strong> (beautiful code editor): <a href="http://www.sublimetext.com/" rel="nofollow">http://www.sublimetext.com/</a></li>
	<li><strong>Adobe Photoshop, Illustrator</strong>, etc. (duh): <a href="http://www.adobe.com" rel="nofollow">http://www.adobe.com</a></li>
</ul><p>Do you have any favorite tools for designing and theming? I\'d love to hear from you in the comments.</p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p class="summary">I spend a lot of my time theming in the browser, writing CSS and testing ideas. In this blog post, I wanted to share some of my favorite tools for designing and theming.</p>
<h2>In-Browser Tools:</h2>
<ul><li><strong>Firebug</strong> (developer tools for in-browser testing and live editing of code): <a href="https://getfirebug.com/" rel="nofollow">https://getfirebug.com/</a> –<em> INVALUABLE!</em></li>
<li><strong>Box Shadow</strong> (create box-shadow CSS for different browsers): <a href="http://css-tricks.com/snippets/css/css-box-shadow/" rel="nofollow">http://css-tricks.com/snippets/css/css-box-shadow/</a></li>
<li><strong>Border Radius generator</strong> (create border-radius CSS for different browsers: <a href="http://border-radius.com/" rel="nofollow">http://border-radius.com/</a></li>
<li><strong>CSS gradient generator</strong> (UI for creating CSS gradients): <a href="http://www.colorzilla.com/gradient-editor/" rel="nofollow">http://www.colorzilla.com/gradient-editor/</a></li>
<li><strong>Web color picker</strong> (web-based color picker tool): <a href="http://www.colorpicker.com/" rel="nofollow">http://www.colorpicker.com/</a></li>
<li><strong>Hex Color Tool</strong> (lighten/darken Hex Color codes by percentage to get shades of a color): <a href="http://hexcolortool.com/" rel="nofollow">http://hexcolortool.com/</a></li>
</ul><h2>Web References:</h2>
<ul><li><strong>CSS reference</strong> (the definitive reference for CSS): <a href="http://www.w3schools.com/cssref/" rel="nofollow">http://www.w3schools.com/cssref/</a></li>
<li><strong>Bootstrap reference</strong> (for all your Bootstrap classes and markup): <a href="http://twitter.github.io/bootstrap/" rel="nofollow">http://twitter.github.io/bootstrap/</a></li>
<li><strong>Font Awesome reference</strong> (for awesome icons): <a href="http://fortawesome.github.io/Font-Awesome/%C2%A0" rel="nofollow">http://fortawesome.github.io/Font-Awesome/</a></li>
</ul><h2>Desktop Tools:</h2>
<ul><li><strong>Little Ipsum</strong> (create lorem ipsum text): <a href="http://littleipsum.com/" rel="nofollow">http://littleipsum.com/</a></li>
<li><strong>Frank DeLoupe</strong> (pick colors from any pixel on your desktop screen): <a href="http://www.jumpzero.com/frank/" rel="nofollow">www.jumpzero.com/frank/</a></li>
<li><strong>Anvil for Mac</strong> (easy, one-click local dev environment): <a href="http://anvilformac.com/" rel="nofollow">http://anvilformac.com/</a></li>
<li><strong>Balsamiq</strong> (wireframing software with built-in UI pattern libraries): <a href="http://www.balsamiq.com/" rel="nofollow">http://www.balsamiq.com/</a> (also available online)</li>
<li><strong>Creately</strong> (great tool for creating site maps): <a href="http://creately.com/" rel="nofollow">http://creately.com/</a> (also available online)</li>
<li><strong>Sublime Text</strong> (beautiful code editor): <a href="http://www.sublimetext.com/" rel="nofollow">http://www.sublimetext.com/</a></li>
<li><strong>Adobe Photoshop, Illustrator</strong>, etc. (duh): <a href="http://www.adobe.com" rel="nofollow">http://www.adobe.com</a></li>
</ul><p>Do you have any favorite tools for designing and theming? I\'d love to hear from you in the comments.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 21,
      ),
    ),
  ),
  'field_categories' => array(
    'und' => array(
      0 => array(
        'tid' => 13,
      ),
    ),
  ),
  'field_image' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-07-31 14:35:51 +0300',
  'author_uuid' => 'f0dd442b-e708-4678-8cec-90cec6dee377',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Stanford Sites Updates, July 11 and 13, 2013',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '8d407726-d5b5-4652-ab1d-2c9f9513fb61',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1375270551,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0f11674f-9eec-4fc8-b643-53cab7884fcd',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<div><span>IT Services will perform database updates for the <a href="https://sites.stanford.edu">Stanford Sites Drupal hosting service</a>, including department and group websites hosted on sites.stanford.edu and individuals\' websites hosted on people.stanford.edu, on the following dates:</span></div>
<div>&nbsp;</div>
<ul><li>Thursday, July 11, from 4 a.m. - 6 a.m.</li>
	<li>Saturday, July 13, from 5 a.m. - 8 a.m.</li>
</ul><div>Changes include&nbsp;updating the database engine from&nbsp;MyISAM to InnoDB and will be made in a rolling upgrade process; this allows the Stanford Sites system to continue providing service throughout the update window. We expect that each website will have approximately 30-60 seconds of downtime as it is updated.</div>
<div>&nbsp;</div>
<div>If you experience issues with your Stanford Site, please <a href="https://helpsu.stanford.edu/?pcat=sites">submit a HelpSU request</a>, and the Stanford Web Services team will respond as soon as possible.</div>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<div><span>IT Services will perform database updates for the <a href="https://sites.stanford.edu">Stanford Sites Drupal hosting service</a>, including department and group websites hosted on sites.stanford.edu and individuals\' websites hosted on people.stanford.edu, on the following dates:</span></div>
<div> </div>
<ul><li>Thursday, July 11, from 4 a.m. - 6 a.m.</li>
<li>Saturday, July 13, from 5 a.m. - 8 a.m.</li>
</ul><div>Changes include updating the database engine from MyISAM to InnoDB and will be made in a rolling upgrade process; this allows the Stanford Sites system to continue providing service throughout the update window. We expect that each website will have approximately 30-60 seconds of downtime as it is updated.</div>
<div> </div>
<div>If you experience issues with your Stanford Site, please <a href="https://helpsu.stanford.edu/?pcat=sites">submit a HelpSU request</a>, and the Stanford Web Services team will respond as soon as possible.</div>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 5,
      ),
    ),
  ),
  'field_categories' => array(
    'und' => array(
      0 => array(
        'tid' => 12,
      ),
    ),
  ),
  'field_image' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-07-31 14:35:51 +0300',
  'author_uuid' => 'f0dd442b-e708-4678-8cec-90cec6dee377',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'OpenWeb Conference 2013',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '095706af-35c3-4a6e-bd83-82bb50a379e6',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1375270551,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2dfbdcf1-e6bf-4400-950d-897675abce2f',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p class="summary">Over a weekend in mid-July several members of Stanford IT Services turned up at the OpenWeb conference held at the Paypal Town Hall in San Jose. This conference, the brain child of <a href="http://john.foliot.ca/" rel="nofollow">John Foliot</a>, &nbsp;had its roots at Stanford. &nbsp;Although a variety of sessions were available, this conference seemed to concentrate on accessibility.</p>
<h2>Why accessibility?</h2>
<p>What I found amazing and wonderful was the number of white canes at this conference. This conference welcomed an amazing number of blind and otherwise disabled people, a group of people whose needs we must consider when developing our web sites and applications.</p>
<p>In his presentation, Ted Drake from Intuit Accessibility, says that for an app or website to be accessible, it must be perceivable, operable, and understandable. That is, a screen reader can read the text; there\'s no text in the images; you can swipe, tab, and use the buttons even when the screen reader is enabled; and the order in which you navigate the page makes sense.</p>
<p>Have you tried navigating your website or app with just a screen reader? Could you do it? My guess is that unless you built your site with accessibility in mind, it\'ll be challenging or even impossible to navigate with a screen reader.</p>
<p>As I consider this man who sat next to me with his white cane folded up under his arm, navigating his iPhone by listening to the screen reader through his headphones, I realize that for me, the big take-away from this conference was that accessibility must become one of our priorities as we develop for the web.</p>',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Over a weekend in mid-July several members of Stanford IT Services turned up at the OpenWeb conference held at the Paypal Town Hall in San Jose. This conference, the brain child of <a href="http://john.foliot.ca/" rel="nofollow">John Foliot</a>,  had its roots at Stanford.  Although a variety of sessions were available, this conference seemed to concentrate on accessibility.<br />
Why accessibility?<br />
What I found amazing and wonderful was the number of white canes at this conference. This conference welcomed an amazing number of blind and otherwise disabled people, a group of people whose needs we must consider when developing our web sites and applications.<br />
In his presentation, Ted Drake from Intuit Accessibility, says that for an app or website to be accessible, it must be perceivable, operable, and understandable. That is, a screen reader can read the text; there\'s no text in the images; you can swipe, tab, and use the buttons even when the screen reader is enabled; and the order in which you navigate the page makes sense.<br />
Have you tried navigating your website or app with just a screen reader? Could you do it? My guess is that unless you built your site with accessibility in mind, it\'ll be challenging or even impossible to navigate with a screen reader.<br />
As I consider this man who sat next to me with his white cane folded up under his arm, navigating his iPhone by listening to the screen reader through his headphones, I realize that for me, the big take-away from this conference was that accessibility must become one of our priorities as we develop for the web.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 19,
      ),
    ),
  ),
  'field_categories' => array(
    'und' => array(
      0 => array(
        'tid' => 3,
      ),
    ),
  ),
  'field_image' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-07-31 14:35:51 +0300',
  'author_uuid' => 'f0dd442b-e708-4678-8cec-90cec6dee377',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Why Not Panels?',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '54844480-9a7c-41e2-8c92-f40e2a795302',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1375270551,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '302d7999-64f7-41a1-9747-3f50e13065df',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<blockquote class="pullquote">"The Panels module allows a site administrator to create customized layouts for multiple uses. At its core it is a drag and drop content manager that lets you visually design a layout and place content within that layout. Integration with other systems allows you to create nodes that use this, landing pages that use this, and even override system pages such as taxonomy and the node page so that you can customize the layout of your site with very fine grained permissions."</blockquote>
<p>(from the <a href="https://drupal.org/project/panels" rel="nofollow">drupal.org project page for Panels</a>).</p>
<p>Panels is a very robust and powerful module that has deep integration with modules such as <a href="https://drupal.org/project/views" rel="nofollow">Views</a>, <a href="https://drupal.org/project/features" rel="nofollow">Features</a>, <a href="https://drupal.org/project/ctools" rel="nofollow">Chaos Tools</a>, and <a href="https://drupal.org/documentation/modules/taxonomy" rel="nofollow">Taxonomy</a>. It has a sophisticated caching mechanism, a powerful in-place editor (IPE), and a rich ecosystem of add-on modules. There even is an <a href="https://drupal.org/project/panopoly" rel="nofollow">entire distribution built on Panels</a>.</p>
<p><a href="https://swsblog.stanford.edu/sites/default/files/images/blog/panels3-choose-layout.png"><img alt="Screenshot of the Panels module\'s user interface for choosing different page layouts" src="https://swsblog.stanford.edu/sites/default/files/styles/large/public/images/blog/panels3-choose-layout.png" title="click to embiggen"></a></p>
<p class="clear-both">(Screenshot taken from <a href="http://www.angrydonuts.com/" rel="nofollow">Earl Miles\'s blog</a>.)</p>
<h2>Planning for Drupal 7 on Stanford Sites</h2>
<p>Stanford Sites launched in Fall, 2011, with Drupal 6 as the only offering. In June, 2012, IT Services staff did a survey of the various page layout approaches available in Drupal 7. We included Panels in this survey, as well as a competing approach, that of <a href="https://drupal.org/project/context" rel="nofollow">Context</a> and <a href="https://drupal.org/project/ds" rel="nofollow">Display Suite</a>. We also reviewed several other modules that attempted to address layout in various ways, including <a href="https://drupal.org/project/bean" rel="nofollow">BEAN</a>, <a href="https://drupal.org/project/boxes" rel="nofollow">Boxes</a>, <a href="https://drupal.org/project/delta" rel="nofollow">Delta</a>, and <a href="https://drupal.org/project/og" rel="nofollow">Organic Groups</a>.</p>
<h3>Pain Points in Drupal 6</h3>
<p>We began by listing our "pain points" in Drupal 6:</p>
<ul><li>Blocks are "dumb" - they have no knowledge of what content is at a given path</li>
	<li>Revisioning: blocks do not track revisions</li>
	<li>Blocks don\'t have instances (i.e., cannot be placed multiple times)</li>
	<li>Cannot assign id or class to blocks (only to divs within blocks)</li>
	<li>Writing PHP, HTML, CSS – many users do not want to do this, and should not have to</li>
</ul><h3>Themes and Regions</h3>
<p>Stanford Web Services (SWS) uses the <a href="https://openframework.stanford.edu">Open Framework</a> theme (and subthemes) extensively. Our responsive web design approach is based on placing blocks in regions within that theme, and dictating how many columns blocks will span. Since blocks and regions are native to Drupal and a relatively simple concept for people new to Drupal to learn, our themes take advantage of a user\'s familiarity with blocks and regions to enable quickly building responsive sites.</p>
<p><a href="https://swsblog.stanford.edu/sites/default/files/images/blog/ResponsiveFlow.png"><img alt="Diagram of the responsive flow of blocks and regions in the Open Framework theme" src="https://swsblog.stanford.edu/sites/default/files/styles/large/public/images/blog/ResponsiveFlow.png" title="click to embiggen"></a></p>
<h3 class="clear-both">Context and Display Suite</h3>
<p>The Context/Display Suite approach builds on our core responsive theme strategy of using blocks and regions, and offers solutions to the majority of our pain points without introducing unnecessary complexity:</p>
<ul><li>Context solves the "blocks are dumb" and the "multiple instances" issues by allowing you to create "layout" configurations (for use site-wide or for specific pages/paths) in which blocks can be reused and placed in different regions in each layout</li>
	<li>Display Suite also allows creation of custom layouts and view modes, and provides the ability to create blocks out of node fields (thus enhancing our blocks/regions strategy)</li>
	<li>The Block Class module is a lightweight way to solve adding classes to blocks and allows us to take advantage of Open Framework\'s responsive grid system (e.g. "span6" gets you a block of 50% width)</li>
	<li>Context and Display Suite have Features integration, which allows us to export layout and configuration (and track in a VCS)</li>
</ul><h3>Panels</h3>
<p>The Panels/Panopoly approach is compelling, and offers a rich set of end-user tools. However, several factors contribute to our decision not to include it in Stanford Sites at this point:</p>
<ul><li>There is a significant learning curve to Panels. With robustness and flexibility come complexity, and this presented an obstacle to launching the Drupal 7 environment quickly, and an impediment to self-service users of Stanford Sites.</li>
	<li>It is an "all-or-nothing" option, in that Panels completely takes over the display of the page</li>
	<li>Although improvements have been made to the administrative UI since previous versions of Panels (particularly the Panels in-place editor [IPE]), it is still a very complex interface</li>
	<li>The responsive benefits of Panels are offset by SWS\'s heavy use of our base theme, Open Framework and its <a href="https://openframework.stanford.edu/regions">responsive block regions</a></li>
</ul><p>In summary, we have taken a core "blocks and regions" approach to layout, and found solutions in a combination of modules: Context, Display Suite, and Block Class. This allows for flexibility and simple layout implementation without the learning curve or overhead of Panels.</p>
<h2>Additional Resources</h2>
<ul><li><a href="https://swsblog.stanford.edu/blog/using-display-suite-place-node-fields-blocks">Using Display Suite to place node fields in blocks</a></li>
	<li><a href="https://swsblog.stanford.edu/blog/styling-sites-introduction-open-framework">Introduction to Open Framework</a></li>
	<li><a href="https://swsblog.stanford.edu/blog/using-context-add-block-region">Using Context to add a block to a region</a></li>
</ul>',
        'summary' => 'One of the common requests that we receive about the <a href="https://itservices.stanford.edu/service/web/stanfordsites/modules">list of included modules in Stanford Sites</a> is if we can add the <a href="https://drupal.org/project/panels" rel="nofollow">Panels</a> module. I would like to outline our rationale for not including Panels in Stanford Sites, and describe the alternative approaches and methods you can use to create unique, custom layouts on your website.',
        'format' => 'filtered_html',
        'safe_value' => '<blockquote class="pullquote"><p>"The Panels module allows a site administrator to create customized layouts for multiple uses. At its core it is a drag and drop content manager that lets you visually design a layout and place content within that layout. Integration with other systems allows you to create nodes that use this, landing pages that use this, and even override system pages such as taxonomy and the node page so that you can customize the layout of your site with very fine grained permissions."</p></blockquote>
<p>(from the <a href="https://drupal.org/project/panels" rel="nofollow">drupal.org project page for Panels</a>).<br />
Panels is a very robust and powerful module that has deep integration with modules such as <a href="https://drupal.org/project/views" rel="nofollow">Views</a>, <a href="https://drupal.org/project/features" rel="nofollow">Features</a>, <a href="https://drupal.org/project/ctools" rel="nofollow">Chaos Tools</a>, and <a href="https://drupal.org/documentation/modules/taxonomy" rel="nofollow">Taxonomy</a>. It has a sophisticated caching mechanism, a powerful in-place editor (IPE), and a rich ecosystem of add-on modules. There even is an <a href="https://drupal.org/project/panopoly" rel="nofollow">entire distribution built on Panels</a>.<br /><a href="https://swsblog.stanford.edu/sites/default/files/images/blog/panels3-choose-layout.png"></a><br />
(Screenshot taken from <a href="http://www.angrydonuts.com/" rel="nofollow">Earl Miles\'s blog</a>.)<br />
Planning for Drupal 7 on Stanford Sites<br />
Stanford Sites launched in Fall, 2011, with Drupal 6 as the only offering. In June, 2012, IT Services staff did a survey of the various page layout approaches available in Drupal 7. We included Panels in this survey, as well as a competing approach, that of <a href="https://drupal.org/project/context" rel="nofollow">Context</a> and <a href="https://drupal.org/project/ds" rel="nofollow">Display Suite</a>. We also reviewed several other modules that attempted to address layout in various ways, including <a href="https://drupal.org/project/bean" rel="nofollow">BEAN</a>, <a href="https://drupal.org/project/boxes" rel="nofollow">Boxes</a>, <a href="https://drupal.org/project/delta" rel="nofollow">Delta</a>, and <a href="https://drupal.org/project/og" rel="nofollow">Organic Groups</a>.<br />
Pain Points in Drupal 6<br />
We began by listing our "pain points" in Drupal 6:</p>
<ul><li>Blocks are "dumb" - they have no knowledge of what content is at a given path</li>
<li>Revisioning: blocks do not track revisions</li>
<li>Blocks don\'t have instances (i.e., cannot be placed multiple times)</li>
<li>Cannot assign id or class to blocks (only to divs within blocks)</li>
<li>Writing PHP, HTML, CSS – many users do not want to do this, and should not have to</li>
</ul><p>Themes and Regions<br />
Stanford Web Services (SWS) uses the <a href="https://openframework.stanford.edu">Open Framework</a> theme (and subthemes) extensively. Our responsive web design approach is based on placing blocks in regions within that theme, and dictating how many columns blocks will span. Since blocks and regions are native to Drupal and a relatively simple concept for people new to Drupal to learn, our themes take advantage of a user\'s familiarity with blocks and regions to enable quickly building responsive sites.<br /><a href="https://swsblog.stanford.edu/sites/default/files/images/blog/ResponsiveFlow.png"></a><br />
Context and Display Suite<br />
The Context/Display Suite approach builds on our core responsive theme strategy of using blocks and regions, and offers solutions to the majority of our pain points without introducing unnecessary complexity:</p>
<ul><li>Context solves the "blocks are dumb" and the "multiple instances" issues by allowing you to create "layout" configurations (for use site-wide or for specific pages/paths) in which blocks can be reused and placed in different regions in each layout</li>
<li>Display Suite also allows creation of custom layouts and view modes, and provides the ability to create blocks out of node fields (thus enhancing our blocks/regions strategy)</li>
<li>The Block Class module is a lightweight way to solve adding classes to blocks and allows us to take advantage of Open Framework\'s responsive grid system (e.g. "span6" gets you a block of 50% width)</li>
<li>Context and Display Suite have Features integration, which allows us to export layout and configuration (and track in a VCS)</li>
</ul><p>Panels<br />
The Panels/Panopoly approach is compelling, and offers a rich set of end-user tools. However, several factors contribute to our decision not to include it in Stanford Sites at this point:</p>
<ul><li>There is a significant learning curve to Panels. With robustness and flexibility come complexity, and this presented an obstacle to launching the Drupal 7 environment quickly, and an impediment to self-service users of Stanford Sites.</li>
<li>It is an "all-or-nothing" option, in that Panels completely takes over the display of the page</li>
<li>Although improvements have been made to the administrative UI since previous versions of Panels (particularly the Panels in-place editor [IPE]), it is still a very complex interface</li>
<li>The responsive benefits of Panels are offset by SWS\'s heavy use of our base theme, Open Framework and its <a href="https://openframework.stanford.edu/regions">responsive block regions</a></li>
</ul><p>In summary, we have taken a core "blocks and regions" approach to layout, and found solutions in a combination of modules: Context, Display Suite, and Block Class. This allows for flexibility and simple layout implementation without the learning curve or overhead of Panels.<br />
Additional Resources</p>
<ul><li><a href="https://swsblog.stanford.edu/blog/using-display-suite-place-node-fields-blocks">Using Display Suite to place node fields in blocks</a></li>
<li><a href="https://swsblog.stanford.edu/blog/styling-sites-introduction-open-framework">Introduction to Open Framework</a></li>
<li><a href="https://swsblog.stanford.edu/blog/using-context-add-block-region">Using Context to add a block to a region</a></li>
</ul>',
        'safe_summary' => '<p>One of the common requests that we receive about the <a href="https://itservices.stanford.edu/service/web/stanfordsites/modules">list of included modules in Stanford Sites</a> is if we can add the <a href="https://drupal.org/project/panels" rel="nofollow">Panels</a> module. I would like to outline our rationale for not including Panels in Stanford Sites, and describe the alternative approaches and methods you can use to create unique, custom layouts on your website.</p>
',
      ),
    ),
  ),
  'field_blog_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 16,
      ),
    ),
  ),
  'field_categories' => array(
    'und' => array(
      0 => array(
        'tid' => 9,
      ),
    ),
  ),
  'field_image' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-07-31 14:35:51 +0300',
  'author_uuid' => 'f0dd442b-e708-4678-8cec-90cec6dee377',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Menu Tricks #3: Automating Virtual Menu Position for Specific Content Types',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '7ef8c3e3-c750-44f5-880a-e0d6b14aa225',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1375270551,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '65b81bc4-0238-46f9-a26d-2f6520e48a0b',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>As a serious navigation advocate, it drives me crazy to have an active "Blog" or "Calendar" link in my main menu when I\'m looking at the overview pages for that section, but then the active link goes away when I look at a specific Event or Blog Post. Am I in the Calendar section or not?</p>
<p>Enter one of my favorite Drupal modules: <a href="https://drupal.org/project/menu_position" rel="nofollow">Menu Position</a>.</p>
<h2>The Menu Position Module</h2>
<p><a href="https://drupal.org/project/menu_position" rel="nofollow">Menu Position</a> allows you to make it appear that a piece of content is in a certain place in the menu without having to actually place it there, based on conditions you can set. Meaning, I can tell Drupal to "pretend" that every blog post is in the main menu under Blog and if I\'m looking at a Blog Post, the main Blog link will be active. Win!</p>
<p>Say I didn\'t have this module, but really wanted "Blog" in my main menu to be active when someone is reading a Blog Post node. My only real option is to add every blog post to the menu, but that\'s a lot of work and would create a mess in my menu! Not worth the hassle, even if you have the same pet peeves as me.</p>
<h2>Configuring Menu Position</h2>
<p>Configuring Menu Position is pretty straight forward once you\'ve enabled the module. Here\'s an example wherein I will place all Articles under "What\'s New."</p>
<ol><li>Go to /admin/structure/menu-position/add</li>
	<li>Title your Menu Position. Mine is called "Place Articles Under What\'s New" (see screenshot)</li>
	<li>Choose the Parent menu Item. In my example "What\'s New" (see screenshot)</li>
	<li>In Conditions, select the Content Type you want to make a Menu Position rule for. Mine is "Article"</li>
	<li>And Save</li>
</ol><p>You can also make menu position rules based on path, user role, or taxonomy.</p>
<p><img alt="Screenshot of Menu Position Configuration" src="https://swsblog.stanford.edu/sites/default/files/styles/large/public/images/blog/Screen%20Shot%202013-06-13%20at%204.52.53%20PM.png" title=""></p>
<h2>Menu Position and Stanford Sites</h2>
<p>Menu Position is on the short list of modules to be added to the Stanford Sites platform. Coming soon!</p>
<p><em>Do you have any menu pet peeves like me? What do you think makes for great navigation?</em></p>',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>As a serious navigation advocate, it drives me crazy to have an active "Blog" or "Calendar" link in my main menu when I\'m looking at the overview pages for that section, but then the active link goes away when I look at a specific Event or Blog Post. Am I in the Calendar section or not?<br />
Enter one of my favorite Drupal modules: <a href="https://drupal.org/project/menu_position" rel="nofollow">Menu Position</a>.<br />
The Menu Position Module<br /><a href="https://drupal.org/project/menu_position" rel="nofollow">Menu Position</a> allows you to make it appear that a piece of content is in a certain place in the menu without having to actually place it there, based on conditions you can set. Meaning, I can tell Drupal to "pretend" that every blog post is in the main menu under Blog and if I\'m looking at a Blog Post, the main Blog link will be active. Win!<br />
Say I didn\'t have this module, but really wanted "Blog" in my main menu to be active when someone is reading a Blog Post node. My only real option is to add every blog post to the menu, but that\'s a lot of work and would create a mess in my menu! Not worth the hassle, even if you have the same pet peeves as me.<br />
Configuring Menu Position<br />
Configuring Menu Position is pretty straight forward once you\'ve enabled the module. Here\'s an example wherein I will place all Articles under "What\'s New."</p>
<ol><li>Go to /admin/structure/menu-position/add</li>
<li>Title your Menu Position. Mine is called "Place Articles Under What\'s New" (see screenshot)</li>
<li>Choose the Parent menu Item. In my example "What\'s New" (see screenshot)</li>
<li>In Conditions, select the Content Type you want to make a Menu Position rule for. Mine is "Article"</li>
<li>And Save</li>
</ol><p>You can also make menu position rules based on path, user role, or taxonomy.</p>
<p>Menu Position and Stanford Sites<br />
Menu Position is on the short list of modules to be added to the Stanford Sites platform. Coming soon!<br /><em>Do you have any menu pet peeves like me? What do you think makes for great navigation?</em></p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 21,
      ),
    ),
  ),
  'field_categories' => array(
    'und' => array(
      0 => array(
        'tid' => 13,
      ),
    ),
  ),
  'field_image' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-07-31 14:35:51 +0300',
  'author_uuid' => 'f0dd442b-e708-4678-8cec-90cec6dee377',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Writing for the Web #1: Calls to Action',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'aef4e039-6a42-46b9-b42f-9c170b47efad',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1375270551,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '802b7270-705b-4241-b860-57a644ffed45',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p class="summary">Get people more engaged in your content! With this post, I\'ll outline two basic guidelines for writing good Calls to Action to lead users through your site.</p>
<h2>What is a Call to Action?</h2>
<p>A Call to Action is a snippet of text with a link, sometimes styled as a button or with an arrow after it.&nbsp;Use&nbsp;Calls to Action when you want to get your readers to do something — whether it\'s&nbsp;to click through to another page, download a document, or even purchase something.&nbsp;<span>A few basic academic examples might be:&nbsp;</span></p>
<ul><li>"Learn more about our programs"</li>
	<li>"View the full calendar"</li>
	<li>"Peruse our list of publications"</li>
	<li>"Get adivising in writing"</li>
	<li>"Read about Professor Smith\'s award</li>
</ul><p>In SWS, we create places for links on slideshows or at the bottoms of blocks, so that it will be easy for people to add Calls to Action where they might be needed. But how do you decide what those links should say?</p>
<h2>Writing a strong Call to Action</h2>
<h3>Start with a verb</h3>
<p>The most important part of a Call to Action is the leading verb. People are far less likely to click on a link that is a noun, they want to be led through your site. Rather than "About Us," try "Read about our team."</p>
<p>Now that you\'re starting off on the right foot, remember to elaborate a little.</p>
<h3>Give a little detail</h3>
<p>One of the common mistakes in writing Calls to Action is making them too short. "Read more" or just "More" is less compelling to readers, and also causes accessibility and Search Engine Optimization problems.</p>
<p>Blind or visually impaired readers aren\'t as able to scan the page visually and know the context of links and, in the same way, the bots (website scanners) that companies like Google use will not be able to form as complete data from links with non-specific text like "More." For those reasons, it\'s important to say Read More about what.</p>
<h2>Examples of Calls to Action</h2>
<table><thead><tr><th>Weaker</th>
			<th>Stronger</th>
		</tr></thead><tbody><tr><td>Our Mission</td>
			<td>Read more about our mission</td>
		</tr><tr><td>Orientation Volunteer Application</td>
			<td>Apply to be an Orientation Volunteer</td>
		</tr><tr><td>Overseas Students meet the president</td>
			<td>
				<p>Learn how Overseas students responded to meeting the president</p>
			</td>
		</tr><tr><td>More</td>
			<td>See More Events</td>
		</tr><tr><td>Read More</td>
			<td><span>Read more about the author</span></td>
		</tr><tr><td>Apply Now</td>
			<td><span>Download PhD Application</span></td>
		</tr><tr><td>Full list of our programs</td>
			<td>Find the program that is right for you (great Call to Action from <a href="http://bosp.stanford.edu">bosp.stanford.edu</a>)</td>
		</tr><tr><td>Student Project Gallery</td>
			<td><span>Check out our Student Project Gallery (great Call to Action from <a href="http://undergrad.stanford.edu">undergrad.stanford.edu</a>)</span></td>
		</tr></tbody></table><p>The <a href="http://adminguide.stanford.edu">recently launched Administrative Guide</a> has a great example on their homepage slideshow, with the following Call to Action text:&nbsp;<span>"Stay informed on financial policies and procedures"</span></p>
<p><img alt="Example of Call to Action from the Stanford Administrative Guide" src="https://swsblog.stanford.edu/sites/default/files/images/blog/Screen%20Shot%202013-07-15%20at%202.22.34%20PM.png" title="" height="340" width="572"></p>
<h2 class="clear-both">Interested in reading more?</h2>
<p>Here is another post that I found helpful, if you want to know even more about specific word choices and their ramifications.</p>
<ul><li><a href="http://contentverve.com/10-call-to-action-case-studies-examples-from-button-tests/" rel="nofollow">http://contentverve.com/10-call-to-action-case-studies-examples-from-but...</a></li>
</ul><p>And remember, these are guidelines, not rules. Sometimes you\'ll encounter constraints, like the size of the area provided, that will also play a part in the text you choose. A small button probably will be better served by "More Events" than "See More Undergrad Events." So, always use your best judgement.</p>',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>Get people more engaged in your content! With this post, I\'ll outline two basic guidelines for writing good Calls to Action to lead users through your site.<br />
What is a Call to Action?<br />
A Call to Action is a snippet of text with a link, sometimes styled as a button or with an arrow after it. Use Calls to Action when you want to get your readers to do something — whether it\'s to click through to another page, download a document, or even purchase something. A few basic academic examples might be: </p>
<ul><li>"Learn more about our programs"</li>
<li>"View the full calendar"</li>
<li>"Peruse our list of publications"</li>
<li>"Get adivising in writing"</li>
<li>"Read about Professor Smith\'s award</li>
</ul><p>In SWS, we create places for links on slideshows or at the bottoms of blocks, so that it will be easy for people to add Calls to Action where they might be needed. But how do you decide what those links should say?<br />
Writing a strong Call to Action<br />
Start with a verb<br />
The most important part of a Call to Action is the leading verb. People are far less likely to click on a link that is a noun, they want to be led through your site. Rather than "About Us," try "Read about our team."<br />
Now that you\'re starting off on the right foot, remember to elaborate a little.<br />
Give a little detail<br />
One of the common mistakes in writing Calls to Action is making them too short. "Read more" or just "More" is less compelling to readers, and also causes accessibility and Search Engine Optimization problems.<br />
Blind or visually impaired readers aren\'t as able to scan the page visually and know the context of links and, in the same way, the bots (website scanners) that companies like Google use will not be able to form as complete data from links with non-specific text like "More." For those reasons, it\'s important to say Read More about what.<br />
Examples of Calls to Action<br />
Weaker<br />
			Stronger<br />
		Our Mission<br />
			Read more about our mission<br />
		Orientation Volunteer Application<br />
			Apply to be an Orientation Volunteer<br />
		Overseas Students meet the president</p>
<p>				Learn how Overseas students responded to meeting the president</p>
<p>		More<br />
			See More Events<br />
		Read More<br />
			Read more about the author<br />
		Apply Now<br />
			Download PhD Application<br />
		Full list of our programs<br />
			Find the program that is right for you (great Call to Action from <a href="http://bosp.stanford.edu">bosp.stanford.edu</a>)<br />
		Student Project Gallery<br />
			Check out our Student Project Gallery (great Call to Action from <a href="http://undergrad.stanford.edu">undergrad.stanford.edu</a>)<br />
		The <a href="http://adminguide.stanford.edu">recently launched Administrative Guide</a> has a great example on their homepage slideshow, with the following Call to Action text: "Stay informed on financial policies and procedures"</p>
<p>Interested in reading more?<br />
Here is another post that I found helpful, if you want to know even more about specific word choices and their ramifications.</p>
<ul><li><a href="http://contentverve.com/10-call-to-action-case-studies-examples-from-button-tests/" rel="nofollow">http://contentverve.com/10-call-to-action-case-studies-examples-from-but...</a></li>
</ul><p>And remember, these are guidelines, not rules. Sometimes you\'ll encounter constraints, like the size of the area provided, that will also play a part in the text you choose. A small button probably will be better served by "More Events" than "See More Undergrad Events." So, always use your best judgement.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 15,
      ),
    ),
  ),
  'field_categories' => array(
    'und' => array(
      0 => array(
        'tid' => 13,
      ),
    ),
  ),
  'field_image' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-07-31 14:35:51 +0300',
  'author_uuid' => 'f0dd442b-e708-4678-8cec-90cec6dee377',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'New Drupal training announced',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'b9e32e93-7281-406c-9970-208d6471d892',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1375270551,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'ae474040-2ca7-47b8-b3af-a3c687710c2d',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p class="summary">IT Services just announced new training opportunities to learn Google Sites, Dreamweaver, and of course, <strong>Drupal and the <a href="https://sites.stanford.edu">Stanford Sites</a> environment</strong>! There are courses for everyone, from beginners just starting to explore web design, all the way up through experienced developers looking to level up their skills in web application development.</p>
<p><strong>Starting in July, the new courses include:</strong></p>
<ul><li>Drupal: Taxonomy, Blocks, and Views</li>
	<li>Google Sites (in-person workshop or an on-demand webinar)</li>
	<li>Google Sites - Advanced</li>
	<li>Dreamweaver: Level 1</li>
	<li>Javascript</li>
	<li>jQuery for Web Application Development</li>
	<li>MySQL/PHP/SQL: Developing Web Applications Workshop</li>
	<li>Python Workshop: Introduction and Beyond</li>
	<li>and more...</li>
</ul><p>Also, coming up in August is the <strong>fifth annual Techie Festival</strong>. For just $125 per course, learn from the experts on a wide range of topics, including several aimed at web professionals at every level. We have experts ready to teach on HTML5, Drupal, web design fundamentals, Stanford-specific styles, preparing web content for Drupal, and social media. <a href="https://itservices.stanford.edu/service/techtraining/techiefestival">Visit the Techie Festival website</a> to see a full schedule.</p>
<h3>How to sign up</h3>
<p><a href="https://itsupcoming.stanford.edu">Visit the IT Services Technology Training current courses schedule</a> to learn more and sign up for regular courses and the special Techie Festival sessions. Use those STAP funds before they expire!</p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p class="summary">IT Services just announced new training opportunities to learn Google Sites, Dreamweaver, and of course, <strong>Drupal and the <a href="https://sites.stanford.edu">Stanford Sites</a> environment</strong>! There are courses for everyone, from beginners just starting to explore web design, all the way up through experienced developers looking to level up their skills in web application development.</p>
<p><strong>Starting in July, the new courses include:</strong></p>
<ul><li>Drupal: Taxonomy, Blocks, and Views</li>
<li>Google Sites (in-person workshop or an on-demand webinar)</li>
<li>Google Sites - Advanced</li>
<li>Dreamweaver: Level 1</li>
<li>Javascript</li>
<li>jQuery for Web Application Development</li>
<li>MySQL/PHP/SQL: Developing Web Applications Workshop</li>
<li>Python Workshop: Introduction and Beyond</li>
<li>and more...</li>
</ul><p>Also, coming up in August is the <strong>fifth annual Techie Festival</strong>. For just $125 per course, learn from the experts on a wide range of topics, including several aimed at web professionals at every level. We have experts ready to teach on HTML5, Drupal, web design fundamentals, Stanford-specific styles, preparing web content for Drupal, and social media. <a href="https://itservices.stanford.edu/service/techtraining/techiefestival">Visit the Techie Festival website</a> to see a full schedule.</p>
<h3>How to sign up</h3>
<p><a href="https://itsupcoming.stanford.edu">Visit the IT Services Technology Training current courses schedule</a> to learn more and sign up for regular courses and the special Techie Festival sessions. Use those STAP funds before they expire!</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 6,
      ),
      1 => array(
        'tid' => 4,
      ),
    ),
  ),
  'field_categories' => array(
    'und' => array(
      0 => array(
        'tid' => 9,
      ),
    ),
  ),
  'field_image' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-07-31 14:35:51 +0300',
  'author_uuid' => 'f0dd442b-e708-4678-8cec-90cec6dee377',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Using Context to Add Blocks to a Region',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '951767fd-6dd0-4655-86d3-2a01aa7c799d',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1375270551,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f30c1b6b-27a3-45d7-a5dc-e240c5089e5c',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p class="summary">You may be asking yourself, how do I add a block to a sidebar or other region, and how do I get it to display on the correct page? In this post I\'ll explain how to use the Context module to do just this.</p>
<p>Blocks are a great way to display content in a more structured way on your page. A block is a may be created with a view, as bean, or a simple block. By placing blocks in regions, you can get different layouts. If you want a sidebar or other region to display on your site, you simply need to add a block to the desired region (provided by your theme) and that region will appear once it has content inside of it. If your site is on <a href="http:// sites.stanford.edu">Stanford Sites</a> your site will have regions such as first (left) and second (right) sidebar.</p>
<p>Drupal almost always gives you several approaches for anything you do. Putting a block in a region is one of those cases. One approach is to use the Blocks module at Structure &gt; Blocks; a second approach is to use the Context module at Structure &gt; Context. At Stanford Web Services, we prefer to define contexts for placing blocks because they provide more flexibility and functionality than what we get on through the Blocks module.</p>
<h2>How Context Works</h2>
<p>Context uses an “If ... then” approach to placing blocks. &nbsp;The Conditions are the “If,” and the Reactions are the “Then.” So, for example, if a condition, such a URL path for a page, is met, then the context will display specific blocks in designated regions on that page. &nbsp;</p>
<p>Using Context, you can designate a whole set of blocks to display, for example, on any events related page. To do this you might define all events-related pages with a common base URL such as:</p>
<div>
	<table><tbody><tr><th>
					<p>URL</p>
				</th>
				<th>
					<p>Page description</p>
				</th>
			</tr><tr><td>
					<p><a href="https://mysite.edu/events" rel="nofollow">https://mysite.edu/events</a></p>
				</td>
				<td>
					<p>Landing page for events</p>
				</td>
			</tr><tr><td>
					<p><a href="https://mysite.edu/events/my-event" rel="nofollow">https://mysite.edu/events/my-event</a></p>
				</td>
				<td>
					<p>Page for a specific event</p>
				</td>
			</tr></tbody></table></div>
<p>Then you’ll create a context at <strong>Structure</strong> &gt; <strong>Context</strong> which will have as one of it’s conditions a path. &nbsp;The path would be designated as:</p>
<div>
	<table><tbody><tr><th>
					<p>Path</p>
				</th>
				<th>
					<p>Description</p>
				</th>
			</tr><tr><td>
					<p>events</p>
				</td>
				<td>
					<p>Landing page for events</p>
				</td>
			</tr><tr><td>
					<p>events/*</p>
				</td>
				<td>
					<p>All individual event pages</p>
				</td>
			</tr></tbody></table></div>
<p>The Reactions, for this example, would be to designate a block or set of blocks to display in one or more regions, such as the sidebar, on the events-related pages.</p>
<h2>Using Contexts to Add Blocks to Regions</h2>
<h3>Check Your Setup</h3>
<ol><li>
		<p>To verify that both the Context and Context UI modules are enabled, navigate to the modules page. &nbsp;From the black admin menu, select <strong>Modules</strong>.</p>
	</li>
	<li>
		<p>If not checked, check the boxes for both Context and Context UI modules.</p>
	</li>
	<li>
		<p>To verify you have the permissions to administer contexts, from the black admin menu, navigate to the permissions page at:<br><strong>People</strong> &gt; <strong>Permissions</strong></p>
	</li>
	<li>
		<p>If not checked, check the box that gives your role the Administer contexts permission.</p>
	</li>
</ol><h3>Create a Context</h3>
<ol><li>
		<p>Navigate to the context page from the black admin menu:<br><strong>Structure</strong> &gt; <strong>Context</strong></p>
	</li>
	<li>
		<p>Click on <strong>+ Add.</strong><br>
			This will bring up the Add a new context page</p>
	</li>
	<li>
		<p>Enter a name for your context. This must be computer readable so you’ll use lowercase letters, dashes or underscores, and no spaces.</p>
	</li>
	<li>
		<p>Enter a tag. This optional tag is used to group similar contexts on the Context UI page.</p>
	</li>
	<li>
		<p>Enter a description. This optional field allows you to describe a context in human readable terms. &nbsp;&nbsp;</p>
	</li>
	<li>
		<p>To add conditions for your context, click on the <strong>&lt;Add a condition&gt;</strong> drop down, and s<span>elect <strong>Path</strong>. &nbsp;</span></p>
	</li>
	<li>
		<p>This will bring up a text edit field. Enter paths, one per line, that describe where you want the context to be effective. &nbsp;For this example enter:<br>
			events<br>
			events/*</p>
	</li>
</ol><h3>Add Reactions (Blocks) to Your Context</h3>
<ol><li>
		<p>To add reactions, click on the <strong>&lt;Add a reaction&gt;</strong> dropdown menu</p>
	</li>
	<li>
		<p>Select <strong>Blocks</strong>.</p>
	</li>
	<li>
		<p>This will bring up a long form listing all the regions available on your site. &nbsp;In the column to the right of this list, about halfway down the page, is a scrollable list of blocks. Use your mouse to scroll through this list and select the blocks you wish to place in a single region.</p>
	</li>
	<li>
		<p>In the center column, click on the <strong>+Add</strong> for the region in which you want to place the blocks, and the blocks should appear in the list for that region.</p>
	</li>
	<li>
		<p>Drag the blocks into correct order with the <strong>+</strong>. (Note: experience has shown that even if the blocks initially appear in the correct order, upon saving, they may not stay. To pre-empt this, simply move them around and back into the correct order before saving.)</p>
	</li>
	<li>
		<p>Once you’ve finished putting blocks into regions, click on <strong>Save</strong>.</p>
	</li>
	<li>
		<p><span>Verify your work by navigating to a page described by the conditions in the context.</span></p>
	</li>
</ol>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p class="summary">You may be asking yourself, how do I add a block to a sidebar or other region, and how do I get it to display on the correct page? In this post I\'ll explain how to use the Context module to do just this.</p>
<p>Blocks are a great way to display content in a more structured way on your page. A block is a may be created with a view, as bean, or a simple block. By placing blocks in regions, you can get different layouts. If you want a sidebar or other region to display on your site, you simply need to add a block to the desired region (provided by your theme) and that region will appear once it has content inside of it. If your site is on <a href="http:// sites.stanford.edu">Stanford Sites</a> your site will have regions such as first (left) and second (right) sidebar.</p>
<p>Drupal almost always gives you several approaches for anything you do. Putting a block in a region is one of those cases. One approach is to use the Blocks module at Structure &gt; Blocks; a second approach is to use the Context module at Structure &gt; Context. At Stanford Web Services, we prefer to define contexts for placing blocks because they provide more flexibility and functionality than what we get on through the Blocks module.</p>
<h2>How Context Works</h2>
<p>Context uses an “If ... then” approach to placing blocks.  The Conditions are the “If,” and the Reactions are the “Then.” So, for example, if a condition, such a URL path for a page, is met, then the context will display specific blocks in designated regions on that page.  </p>
<p>Using Context, you can designate a whole set of blocks to display, for example, on any events related page. To do this you might define all events-related pages with a common base URL such as:</p>
<div>
<table><tbody><tr><th>
<p>URL</p>
</th>
<th>
<p>Page description</p>
</th>
</tr><tr><td>
<p><a href="https://mysite.edu/events" rel="nofollow">https://mysite.edu/events</a></p>
</td>
<td>
<p>Landing page for events</p>
</td>
</tr><tr><td>
<p><a href="https://mysite.edu/events/my-event" rel="nofollow">https://mysite.edu/events/my-event</a></p>
</td>
<td>
<p>Page for a specific event</p>
</td>
</tr></tbody></table></div>
<p>Then you’ll create a context at <strong>Structure</strong> &gt; <strong>Context</strong> which will have as one of it’s conditions a path.  The path would be designated as:</p>
<div>
<table><tbody><tr><th>
<p>Path</p>
</th>
<th>
<p>Description</p>
</th>
</tr><tr><td>
<p>events</p>
</td>
<td>
<p>Landing page for events</p>
</td>
</tr><tr><td>
<p>events/*</p>
</td>
<td>
<p>All individual event pages</p>
</td>
</tr></tbody></table></div>
<p>The Reactions, for this example, would be to designate a block or set of blocks to display in one or more regions, such as the sidebar, on the events-related pages.</p>
<h2>Using Contexts to Add Blocks to Regions</h2>
<h3>Check Your Setup</h3>
<ol><li>
<p>To verify that both the Context and Context UI modules are enabled, navigate to the modules page.  From the black admin menu, select <strong>Modules</strong>.</p>
</li>
<li>
<p>If not checked, check the boxes for both Context and Context UI modules.</p>
</li>
<li>
<p>To verify you have the permissions to administer contexts, from the black admin menu, navigate to the permissions page at:<br /><strong>People</strong> &gt; <strong>Permissions</strong></p>
</li>
<li>
<p>If not checked, check the box that gives your role the Administer contexts permission.</p>
</li>
</ol><h3>Create a Context</h3>
<ol><li>
<p>Navigate to the context page from the black admin menu:<br /><strong>Structure</strong> &gt; <strong>Context</strong></p>
</li>
<li>
<p>Click on <strong>+ Add.</strong><br /><br />
			This will bring up the Add a new context page</p>
</li>
<li>
<p>Enter a name for your context. This must be computer readable so you’ll use lowercase letters, dashes or underscores, and no spaces.</p>
</li>
<li>
<p>Enter a tag. This optional tag is used to group similar contexts on the Context UI page.</p>
</li>
<li>
<p>Enter a description. This optional field allows you to describe a context in human readable terms.   </p>
</li>
<li>
<p>To add conditions for your context, click on the <strong>&lt;Add a condition&gt;</strong> drop down, and s<span>elect <strong>Path</strong>.  </span></p>
</li>
<li>
<p>This will bring up a text edit field. Enter paths, one per line, that describe where you want the context to be effective.  For this example enter:<br /><br />
			events<br /><br />
			events/*</p>
</li>
</ol><h3>Add Reactions (Blocks) to Your Context</h3>
<ol><li>
<p>To add reactions, click on the <strong>&lt;Add a reaction&gt;</strong> dropdown menu</p>
</li>
<li>
<p>Select <strong>Blocks</strong>.</p>
</li>
<li>
<p>This will bring up a long form listing all the regions available on your site.  In the column to the right of this list, about halfway down the page, is a scrollable list of blocks. Use your mouse to scroll through this list and select the blocks you wish to place in a single region.</p>
</li>
<li>
<p>In the center column, click on the <strong>+Add</strong> for the region in which you want to place the blocks, and the blocks should appear in the list for that region.</p>
</li>
<li>
<p>Drag the blocks into correct order with the <strong>+</strong>. (Note: experience has shown that even if the blocks initially appear in the correct order, upon saving, they may not stay. To pre-empt this, simply move them around and back into the correct order before saving.)</p>
</li>
<li>
<p>Once you’ve finished putting blocks into regions, click on <strong>Save</strong>.</p>
</li>
<li>
<p><span>Verify your work by navigating to a page described by the conditions in the context.</span></p>
</li>
</ol>',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 10,
      ),
    ),
  ),
  'field_categories' => array(
    'und' => array(
      0 => array(
        'tid' => 12,
      ),
    ),
  ),
  'field_image' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-07-31 14:35:51 +0300',
  'author_uuid' => 'f0dd442b-e708-4678-8cec-90cec6dee377',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Tips for selecting a Drupal vendor',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '19682808-3d42-4c7a-a2cf-cdf7e140e92c',
  'type' => 'blog',
  'language' => 'und',
  'created' => 1375270551,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f6a9987e-4aca-439d-b525-97c493cad7cd',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p dir="ltr">I provide web project strategy and guidance for Stanford departments looking to hire a vendor for custom web development.  My clients receive a full-service experience that includes business analysis, technical review, needs assessment, research and writing, agency recruitment, proposal evaluation, reference checks, forecasting, and is tailored to their specific needs. My clients are very happy.</p>
<p dir="ltr">However, this model does not scale. A comprehensive selection process can take 6 weeks, and I can’t work with everyone who needs help. Therefore, I intend to use this blog to share information &nbsp;and experiences with the community about some of the basics of vendor selection that could help lots of people at once.</p>
<p dir="ltr">Because of the importance of Drupal in Stanford’s web environment —and the inherent dangers of handing a tool with such flexibility (and thereby margin for error) to a non-specialist— I choose to focus specifically on Drupal for this article, but I should probably write another one for general considerations when sourcing web design and development talent. &nbsp;For today, I will keep it mainly on the Drupal channel, occasionally flipping over to the PM channel.</p>
<p dir="ltr">When selecting a vendor for Drupal work, these are among the things that I look for. Please read these tips <em>before</em> searching for a vendor or signing a contract. </p>
<div class="callout" style="width:80% !important;">
<h2>tl;dr summary</h2>
<ul><li dir="ltr">
<p dir="ltr">Make sure your developer knows the Drupal API</p>
</li>
<li dir="ltr">
<p dir="ltr">Standing in the Drupal community matters</p>
</li>
<li dir="ltr">
<p dir="ltr">Examine portfolio and filter on the specialty suited to your particular needs</p>
</li>
<li dir="ltr">
<p dir="ltr">Require secure code</p>
</li>
<li dir="ltr">
<p dir="ltr">Check references</p>
</li>
<li dir="ltr">
<p dir="ltr">Seek competitive bids</p>
</li>
<li dir="ltr">
<p dir="ltr">Project Management and communication matter</p>
</li>
</ul></div>
<h2 dir="ltr">Knowledge of the Drupal API</h2>
<p dir="ltr"><a href="https://drupal.org/">Drupal</a> has a <a href="http://api.drupal.org/api/drupal/includes!module.inc/group/hooks/7">hook system</a> that allows for any given component of <a href="http://api.drupal.org/api/drupal">how Drupal works</a> to be overridden. It is fundamental that your developer understand this system. Masters of this practice can do amazing things. Those who ignore it break stuff.</p>
<p dir="ltr">A common mistake is hiring an expert PHP developer to build something in Drupal. They will have a solid understanding of the underlying technologies, and will be naturally inclined to seek expediencies (a.k.a. “hack core”). <a href="http://drupal.org/best-practices/do-not-hack-core">That’s bad</a>. An expert PHP programmer could easily become a Drupal developer, but they will need a guided tour before they dig in. The value of this approach may not be apparent or convincing to a developer at the outset.</p>
<h2 dir="ltr">Standing in the Drupal community</h2>
<p>Your preferred agency may seem skilled and professional, but who are their developers exactly? All Drupal developers have profiles on drupal.org. Ask who the lead developer on a project will be, and ask for his or her drupal.org username. You can then look him or her up and discover what contributions they have made to to the Drupal project.</p>
<p dir="ltr">Is your agency a member of the <a href="https://association.drupal.org/">Drupal Association</a>? Do they participate at <a href="http://portland2013.drupal.org/">DrupalCon</a> and Drupal <a href="http://2012.badcamp.net/">Camps</a>? Do they sponsor these events? Do they contribute code back to the open source community? These are all things that matter.</p>
<p>Experience shows that standing in the community can have a direct effect on project outcomes. Drupal is not one project, it is thousands of separate projects (called “contrib” for “contributed modules”), a constellation that orbits one central body that is Drupal Core. This is one of the big reasons that Drupal is so flexible and so powerful. If your custom project pushes the boundaries of what is possible in Drupal, and new functionality is needed to succeed, a dev that is well-established in the contrib space will be more successful in getting patches accepted by &nbsp;module maintainers.</p>
<p dir="ltr">I should acknowledge that not every agency broadcasts their contributions, and plenty of expert implementers don’t have have numerous commits to the Drupal project. I know some stellar developers that have light-looking d.o profiles. It’s not a litmus test, but if the lead dev for an agency doesn’t even have an account, that’s a red flag.</p>
<h2 dir="ltr">Portfolio and sub-specialty</h2>
<p>Not all web projects are the same, and often no two Drupal projects are exactly the same. Some projects require sub-specialties. How strong is your agency of choice at theming? <a href="http://en.wikipedia.org/wiki/DevOps">devops</a>? features? installation profiles? custom module development? evaluating available contrib options? commerce? CRM? SEO? An agency that is excellent overall might not be top-of-list if their skills don’t align with your project requirements and priorities.</p>
<p dir="ltr"><em>Caveat Emptor:</em> do NOT hire a pure marketing/advertising agency without a qualified Drupal development team, and if you hire a print designer with no web experience whatsoever, I guarantee that you will be the owner of a hot mess in about six months..</p>
<h2>Secure Code</h2>
<p>Drupal is a very secure system that is used widely by such entities as the Department of Defense and the White House. The core project is very secure when kept up-to-date and implemented correctly. Drupal also has its own <a href="https://drupal.org/security-team">Security Team</a> that responds to exploits discovered by the community and keeps us busy applying code updates. However, as soon as we introduce a custom module—as large projects almost always do—we must be certain that the vendor we engage is well versed in best practices for <a href="https://drupal.org/writing-secure-code">writing secure code</a>. Simply asking your prospective vendor what they do to ensure that their developers are up to speed on web application security is a step in the right direction.</p>
<h2 dir="ltr">References</h2>
<p>Has your preferred agency worked at Stanford before? If so, which projects, and what was that experience like for the Stanford client? Some of the best agencies in the business (to my chagrin) still have not worked with Stanford, so this shouldn’t really be a barrier to entry; however, you should check with colleagues in order to benefit from institutional memory.</p>
<h2 dir="ltr">Competitive Bids</h2>
<p>The Procurement Office requires competitive bids for development  web development work. Stanford faculty and staff have a fiduciary responsibility to follow Procurement guidelines, and should not abuse the sole source justification. Sole source certainly has its place, but we should be rigorous. If you are tempted to select a vendor based mainly on a prior relationship, slow down, evaluate the project requirements, and take stock of whether you are asking them to operate outside their area of expertise</p>
<h2 dir="ltr">Client Communication and Project Management</h2>
<p>In the early days of my vendor relations career, I prized technical chops over pretty much everything else. That was a mistake. Projects can fail for a variety of reasons, technology being only the most obvious. Successful projects are built on three pillars:</p>
<ol><li dir="ltr">Technical proficiency of the designer, developer, or agency</li>
<li dir="ltr">Project Management (PM)</li>
<li dir="ltr">Client communication</li>
</ol><p dir="ltr">I used to put all of my eggs in basket #1, but have since learned that this stool needs all three legs. Project Management is a highly technical skillset, and the people who are very good at it are rockstars. Not everyone can do it well. A technical PM is an invaluable asset, especially if they can provide deft pushback when needed (and it will be needed at least once on every single project).</p>
<p>I have also learned that PM and client relations are separate proficiencies, and we need both. PMs can be extremely efficient communicators, but may not be best suited for the client relations role, and having an additional point of contact separate from the PM workflow is ideal. If it is an especially huge or complex project with a large stakeholder group on the Stanford side, it is recommended that you have a dedicated PM on the client side to work with the PM on the vendor side. I realize this sounds like overkill, but experience shows that staffing at this level can really pay off and take a great deal of stress off the Stanford project lead (a.k.a. “you”) and save money in the long run.</p>
<h3>Inconvenient Truth Time</h3>
<p dir="ltr">It is a stark fact that doesn’t get talked about much, but for projects that experience difficulty, clients are in fact the problem at least half the time (this is an industry-wide phenomenon and is not unique to Stanford). Technical and creative projects tend naturally toward entropy and confusion, which has to be mitigated on purpose. An agency that possesses a distinct client communication proficiency will succeed more often. Clients are not obtuse luddites, they may be brilliant minds at the top of their chosen field; it’s just that they don’t do web-related work every day, and sometimes need a congenial expert guide to keep the ship on course. If your agency has one of those people —in addition to a skilled development/design and strong PM— then you are in good shape.</p>
<h2>Conclusion</h2>
<p>These days many units at Stanford are opting for Drupal at project outset because of the great amount of resources and expertise that we have accumulated as a University in this technology, and, I wager, the inherent power of the Drupal framework. Drupal is complex, and hard to do well especially if you don\'t want to forward that complexity to the user.  Because Drupal is complex, it is important to engage a bona fide Drupal agency if your project calls for custom solutions.</p>
<p>Lastly, if any Stanford unit has a bad experience with an agency, please let me know. If your unit has a good experience with an agency, also let me know. We want to learn from mistakes and successes alike, and pass that information on to the community.</p>
<p>Good luck with your project!</p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p dir="ltr">I provide web project strategy and guidance for Stanford departments looking to hire a vendor for custom web development.  My clients receive a full-service experience that includes business analysis, technical review, needs assessment, research and writing, agency recruitment, proposal evaluation, reference checks, forecasting, and is tailored to their specific needs. My clients are very happy.</p>
<p dir="ltr">However, this model does not scale. A comprehensive selection process can take 6 weeks, and I can’t work with everyone who needs help. Therefore, I intend to use this blog to share information  and experiences with the community about some of the basics of vendor selection that could help lots of people at once.</p>
<p dir="ltr">Because of the importance of Drupal in Stanford’s web environment —and the inherent dangers of handing a tool with such flexibility (and thereby margin for error) to a non-specialist— I choose to focus specifically on Drupal for this article, but I should probably write another one for general considerations when sourcing web design and development talent.  For today, I will keep it mainly on the Drupal channel, occasionally flipping over to the PM channel.</p>
<p dir="ltr">When selecting a vendor for Drupal work, these are among the things that I look for. Please read these tips <em>before</em> searching for a vendor or signing a contract. </p>
<div class="callout" style="width:80% !important;">
<h2>tl;dr summary</h2>
<ul><li dir="ltr">
<p dir="ltr">Make sure your developer knows the Drupal API</p>
</li>
<li dir="ltr">
<p dir="ltr">Standing in the Drupal community matters</p>
</li>
<li dir="ltr">
<p dir="ltr">Examine portfolio and filter on the specialty suited to your particular needs</p>
</li>
<li dir="ltr">
<p dir="ltr">Require secure code</p>
</li>
<li dir="ltr">
<p dir="ltr">Check references</p>
</li>
<li dir="ltr">
<p dir="ltr">Seek competitive bids</p>
</li>
<li dir="ltr">
<p dir="ltr">Project Management and communication matter</p>
</li>
</ul></div>
<h2 dir="ltr">Knowledge of the Drupal API</h2>
<p dir="ltr"><a href="https://drupal.org/">Drupal</a> has a <a href="http://api.drupal.org/api/drupal/includes!module.inc/group/hooks/7">hook system</a> that allows for any given component of <a href="http://api.drupal.org/api/drupal">how Drupal works</a> to be overridden. It is fundamental that your developer understand this system. Masters of this practice can do amazing things. Those who ignore it break stuff.</p>
<p dir="ltr">A common mistake is hiring an expert PHP developer to build something in Drupal. They will have a solid understanding of the underlying technologies, and will be naturally inclined to seek expediencies (a.k.a. “hack core”). <a href="http://drupal.org/best-practices/do-not-hack-core">That’s bad</a>. An expert PHP programmer could easily become a Drupal developer, but they will need a guided tour before they dig in. The value of this approach may not be apparent or convincing to a developer at the outset.</p>
<h2 dir="ltr">Standing in the Drupal community</h2>
<p>Your preferred agency may seem skilled and professional, but who are their developers exactly? All Drupal developers have profiles on drupal.org. Ask who the lead developer on a project will be, and ask for his or her drupal.org username. You can then look him or her up and discover what contributions they have made to to the Drupal project.</p>
<p dir="ltr">Is your agency a member of the <a href="https://association.drupal.org/">Drupal Association</a>? Do they participate at <a href="http://portland2013.drupal.org/">DrupalCon</a> and Drupal <a href="http://2012.badcamp.net/">Camps</a>? Do they sponsor these events? Do they contribute code back to the open source community? These are all things that matter.</p>
<p>Experience shows that standing in the community can have a direct effect on project outcomes. Drupal is not one project, it is thousands of separate projects (called “contrib” for “contributed modules”), a constellation that orbits one central body that is Drupal Core. This is one of the big reasons that Drupal is so flexible and so powerful. If your custom project pushes the boundaries of what is possible in Drupal, and new functionality is needed to succeed, a dev that is well-established in the contrib space will be more successful in getting patches accepted by  module maintainers.</p>
<p dir="ltr">I should acknowledge that not every agency broadcasts their contributions, and plenty of expert implementers don’t have have numerous commits to the Drupal project. I know some stellar developers that have light-looking d.o profiles. It’s not a litmus test, but if the lead dev for an agency doesn’t even have an account, that’s a red flag.</p>
<h2 dir="ltr">Portfolio and sub-specialty</h2>
<p>Not all web projects are the same, and often no two Drupal projects are exactly the same. Some projects require sub-specialties. How strong is your agency of choice at theming? <a href="http://en.wikipedia.org/wiki/DevOps">devops</a>? features? installation profiles? custom module development? evaluating available contrib options? commerce? CRM? SEO? An agency that is excellent overall might not be top-of-list if their skills don’t align with your project requirements and priorities.</p>
<p dir="ltr"><em>Caveat Emptor:</em> do NOT hire a pure marketing/advertising agency without a qualified Drupal development team, and if you hire a print designer with no web experience whatsoever, I guarantee that you will be the owner of a hot mess in about six months..</p>
<h2>Secure Code</h2>
<p>Drupal is a very secure system that is used widely by such entities as the Department of Defense and the White House. The core project is very secure when kept up-to-date and implemented correctly. Drupal also has its own <a href="https://drupal.org/security-team">Security Team</a> that responds to exploits discovered by the community and keeps us busy applying code updates. However, as soon as we introduce a custom module—as large projects almost always do—we must be certain that the vendor we engage is well versed in best practices for <a href="https://drupal.org/writing-secure-code">writing secure code</a>. Simply asking your prospective vendor what they do to ensure that their developers are up to speed on web application security is a step in the right direction.</p>
<h2 dir="ltr">References</h2>
<p>Has your preferred agency worked at Stanford before? If so, which projects, and what was that experience like for the Stanford client? Some of the best agencies in the business (to my chagrin) still have not worked with Stanford, so this shouldn’t really be a barrier to entry; however, you should check with colleagues in order to benefit from institutional memory.</p>
<h2 dir="ltr">Competitive Bids</h2>
<p>The Procurement Office requires competitive bids for development  web development work. Stanford faculty and staff have a fiduciary responsibility to follow Procurement guidelines, and should not abuse the sole source justification. Sole source certainly has its place, but we should be rigorous. If you are tempted to select a vendor based mainly on a prior relationship, slow down, evaluate the project requirements, and take stock of whether you are asking them to operate outside their area of expertise</p>
<h2 dir="ltr">Client Communication and Project Management</h2>
<p>In the early days of my vendor relations career, I prized technical chops over pretty much everything else. That was a mistake. Projects can fail for a variety of reasons, technology being only the most obvious. Successful projects are built on three pillars:</p>
<ol><li dir="ltr">Technical proficiency of the designer, developer, or agency</li>
<li dir="ltr">Project Management (PM)</li>
<li dir="ltr">Client communication</li>
</ol><p dir="ltr">I used to put all of my eggs in basket #1, but have since learned that this stool needs all three legs. Project Management is a highly technical skillset, and the people who are very good at it are rockstars. Not everyone can do it well. A technical PM is an invaluable asset, especially if they can provide deft pushback when needed (and it will be needed at least once on every single project).</p>
<p>I have also learned that PM and client relations are separate proficiencies, and we need both. PMs can be extremely efficient communicators, but may not be best suited for the client relations role, and having an additional point of contact separate from the PM workflow is ideal. If it is an especially huge or complex project with a large stakeholder group on the Stanford side, it is recommended that you have a dedicated PM on the client side to work with the PM on the vendor side. I realize this sounds like overkill, but experience shows that staffing at this level can really pay off and take a great deal of stress off the Stanford project lead (a.k.a. “you”) and save money in the long run.</p>
<h3>Inconvenient Truth Time</h3>
<p dir="ltr">It is a stark fact that doesn’t get talked about much, but for projects that experience difficulty, clients are in fact the problem at least half the time (this is an industry-wide phenomenon and is not unique to Stanford). Technical and creative projects tend naturally toward entropy and confusion, which has to be mitigated on purpose. An agency that possesses a distinct client communication proficiency will succeed more often. Clients are not obtuse luddites, they may be brilliant minds at the top of their chosen field; it’s just that they don’t do web-related work every day, and sometimes need a congenial expert guide to keep the ship on course. If your agency has one of those people —in addition to a skilled development/design and strong PM— then you are in good shape.</p>
<h2>Conclusion</h2>
<p>These days many units at Stanford are opting for Drupal at project outset because of the great amount of resources and expertise that we have accumulated as a University in this technology, and, I wager, the inherent power of the Drupal framework. Drupal is complex, and hard to do well especially if you don\'t want to forward that complexity to the user.  Because Drupal is complex, it is important to engage a bona fide Drupal agency if your project calls for custom solutions.</p>
<p>Lastly, if any Stanford unit has a bad experience with an agency, please let me know. If your unit has a good experience with an agency, also let me know. We want to learn from mistakes and successes alike, and pass that information on to the community.</p>
<p>Good luck with your project!</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_blog_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 20,
      ),
    ),
  ),
  'field_categories' => array(
    'und' => array(
      0 => array(
        'tid' => 13,
      ),
    ),
  ),
  'field_image' => array(),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-07-31 14:35:51 +0300',
  'author_uuid' => 'f0dd442b-e708-4678-8cec-90cec6dee377',
);
  return $nodes;
}
