<?php
/**
 * @file
 * Code for the SLAC Forum feature.
 */

include_once 'slac_forum.features.inc';

/**
 * Implements hook_form_FORM_ID_alter
 */
/*function slac_forum_form_forum_node_form_alter(&$form, &$form_state, $form_id) {
  $form['body'][LANGUAGE_NONE][0]['#format'] = 'markdown';
  $form['#attached']['js'] = array(
    drupal_get_path('module', 'slac_forum') . '/slac_forum.js',
  );
}*/

/**
 * Implements hook_views_default_views_alter().
 */
function slac_forum_views_default_views_alter(&$views) {
  if (isset($views['advanced_forum_unanswered_topics'])) {
    $handler =& $views['advanced_forum_unanswered_topics']->display['default']->handler;
    $handler->display->display_options['access']['type'] = 'role';
    $handler->display->display_options['access']['role']['3'] = '3';
  }
  if (isset($views['advanced_forum_new_topics'])) {
    $handler =& $views['advanced_forum_new_topics']->display['default']->handler;
    $handler->display->display_options['access']['type'] = 'none';
    $views['advanced_forum_new_topics']->display['page_1']->handler->display->display_options['menu']['title'] = 'Recent posts';
  }
}