<?php
/**
 * @file
 * slac_blog_demo.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function slac_blog_demo_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'SEO',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0afb00da-79ea-45e4-8253-1c07cf782c12',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'vendor',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '0b6cb850-9253-4706-967c-5269ff3f731b',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'Site building',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '25f89c1a-ad28-49ce-ac5d-0da000be0ff3',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'Drupal 7',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '2779b052-a751-45e1-80a5-efa4dadb3867',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'Writing for the Web',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '2d557d82-23f6-4ab1-881e-93a0ca55c724',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'Layouts',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '4f35075e-1d91-4863-81cf-fe938121419c',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'training',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '589b9c1f-9069-49c4-9f7e-8bdcffcc26a0',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'Context',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => '6e1c034d-d332-4fd7-8771-e3c6a62ec739',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'Panels',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '77f52d96-2914-40c4-866d-bf4622d91a13',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'theming',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '86014be0-6ad6-4522-acd6-faa5fb09c1fe',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'tools',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => '8de877ee-60b3-4dfa-8673-541141c036b8',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'Stanford Sites',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a51a59b2-bc06-413a-9fd8-65baf7c680c3',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'business',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'a555ebd8-d8f1-464c-a3de-a903da2fbffd',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'accessibility',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'aaeef82f-6290-44e7-9e21-11965982c65c',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'modules',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'b2959bf4-b73c-4c1c-b8bb-a8d6c55e4dd0',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'agile',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'c2935c8d-9f69-4392-9136-2deadbc90b6c',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'API',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ce8fd534-a7f1-4293-b40e-e8ffc23f82de',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'box',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'd478a0e3-5ecf-4a76-9374-196dc40c631a',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'events',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'dc0520f8-9399-478e-bfff-a0a5b4b59423',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'Display Suite',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'e0e71063-f177-468a-b7b3-f2f7785bb689',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'CSS Injector',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => 0,
    'uuid' => 'ee1b6371-da63-44d0-849f-116ee0803cf8',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  $terms[] = array(
    'name' => 'navigation',
    'description' => NULL,
    'format' => NULL,
    'weight' => 0,
    'uuid' => 'f6178ca4-ebc3-4f99-89c3-aa89b5a65dc6',
    'vocabulary_machine_name' => 'slac_blog_tags',
  );
  return $terms;
}
