<?php
/**
 * @file
 * slac_news_demo_content.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function slac_news_demo_content_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Research Paints New Picture of \'Dinobird\' Feathers',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '7525b632-3944-408f-b3d1-4b86c3ff1820',
  'type' => 'news',
  'language' => 'und',
  'created' => 1375969512,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '44a004e0-ec5e-4ed4-99e4-fe7f3e7e154f',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><strong>Menlo Park, Calif. — </strong>The first complete chemical analysis of feathers from <em>Archaeopteryx,</em> a famous fossil linking dinosaurs and birds, reveals that the feathers were patterned—light in color, with a dark edge and tip—rather than all black, as previously thought.</p>
<p>The findings came from X-ray experiments at the Department of Energy\'s (DOE) SLAC National Accelerator Laboratory, where scientists were able to find chemical traces of the original dinobird and its pigments in the rock that entombed it 150 million years ago.</p>
<p>"This is a big leap forward in our understanding of the evolution of plumage," said Phillip Manning, a paleontologist at the University of Manchester and lead author of the report which received <a href="http://pubs.rsc.org/en/content/articlelanding/2013/ja/c3ja50077b" target="_blank">advanced online publication May 31</a> and appears in print in the June issue of the <em>Journal of Analytical Atomic Spectrometry.</em></p>
<table style="height: 129px; background-color: #ffffff; border: 5px solid #ffffff;" border="5" cellspacing="5" cellpadding="5" width="400" align="left">
<tbody>
<tr>
<td><img title="Updated Archaeopteryx" src="/pictures/full-size/2013-06-12-dinobird.jpg" border="1" alt="Updated Archaeopteryx" width="400" height="294"><br> <span style="font-size: x-small;"><strong>An artist\'s illustration of how <em>Archaeopteryx</em> may have looked sporting its new pigmentation. (Courtesy University of Manchester)</strong></span></td>
</tr>
</tbody>
</table>
<p>Only 11 specimens of <em>Archaeopteryx</em> have been found, the first one consisting of a single feather. Until a few years ago, researchers thought all the bones and tissues of the original animal would have been replaced by minerals during fossilization, leaving no chemical traces behind.</p>
<p>But two recently developed methods have turned up more information about the dinobird and its plumage.</p>
<p>The first is the discovery of melanosomes—microscopic "paint pot" structures containing pigment—in fossils. A team led by researchers at Brown University <a href="http://news.brown.edu/pressreleases/2012/01/archaeopteryx">announced last year</a> that an analysis of melanosomes in the <em>Archaeopteryx</em> feather specimen showed that the feather was black. They identified the feather as a covert—a type of feather that covers the primary and secondary wing feathers—and said its heavy pigmentation may have strengthened it against the wear and tear of flight, as it does in modern birds.</p>
<p>However, that study examined melanosomes from just a few locations in the fossilized feather, said SLAC’s Uwe Bergmann. "It’s actually quite a beautiful paper," he said, "but they took just tiny samples of the feather, not the whole thing."</p>
<p>The second is a method Bergmann, Manning and Roy Wogelius of the University of Manchester developed for rapidly scanning entire fossils and analyzing their chemistry with an X-ray beam at SLAC’s Stanford Synchrotron Radiation Lightsource (SSRL).</p>
<p>Over the past three years, they led a team that used this method to discover <a href="http://home.slac.stanford.edu/pressreleases/2010/20100510.htm">chemicals left by the dinobird’s bones and feathers</a> in the surrounding rock, as well as pigments from the fossilized feathers of two of the first known birds. This allowed them to <a href="http://www6.slac.stanford.edu/news/2011-06-30-xray-reveals-patterns-in-plumage-of-first-birds.aspx">recreate the plumage pattern</a> of a bird that lived more than 120 million years ago.</p>
<p>In the latest study, the team scanned the entire fossil of the first <em>Archaeopteryx</em> feather with the SSRL X-ray beam. They found trace metals associated with pigments and organic sulfur compounds that could only have come from the animal itself. The fact that these compounds have been preserved in the fossil for 150 million years is extraordinary, Manning said.</p>
<p>Together these chemical traces show that the feather was light in color, with areas of darker pigmentation along one edge and on the tip. Scans of a second fossilized <em>Archaeopteryx</em>, known as the Berlin counterpart, revealed that its covert feathers had the same pigmentation pattern, Manning said.</p>
<p>He said the results show that the chemical analysis provided by synchrotron X-ray sources such as SSRL is crucial for understanding these ancient fossils, including plumage patterns that play an important role in the courtship, reproduction and evolution of birds and contain clues to their health, eating habits and environment.</p>
<p>The research team included Dimosthenis Sokaras and Roberto Alonso of SLAC and scientists from the University of Manchester in England, the Black Hills Institute of Geological Research in South Dakota and the Museum für Naturkunde in Berlin, which provided the <em>Archaeopteryx</em> fossils for analysis.</p>
<p><em>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science. To learn more, please visit <a href="http://www.slac.stanford.edu">www.slac.stanford.edu</a>. <br></em></p>
<p><em>SLAC’s Stanford Synchrotron Radiation Lightsource is a third-generation light source producing extremely bright X-rays for basic and applied science. A DOE national user facility, SSRL attracts and supports scientists from around the world who use its state-of-the-art capabilities to make discoveries that benefit society. For more information visit </em><a href="http://www-ssrl.slac.stanford.edu"><em>http://www-ssrl.slac.stanford.edu</em></a><em>.</em></p>
<p><em>DOE’s Office of Science is the single largest supporter of basic research in the physical sciences in the United States, and is working to address some of the most pressing challenges of our time. For more information, please visit </em><a href="science.energy.gov" target="_blank"><em>science.energy.gov</em></a><em>.</em></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p><strong>Menlo Park, Calif. — </strong>The first complete chemical analysis of feathers from <em>Archaeopteryx,</em> a famous fossil linking dinosaurs and birds, reveals that the feathers were patterned—light in color, with a dark edge and tip—rather than all black, as previously thought.</p>
<p>The findings came from X-ray experiments at the Department of Energy\'s (DOE) SLAC National Accelerator Laboratory, where scientists were able to find chemical traces of the original dinobird and its pigments in the rock that entombed it 150 million years ago.</p>
<p>"This is a big leap forward in our understanding of the evolution of plumage," said Phillip Manning, a paleontologist at the University of Manchester and lead author of the report which received <a href="http://pubs.rsc.org/en/content/articlelanding/2013/ja/c3ja50077b" target="_blank">advanced online publication May 31</a> and appears in print in the June issue of the <em>Journal of Analytical Atomic Spectrometry.</em></p>
<table style="height: 129px; background-color: #ffffff; border: 5px solid #ffffff;" border="5" cellspacing="5" cellpadding="5" width="400" align="left"><tbody><tr><td><img title="Updated Archaeopteryx" src="/pictures/full-size/2013-06-12-dinobird.jpg" border="1" alt="Updated Archaeopteryx" width="400" height="294" /><br /><span style="font-size: x-small;"><strong>An artist\'s illustration of how <em>Archaeopteryx</em> may have looked sporting its new pigmentation. (Courtesy University of Manchester)</strong></span></td>
</tr></tbody></table><p>Only 11 specimens of <em>Archaeopteryx</em> have been found, the first one consisting of a single feather. Until a few years ago, researchers thought all the bones and tissues of the original animal would have been replaced by minerals during fossilization, leaving no chemical traces behind.</p>
<p>But two recently developed methods have turned up more information about the dinobird and its plumage.</p>
<p>The first is the discovery of melanosomes—microscopic "paint pot" structures containing pigment—in fossils. A team led by researchers at Brown University <a href="http://news.brown.edu/pressreleases/2012/01/archaeopteryx">announced last year</a> that an analysis of melanosomes in the <em>Archaeopteryx</em> feather specimen showed that the feather was black. They identified the feather as a covert—a type of feather that covers the primary and secondary wing feathers—and said its heavy pigmentation may have strengthened it against the wear and tear of flight, as it does in modern birds.</p>
<p>However, that study examined melanosomes from just a few locations in the fossilized feather, said SLAC’s Uwe Bergmann. "It’s actually quite a beautiful paper," he said, "but they took just tiny samples of the feather, not the whole thing."</p>
<p>The second is a method Bergmann, Manning and Roy Wogelius of the University of Manchester developed for rapidly scanning entire fossils and analyzing their chemistry with an X-ray beam at SLAC’s Stanford Synchrotron Radiation Lightsource (SSRL).</p>
<p>Over the past three years, they led a team that used this method to discover <a href="http://home.slac.stanford.edu/pressreleases/2010/20100510.htm">chemicals left by the dinobird’s bones and feathers</a> in the surrounding rock, as well as pigments from the fossilized feathers of two of the first known birds. This allowed them to <a href="http://www6.slac.stanford.edu/news/2011-06-30-xray-reveals-patterns-in-plumage-of-first-birds.aspx">recreate the plumage pattern</a> of a bird that lived more than 120 million years ago.</p>
<p>In the latest study, the team scanned the entire fossil of the first <em>Archaeopteryx</em> feather with the SSRL X-ray beam. They found trace metals associated with pigments and organic sulfur compounds that could only have come from the animal itself. The fact that these compounds have been preserved in the fossil for 150 million years is extraordinary, Manning said.</p>
<p>Together these chemical traces show that the feather was light in color, with areas of darker pigmentation along one edge and on the tip. Scans of a second fossilized <em>Archaeopteryx</em>, known as the Berlin counterpart, revealed that its covert feathers had the same pigmentation pattern, Manning said.</p>
<p>He said the results show that the chemical analysis provided by synchrotron X-ray sources such as SSRL is crucial for understanding these ancient fossils, including plumage patterns that play an important role in the courtship, reproduction and evolution of birds and contain clues to their health, eating habits and environment.</p>
<p>The research team included Dimosthenis Sokaras and Roberto Alonso of SLAC and scientists from the University of Manchester in England, the Black Hills Institute of Geological Research in South Dakota and the Museum für Naturkunde in Berlin, which provided the <em>Archaeopteryx</em> fossils for analysis.</p>
<p><em>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science. To learn more, please visit <a href="http://www.slac.stanford.edu">www.slac.stanford.edu</a>. <br /></em></p>
<p><em>SLAC’s Stanford Synchrotron Radiation Lightsource is a third-generation light source producing extremely bright X-rays for basic and applied science. A DOE national user facility, SSRL attracts and supports scientists from around the world who use its state-of-the-art capabilities to make discoveries that benefit society. For more information visit </em><a href="http://www-ssrl.slac.stanford.edu"><em>http://www-ssrl.slac.stanford.edu</em></a><em>.</em></p>
<p><em>DOE’s Office of Science is the single largest supporter of basic research in the physical sciences in the United States, and is working to address some of the most pressing challenges of our time. For more information, please visit </em><a href="science.energy.gov" target="_blank"><em>science.energy.gov</em></a><em>.</em></p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_link' => array(),
  'field_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 26,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_news_category' => array(
    'und' => array(
      0 => array(
        'tid' => 21,
        'uuid' => '2b63fdee-aa9f-4a8e-818c-c4b808fe6731',
      ),
    ),
  ),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-08-08 13:45:00',
        'timezone' => 'Europe/Helsinki',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_contact_information' => array(
    'und' => array(
      0 => array(
        'value' => 'Bronwyn Barnett: bronwynb@slac.stanford.edu, (650) 926-8580',
        'format' => NULL,
        'safe_value' => 'Bronwyn Barnett: bronwynb@slac.stanford.edu, (650) 926-8580',
      ),
    ),
  ),
  'field_citation' => array(
    'und' => array(
      0 => array(
        'value' => 'Phillip Manning, et al., J. Anal. At. Spectrom., June, 2013 (10.1039/C3JA50077B)',
        'format' => NULL,
        'safe_value' => 'Phillip Manning, et al., J. Anal. At. Spectrom., June, 2013 (10.1039/C3JA50077B)',
      ),
    ),
  ),
  'field_news_tags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-08 16:45:12 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Speed Limit Set for Ultrafast Electrical Switch',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => 'ba4e3cbe-90fc-4a68-8aa3-df3b98ceee6c',
  'type' => 'news',
  'language' => 'und',
  'created' => 1375801760,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '906c7c49-881b-43fb-bef8-1b8ded8cfc87',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'Menlo Park, Calif. — Researchers from the U.S. Department of Energy\'s (DOE) SLAC National Accelerator Laboratory have clocked the fastest-possible electrical switching in magnetite, a naturally magnetic mineral. Their results could drive innovations in the tiny transistors that control the flow of electricity across silicon chips, enabling faster, more powerful computing devices.

Scientists using SLAC\'s Linac Coherent Light Source (LCLS) X-ray laser found that it takes only 1 trillionth of a second to flip the on-off electrical switch in samples of magnetite, which is thousands of times faster than in transistors now in use. The results were published July 28 in Nature Materials.

"This breakthrough research reveals for the first time the \'speed limit\' for electrical switching in this material," said Roopali Kukreja, a materials science researcher at SLAC and Stanford University who is a lead author of the study.

The LCLS experiment also showed researchers how the electronic structure of the sample rearranged into non-conducting "islands" surrounded by electrically conducting regions, which began to form just hundreds of quadrillionths of a second after a laser pulse struck the sample. The study shows how such conducting and non-conducting states can coexist and create electrical pathways in next-generation transistors.

Scientists first hit each sample with a visible-light laser, which fragmented the material\'s electronic structure at an atomic scale, rearranging it to form the islands. The laser blast was followed closely by an ultrabright, ultrashort X-ray pulse that allowed researchers to study, for the first time, the timing and details of changes in the sample excited by the initial laser strike.

By slightly adjusting the interval of the X-ray pulses, they precisely measured how long it took the material to shift from a non-conducting to an electrically conducting state, and observed the structural changes during this switch.

Scientists had worked for decades to resolve this electrical structure at the atomic level, and just last year another research team had identified its building blocks as "trimerons" – formed by three iron atoms that lock in the charges. That finding provided key insights in interpreting results from the LCLS experiment.

The magnetite had to be cooled to minus 190 degrees Celsius to lock its electrical charges in place, so the next step is to study more complex materials and room-temperature applications, Kukreja said. Future experiments will aim to identify exotic compounds and test new techniques to induce the switching and tap into other properties that are superior to modern-day silicon transistors. The researchers have already conducted follow-up studies focusing on a hybrid material that exhibits similar ultrafast switching properties at near room temperature, which makes it a better candidate for commercial use than magnetite.

Hermann Dürr, the principal investigator of the LCLS experiment and senior staff scientist for the Stanford Institute for Materials and Energy Sciences (SIMES), said there is a major global effort underway to go beyond modern semiconductor transistors using new materials to satisfy demands for smaller and faster computers, and LCLS has the unique ability to home in on processes that occur at the scale of atoms in trillionths and quadrillionths of a second.

While magnetite\'s basic magnetic properties have been known for thousands of years, the experiment shows how much still can be learned about the more exotic electronic properties of magnetite and other more complex materials using LCLS, Dürr said.

Other collaborating scientists on this research were from Helmholtz-Zentrum Berlin for Materials and Energy; Hamburg University/Center for Free Electron Laser Science (CFEL); University of Amsterdam; the T-REX laboratory at the ELETTRA-Sincrotrone Trieste and University of Trieste; Cologne, Potsdam Regensburg and Purdue universities; the Advanced Light Source at Lawrence Berkeley National Laboratory; and SwissFEL.

Research at Stanford University was supported through SIMES and LCLS by the DOE Office of Science. Portions of this research were carried out on the Soft X-ray (SXR) instrument at the LCLS, a user facility operated by Stanford University for the DOE. SXR is funded by a consortium including LCLS, Stanford, Berkeley Lab, CFEL, University of Hamburg and several other research organizations in Europe.

SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the DOE Office of Science. To learn more, please visit www.slac.stanford.edu.

DOE’s Office of Science is the single largest supporter of basic research in the physical sciences in the United States, and is working to address some of the most pressing challenges of our time. For more information, please visit science.energy.gov.',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>Menlo Park, Calif. — Researchers from the U.S. Department of Energy\'s (DOE) SLAC National Accelerator Laboratory have clocked the fastest-possible electrical switching in magnetite, a naturally magnetic mineral. Their results could drive innovations in the tiny transistors that control the flow of electricity across silicon chips, enabling faster, more powerful computing devices.</p>
<p>Scientists using SLAC\'s Linac Coherent Light Source (LCLS) X-ray laser found that it takes only 1 trillionth of a second to flip the on-off electrical switch in samples of magnetite, which is thousands of times faster than in transistors now in use. The results were published July 28 in Nature Materials.</p>
<p>"This breakthrough research reveals for the first time the \'speed limit\' for electrical switching in this material," said Roopali Kukreja, a materials science researcher at SLAC and Stanford University who is a lead author of the study.</p>
<p>The LCLS experiment also showed researchers how the electronic structure of the sample rearranged into non-conducting "islands" surrounded by electrically conducting regions, which began to form just hundreds of quadrillionths of a second after a laser pulse struck the sample. The study shows how such conducting and non-conducting states can coexist and create electrical pathways in next-generation transistors.</p>
<p>Scientists first hit each sample with a visible-light laser, which fragmented the material\'s electronic structure at an atomic scale, rearranging it to form the islands. The laser blast was followed closely by an ultrabright, ultrashort X-ray pulse that allowed researchers to study, for the first time, the timing and details of changes in the sample excited by the initial laser strike.</p>
<p>By slightly adjusting the interval of the X-ray pulses, they precisely measured how long it took the material to shift from a non-conducting to an electrically conducting state, and observed the structural changes during this switch.</p>
<p>Scientists had worked for decades to resolve this electrical structure at the atomic level, and just last year another research team had identified its building blocks as "trimerons" – formed by three iron atoms that lock in the charges. That finding provided key insights in interpreting results from the LCLS experiment.</p>
<p>The magnetite had to be cooled to minus 190 degrees Celsius to lock its electrical charges in place, so the next step is to study more complex materials and room-temperature applications, Kukreja said. Future experiments will aim to identify exotic compounds and test new techniques to induce the switching and tap into other properties that are superior to modern-day silicon transistors. The researchers have already conducted follow-up studies focusing on a hybrid material that exhibits similar ultrafast switching properties at near room temperature, which makes it a better candidate for commercial use than magnetite.</p>
<p>Hermann Dürr, the principal investigator of the LCLS experiment and senior staff scientist for the Stanford Institute for Materials and Energy Sciences (SIMES), said there is a major global effort underway to go beyond modern semiconductor transistors using new materials to satisfy demands for smaller and faster computers, and LCLS has the unique ability to home in on processes that occur at the scale of atoms in trillionths and quadrillionths of a second.</p>
<p>While magnetite\'s basic magnetic properties have been known for thousands of years, the experiment shows how much still can be learned about the more exotic electronic properties of magnetite and other more complex materials using LCLS, Dürr said.</p>
<p>Other collaborating scientists on this research were from Helmholtz-Zentrum Berlin for Materials and Energy; Hamburg University/Center for Free Electron Laser Science (CFEL); University of Amsterdam; the T-REX laboratory at the ELETTRA-Sincrotrone Trieste and University of Trieste; Cologne, Potsdam Regensburg and Purdue universities; the Advanced Light Source at Lawrence Berkeley National Laboratory; and SwissFEL.</p>
<p>Research at Stanford University was supported through SIMES and LCLS by the DOE Office of Science. Portions of this research were carried out on the Soft X-ray (SXR) instrument at the LCLS, a user facility operated by Stanford University for the DOE. SXR is funded by a consortium including LCLS, Stanford, Berkeley Lab, CFEL, University of Hamburg and several other research organizations in Europe.</p>
<p>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the DOE Office of Science. To learn more, please visit <a href="http://www.slac.stanford.edu">www.slac.stanford.edu</a>.</p>
<p>DOE’s Office of Science is the single largest supporter of basic research in the physical sciences in the United States, and is working to address some of the most pressing challenges of our time. For more information, please visit science.energy.gov.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_link' => array(),
  'field_news_media' => array(),
  'field_news_category' => array(
    'und' => array(
      0 => array(
        'tid' => 21,
        'uuid' => '2b63fdee-aa9f-4a8e-818c-c4b808fe6731',
      ),
    ),
  ),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-07-28 15:00:00',
        'timezone' => 'Europe/Helsinki',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_contact_information' => array(
    'und' => array(
      0 => array(
        'value' => 'Andy Freeberg, SLAC, afreeberg@slac.stanford.edu, (650) 926-4359',
        'format' => NULL,
        'safe_value' => 'Andy Freeberg, SLAC, afreeberg@slac.stanford.edu, (650) 926-4359',
      ),
    ),
  ),
  'field_citation' => array(
    'und' => array(
      0 => array(
        'value' => 'S. de Jong et al., Nature Materials, 28 July 2013 (10.1038/NMAT3718)',
        'format' => NULL,
        'safe_value' => 'S. de Jong et al., Nature Materials, 28 July 2013 (10.1038/NMAT3718)',
      ),
    ),
  ),
  'field_news_tags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-06 18:09:20 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'A New Tool to Split X-ray Laser Pulses',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 1,
  'sticky' => 0,
  'vuuid' => '5ddf1ba3-5615-458a-91a7-693e37a27006',
  'type' => 'news',
  'language' => 'und',
  'created' => 1375368689,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'b0fca974-4f47-4b0f-bb3b-7bdfae359929',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'A new tool at SLAC\'s Linac Coherent Light Source splits individual X-ray laser pulses into two pulses that can hit a target one right after another with precisely controlled timing, allowing scientists to trigger and measure specific ultrafast changes in atoms and molecules.


(Click to view larger image.) This soft X-ray split-and-delay system divides individual X-ray laser pulses into two separate, closely spaced pulses at SLAC\'s LCLS. (Matt Beardsley/SLAC)
Built through a collaboration of SLAC and Western Michigan University and installed in May, the system controls the tilt and height of two silicon mirrors to split the pulses and vary their arrival times by up to 200 femtoseconds, or quadrillionths of a second, with a timing accuracy down to a fraction of a femtosecond.

The soft X-ray split-and-delay tool has already been put to use in two experiments at LCLS.

"It\'s working even better than designed," said Brendan Murphy, a postdoctoral research associate at Western Michigan University who played a leading role in the system\'s development. "With these first experiments we\'ve established that this is an effective tool that offers unique strengths over other approaches."

Nora Berrah of Western Michigan University, who has led pioneering experiments at LCLS, worked with John Bozek, a staff scientist who manages the LCLS Soft X-ray Department, to oversee the development of the split-and-delay system. Berrah said the split-and-delay tool can be used to study and refine the timeline of fundamental processes in molecules and atoms, such as the creation of highly charged states, and explore the rearrangement of an atom\'s innermost electrons.

 
Brendan Murphy of Western Michigan University discusses the soft X-ray split-and-delay tool installed at SLAC. (SLAC Multimedia Communications)
In the first experiment using the system, a research team led by Berrah and Murphy measured the possible fundamental mechanisms for radiation damage in a large molecule to model damage in biomolecules. "We were watching how a big molecule falls apart after radiation damage," Berrah said, in order to understand how to best minimize this damage.

While there are already techniques and tools to divide X-ray pulses and produce closely spaced pulses, as well as several more in development for use at LCLS and other X-ray lasers, the new system is distinguished by its precise timing and the ability to measure the energy of every pulse. The first pulse "pumps" energy into the sample to create a specific response, and the following pulse probes and measures the resulting changes at a specific point in time. The energy signatures of the pump and probe pulses allow researchers to measure and interpret their effects on the sample.

Working in the soft X-ray range, this new system can be used to excite changes in atoms of a specific element, said Murphy, who is a part of Berrah\'s research group.

"You can pick which element you want to study in a given sample and even within a molecule," he said.

With other two-pulse techniques, a timing jitter, or fluctuations, typically make it difficult to precisely space the pulses. With this new split-delay tool, the spacing between pulses "is almost jitter-free on a scale of even the shortest X-ray pulses," Murphy said.

Currently installed at the Atomic, Molecular and Optical Science (AMO) experimental station at LCLS, the new tool is transportable and can be moved to a neighboring soft X-ray experimental station.

The system was funded through a Single Individual and Small Group Research grant (SISGR) awarded to Western Michigan University by the U.S. Department of Energy Basic Energy Sciences Division of Chemical Sciences, Geosciences and Energy Biosciences, and was also paid for with LCLS funds.',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>A new tool at SLAC\'s Linac Coherent Light Source splits individual X-ray laser pulses into two pulses that can hit a target one right after another with precisely controlled timing, allowing scientists to trigger and measure specific ultrafast changes in atoms and molecules.</p>
<p>(Click to view larger image.) This soft X-ray split-and-delay system divides individual X-ray laser pulses into two separate, closely spaced pulses at SLAC\'s LCLS. (Matt Beardsley/SLAC)<br />
Built through a collaboration of SLAC and Western Michigan University and installed in May, the system controls the tilt and height of two silicon mirrors to split the pulses and vary their arrival times by up to 200 femtoseconds, or quadrillionths of a second, with a timing accuracy down to a fraction of a femtosecond.</p>
<p>The soft X-ray split-and-delay tool has already been put to use in two experiments at LCLS.</p>
<p>"It\'s working even better than designed," said Brendan Murphy, a postdoctoral research associate at Western Michigan University who played a leading role in the system\'s development. "With these first experiments we\'ve established that this is an effective tool that offers unique strengths over other approaches."</p>
<p>Nora Berrah of Western Michigan University, who has led pioneering experiments at LCLS, worked with John Bozek, a staff scientist who manages the LCLS Soft X-ray Department, to oversee the development of the split-and-delay system. Berrah said the split-and-delay tool can be used to study and refine the timeline of fundamental processes in molecules and atoms, such as the creation of highly charged states, and explore the rearrangement of an atom\'s innermost electrons.</p>
<p>Brendan Murphy of Western Michigan University discusses the soft X-ray split-and-delay tool installed at SLAC. (SLAC Multimedia Communications)<br />
In the first experiment using the system, a research team led by Berrah and Murphy measured the possible fundamental mechanisms for radiation damage in a large molecule to model damage in biomolecules. "We were watching how a big molecule falls apart after radiation damage," Berrah said, in order to understand how to best minimize this damage.</p>
<p>While there are already techniques and tools to divide X-ray pulses and produce closely spaced pulses, as well as several more in development for use at LCLS and other X-ray lasers, the new system is distinguished by its precise timing and the ability to measure the energy of every pulse. The first pulse "pumps" energy into the sample to create a specific response, and the following pulse probes and measures the resulting changes at a specific point in time. The energy signatures of the pump and probe pulses allow researchers to measure and interpret their effects on the sample.</p>
<p>Working in the soft X-ray range, this new system can be used to excite changes in atoms of a specific element, said Murphy, who is a part of Berrah\'s research group.</p>
<p>"You can pick which element you want to study in a given sample and even within a molecule," he said.</p>
<p>With other two-pulse techniques, a timing jitter, or fluctuations, typically make it difficult to precisely space the pulses. With this new split-delay tool, the spacing between pulses "is almost jitter-free on a scale of even the shortest X-ray pulses," Murphy said.</p>
<p>Currently installed at the Atomic, Molecular and Optical Science (AMO) experimental station at LCLS, the new tool is transportable and can be moved to a neighboring soft X-ray experimental station.</p>
<p>The system was funded through a Single Individual and Small Group Research grant (SISGR) awarded to Western Michigan University by the U.S. Department of Energy Basic Energy Sciences Division of Chemical Sciences, Geosciences and Energy Biosciences, and was also paid for with LCLS funds.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_link' => array(
    'und' => array(
      0 => array(
        'url' => 'www.google.com',
        'title' => 'Scientific American',
        'attributes' => array(),
      ),
    ),
  ),
  'field_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 21,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_news_category' => array(
    'und' => array(
      0 => array(
        'tid' => 20,
        'uuid' => 'eebfd8ab-8943-4b70-aeb1-a6ed3ba11e3d',
      ),
    ),
  ),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-08-08 01:45:00',
        'timezone' => 'Europe/Helsinki',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_contact_information' => array(),
  'field_citation' => array(),
  'field_news_tags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-01 17:51:29 +0300',
);
  $nodes[] = array(
  'uid' => 6,
  'title' => 'New Test Bed Probes the Origin of Pulses at LCLS',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'db52862c-8e4c-4cc1-98c8-82bf31a61783',
  'type' => 'news',
  'language' => 'und',
  'created' => 1375967976,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'c7b0a800-cd88-4e9b-b2b6-3e792f4195d3',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => 'It all comes down to one tiny spot on a diamond-cut, highly pure copper plate. That\'s where every X-ray laser pulse at SLAC\'s Linac Coherent Light Source gets its start. That tiny spot must be close to perfect or it can impair and even halt LCLS operations.

SLAC in May 2013 opened a new test facility at the Accelerator Structure Test Area (ASTA) to study the complex physics and chemistry that cause that shiny copper slab, called a cathode, to degrade over time, and to identify ways to maintain and improve its performance.

"ASTA is the ideal place, the perfect place to test the cathode, RF (radio-frequency) gun and the laser for the future demands of LCLS and LCLS-II, the planned upgrade of LCLS," said Feng Zhou, a SLAC physicist who has served since March 2013 as a project leader for cathode research and development at ASTA.

Zhou added, "Understanding cathode performance and degradation has been kind of a black art, and ASTA will for the first time allow very detailed analysis aimed at maximizing performance and longevity."


(Click to view larger image.) SLAC\'s ASTA research team. Front row, from left: Feng Zhou, Marcelo Ferreira. Second row, from left: Wolfram \'Wolfi\' Helml, Joe Olszewski, Jeff Corbett. Third row, from left: Erik Jongewaard, Sasha Gilevich. Fourth row, from left (standing): James Lewandowski, John Eichner, John Sheppard, Nick Hartmann, Stephen Weathersby and Theo Vecchione. (Courtesy Feng Zhou)
The copper cathode is part of the photocathode gun, the first step in a mile-long chain of precisely tuned equipment that makes up the LCLS. In the photocathode gun, a rapid-fire ultraviolet laser strikes a millimeter-size spot on the cathode. This generates tight bunches of electrons that are accelerated in a 1-kilometer section of SLAC\'s linear accelerator. The electrons then travel through a series of magnets, called an undulator, and emit ultrabright X-ray light that travels to LCLS experimental stations at a rate of more than 100 pulses per second.

Troubles with the LCLS cathode, including technical issues that required change-out of a cathode about two years ago, sparked SLAC\'s push for the cathode test bed, said Erik Jongewaard, a lead engineer for the project and former project leader who oversaw the construction of the test facility at ASTA.

"We couldn\'t get enough charge out of the cathode," said Jongewaard, "so there was a huge amount of emphasis – a lot of work by a lot of folks – looking at ways of getting around the problem." If the cathode does not produce sufficient electrons when struck by the ultraviolet laser pulses, the intensity of X-ray pulses will be limited.

Using a higher-intensity laser beam to "clean" the surface of the cathode has proven effective but requires more study.

"We want to understand the laser-cleaning process and also try to make sure this technique is robust. We also want to know the technique\'s limitations, and what is the optimum \'recipe,\'" said Zhou.

Jongewaard said, "There may be a delicate balancing act in how much laser cleaning the surface can take before the cleaning itself damages the cathode." ASTA will enable precise measurements of how the cleaning improves or degrades the performance of each electron bunch.

ASTA will likely be used to study specialized coatings and determine whether they improve and extend the cathode\'s performance, too, and to test new ways to replace aging cathodes that minimize LCLS downtime.

Increasing the repetition rate of LCLS pulses, which would multiply the amount of data collected in experiments, will require advances in cathode, laser and RF gun systems, as well as in related RF systems. Such upgrades could be tested at ASTA.

A range of sensors at ASTA will study the properties of the electrons produced with the photocathode guns, the effectiveness of the laser system that drives the electron bunches and the chemistry at the surface of the cathodes.

The drive laser system used for photocathode gun research at ASTA will also be used in a separate effort to develop laser techniques for echo-enabled harmonic generation, which can produce highly tunable X-ray laser pulses.

Ryan Coffee, an LCLS staff scientist, and others are also working on a new diagnostic tool, to be shared by both research programs, that can precisely measure the properties of ultraviolet laser pulses. This group had developed a similar tool to measure X-ray laser pulses. Coffee said the laser system at ASTA has already been upgraded to provide more flexibility for a range of experiments benefiting both efforts. "Everybody wins," he said.

Jongewaard said ASTA could eventually serve as a hub for researchers from other labs to collaborate in testing cathodes and related components. "In some sense this could become a small user facility," he said.',
        'summary' => '',
        'format' => 'filtered_html',
        'safe_value' => '<p>It all comes down to one tiny spot on a diamond-cut, highly pure copper plate. That\'s where every X-ray laser pulse at SLAC\'s Linac Coherent Light Source gets its start. That tiny spot must be close to perfect or it can impair and even halt LCLS operations.</p>
<p>SLAC in May 2013 opened a new test facility at the Accelerator Structure Test Area (ASTA) to study the complex physics and chemistry that cause that shiny copper slab, called a cathode, to degrade over time, and to identify ways to maintain and improve its performance.</p>
<p>"ASTA is the ideal place, the perfect place to test the cathode, RF (radio-frequency) gun and the laser for the future demands of LCLS and LCLS-II, the planned upgrade of LCLS," said Feng Zhou, a SLAC physicist who has served since March 2013 as a project leader for cathode research and development at ASTA.</p>
<p>Zhou added, "Understanding cathode performance and degradation has been kind of a black art, and ASTA will for the first time allow very detailed analysis aimed at maximizing performance and longevity."</p>
<p>(Click to view larger image.) SLAC\'s ASTA research team. Front row, from left: Feng Zhou, Marcelo Ferreira. Second row, from left: Wolfram \'Wolfi\' Helml, Joe Olszewski, Jeff Corbett. Third row, from left: Erik Jongewaard, Sasha Gilevich. Fourth row, from left (standing): James Lewandowski, John Eichner, John Sheppard, Nick Hartmann, Stephen Weathersby and Theo Vecchione. (Courtesy Feng Zhou)<br />
The copper cathode is part of the photocathode gun, the first step in a mile-long chain of precisely tuned equipment that makes up the LCLS. In the photocathode gun, a rapid-fire ultraviolet laser strikes a millimeter-size spot on the cathode. This generates tight bunches of electrons that are accelerated in a 1-kilometer section of SLAC\'s linear accelerator. The electrons then travel through a series of magnets, called an undulator, and emit ultrabright X-ray light that travels to LCLS experimental stations at a rate of more than 100 pulses per second.</p>
<p>Troubles with the LCLS cathode, including technical issues that required change-out of a cathode about two years ago, sparked SLAC\'s push for the cathode test bed, said Erik Jongewaard, a lead engineer for the project and former project leader who oversaw the construction of the test facility at ASTA.</p>
<p>"We couldn\'t get enough charge out of the cathode," said Jongewaard, "so there was a huge amount of emphasis – a lot of work by a lot of folks – looking at ways of getting around the problem." If the cathode does not produce sufficient electrons when struck by the ultraviolet laser pulses, the intensity of X-ray pulses will be limited.</p>
<p>Using a higher-intensity laser beam to "clean" the surface of the cathode has proven effective but requires more study.</p>
<p>"We want to understand the laser-cleaning process and also try to make sure this technique is robust. We also want to know the technique\'s limitations, and what is the optimum \'recipe,\'" said Zhou.</p>
<p>Jongewaard said, "There may be a delicate balancing act in how much laser cleaning the surface can take before the cleaning itself damages the cathode." ASTA will enable precise measurements of how the cleaning improves or degrades the performance of each electron bunch.</p>
<p>ASTA will likely be used to study specialized coatings and determine whether they improve and extend the cathode\'s performance, too, and to test new ways to replace aging cathodes that minimize LCLS downtime.</p>
<p>Increasing the repetition rate of LCLS pulses, which would multiply the amount of data collected in experiments, will require advances in cathode, laser and RF gun systems, as well as in related RF systems. Such upgrades could be tested at ASTA.</p>
<p>A range of sensors at ASTA will study the properties of the electrons produced with the photocathode guns, the effectiveness of the laser system that drives the electron bunches and the chemistry at the surface of the cathodes.</p>
<p>The drive laser system used for photocathode gun research at ASTA will also be used in a separate effort to develop laser techniques for echo-enabled harmonic generation, which can produce highly tunable X-ray laser pulses.</p>
<p>Ryan Coffee, an LCLS staff scientist, and others are also working on a new diagnostic tool, to be shared by both research programs, that can precisely measure the properties of ultraviolet laser pulses. This group had developed a similar tool to measure X-ray laser pulses. Coffee said the laser system at ASTA has already been upgraded to provide more flexibility for a range of experiments benefiting both efforts. "Everybody wins," he said.</p>
<p>Jongewaard said ASTA could eventually serve as a hub for researchers from other labs to collaborate in testing cathodes and related components. "In some sense this could become a small user facility," he said.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_link' => array(),
  'field_news_media' => array(),
  'field_news_category' => array(
    'und' => array(
      0 => array(
        'tid' => 20,
        'uuid' => 'eebfd8ab-8943-4b70-aeb1-a6ed3ba11e3d',
      ),
    ),
  ),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-08-08 13:15:00',
        'timezone' => 'Europe/Helsinki',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_contact_information' => array(),
  'field_citation' => array(),
  'field_news_tags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 6,
  'comment_count' => 0,
  'name' => 'proppl',
  'picture' => 0,
  'data' => NULL,
  'date' => '2013-08-08 16:19:36 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'A New Tool to Split X-ray Laser Pulses',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'ebc35b1e-3f24-416d-9351-afc001b69c9f',
  'type' => 'news',
  'language' => 'und',
  'created' => 1375969778,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'e3d84571-2811-412d-bea4-33c382aa17aa',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>A new tool at SLAC\'s Linac Coherent Light Source splits individual X-ray laser pulses into two pulses that can hit a target one right after another with precisely controlled timing, allowing scientists to trigger and measure specific ultrafast changes in atoms and molecules.</p>
<p>
</p><table style="height: 129px; background-color: #ffffff; border: 5px solid #ffffff;" border="5" cellspacing="1" cellpadding="5" width="133" align="left">
<tbody>
<tr>
<td><a title="Photo - Soft X-ray split-and-delay system" href="https://news.slac.stanford.edu/sites/default/files/images/image/13-07-29-splitdelay-990b.jpg" target="_blank"><img title="Soft X-ray Split-and-delay System" src="https://news.slac.stanford.edu/sites/default/files/images/image/13-07-29-splitdelay-990b.jpg" alt="" width="350"></a><br> <strong><span style="font-size: x-small;">(<a title="Soft X-ray split-and-delay system" href="https://news.slac.stanford.edu/sites/default/files/images/image/13-07-29-splitdelay-990b.jpg" target="_blank">Click to view larger image.</a>) This soft X-ray split-and-delay system divides individual X-ray laser pulses into two separate, closely spaced pulses at SLAC\'s LCLS. </span></strong><span style="font-size: x-small;"> <em>(Matt Beardsley/SLAC)</em></span></td>
</tr>
</tbody>
</table>
<p></p>
<p>Built through a collaboration of SLAC and Western Michigan University and installed in May, the system controls the tilt and height of two silicon mirrors to split the pulses and vary their arrival times by up to 200 femtoseconds, or quadrillionths of a second, with a timing accuracy down to a fraction of a femtosecond.</p>
<p>The <a href="http://iopscience.iop.org/1742-6596/425/15/152021">soft X-ray split-and-delay tool</a> has already been put to use in two experiments at LCLS.</p>
<p>"It\'s working even better than designed," said Brendan Murphy, a postdoctoral research associate at Western Michigan University who played a leading role in the system\'s development. "With these first experiments we\'ve established that this is an effective tool that offers unique strengths over other approaches."</p>
<p>Nora Berrah of Western Michigan University, who has led <a href="http://home.slac.stanford.edu/pressreleases/2010/20100630.htm" target="_blank">pioneering experiments</a> at LCLS, worked with John Bozek, a staff scientist who manages the LCLS Soft X-ray Department, to oversee the development of the split-and-delay system. Berrah said the split-and-delay tool can be used to study and refine the timeline of fundamental processes in molecules and atoms, such as the creation of highly charged states, and explore the rearrangement of an atom\'s innermost electrons.</p>
<table style="height: 129px; background-color: #ffffff; border: 5px solid #ffffff;" border="5" cellspacing="1" cellpadding="5" width="133" align="left">
<tbody>
<tr>
<td>
<object width="596" height="335">
<param name="movie" value="//www.youtube.com/v/L0BOZ4djafM?hl=en_US&amp;version=3&amp;rel=0">
<param name="allowFullScreen" value="true">
<param name="allowscriptaccess" value="always"><embed type="application/x-shockwave-flash" width="596" height="335" src="//www.youtube.com/v/L0BOZ4djafM?hl=en_US&amp;version=3&amp;rel=0" allowscriptaccess="always" allowfullscreen="true">
</object>
<br><span style="font-size: x-small;"><span style="color: #000000;"><strong>Brendan Murphy of Western Michigan University discusses the soft X-ray split-and-delay tool installed at SLAC.</strong></span> <em>(SLAC Multimedia Communications)</em></span></td>
</tr>
</tbody>
</table>
<p>In the first experiment using the system, a research team led by Berrah and Murphy measured the possible fundamental mechanisms for radiation damage in a large molecule to model damage in biomolecules. "We were watching how a big molecule falls apart after radiation damage," Berrah said, in order to understand how to best minimize this damage.</p>
<p>While there are already <a href="http://www6.slac.stanford.edu/news/2013-03-26-two-color.aspx">techniques</a> and <a href="http://www6.slac.stanford.edu/news/2013-03-12-X-ray-beam-sharing.aspx">tools</a> to divide X-ray pulses and produce closely spaced pulses, as well as several more in development for use at LCLS and other X-ray lasers, the new system is distinguished by its precise timing and the ability to measure the energy of every pulse. The first pulse "pumps" energy into the sample to create a specific response, and the following pulse probes and measures the resulting changes at a specific point in time. The energy signatures of the pump and probe pulses allow researchers to measure and interpret their effects on the sample.</p>
<p>Working in the soft X-ray range, this new system can be used to excite changes in atoms of a specific element, said Murphy, who is a part of Berrah\'s research group.</p>
<p>"You can pick which element you want to study in a given sample and even within a molecule," he said.</p>
<p>With other two-pulse techniques, a timing jitter, or fluctuations, typically make it difficult to precisely space the pulses. With this new split-delay tool, the spacing between pulses "is almost jitter-free on a scale of even the shortest X-ray pulses," Murphy said.</p>
<p>Currently installed at the <a href="https://portal.slac.stanford.edu/sites/lcls_public/instruments/amo/Pages/default.aspx">Atomic, Molecular and Optical Science (AMO)</a> experimental station at LCLS, the new tool is transportable and can be moved to a neighboring <a href="https://portal.slac.stanford.edu/sites/lcls_public/instruments/SXR/Pages/default.aspx">soft X-ray experimental station</a>.</p>
<p>The system was funded through a Single Individual and Small Group Research grant (SISGR) awarded to Western Michigan University by the U.S. Department of Energy Basic Energy Sciences Division of Chemical Sciences, Geosciences and Energy Biosciences, and was also paid for with LCLS funds.</p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>A new tool at SLAC\'s Linac Coherent Light Source splits individual X-ray laser pulses into two pulses that can hit a target one right after another with precisely controlled timing, allowing scientists to trigger and measure specific ultrafast changes in atoms and molecules.</p>

<table style="height: 129px; background-color: #ffffff; border: 5px solid #ffffff;" border="5" cellspacing="1" cellpadding="5" width="133" align="left"><tbody><tr><td><a title="Photo - Soft X-ray split-and-delay system" href="https://news.slac.stanford.edu/sites/default/files/images/image/13-07-29-splitdelay-990b.jpg" target="_blank"><img title="Soft X-ray Split-and-delay System" src="https://news.slac.stanford.edu/sites/default/files/images/image/13-07-29-splitdelay-990b.jpg" alt="" width="350" /></a><br /><strong><span style="font-size: x-small;">(<a title="Soft X-ray split-and-delay system" href="https://news.slac.stanford.edu/sites/default/files/images/image/13-07-29-splitdelay-990b.jpg" target="_blank">Click to view larger image.</a>) This soft X-ray split-and-delay system divides individual X-ray laser pulses into two separate, closely spaced pulses at SLAC\'s LCLS. </span></strong><span style="font-size: x-small;"> <em>(Matt Beardsley/SLAC)</em></span></td>
</tr></tbody></table><p>Built through a collaboration of SLAC and Western Michigan University and installed in May, the system controls the tilt and height of two silicon mirrors to split the pulses and vary their arrival times by up to 200 femtoseconds, or quadrillionths of a second, with a timing accuracy down to a fraction of a femtosecond.</p>
<p>The <a href="http://iopscience.iop.org/1742-6596/425/15/152021">soft X-ray split-and-delay tool</a> has already been put to use in two experiments at LCLS.</p>
<p>"It\'s working even better than designed," said Brendan Murphy, a postdoctoral research associate at Western Michigan University who played a leading role in the system\'s development. "With these first experiments we\'ve established that this is an effective tool that offers unique strengths over other approaches."</p>
<p>Nora Berrah of Western Michigan University, who has led <a href="http://home.slac.stanford.edu/pressreleases/2010/20100630.htm" target="_blank">pioneering experiments</a> at LCLS, worked with John Bozek, a staff scientist who manages the LCLS Soft X-ray Department, to oversee the development of the split-and-delay system. Berrah said the split-and-delay tool can be used to study and refine the timeline of fundamental processes in molecules and atoms, such as the creation of highly charged states, and explore the rearrangement of an atom\'s innermost electrons.</p>
<table style="height: 129px; background-color: #ffffff; border: 5px solid #ffffff;" border="5" cellspacing="1" cellpadding="5" width="133" align="left"><tbody><tr><td>
<object width="596" height="335">
<param name="movie" value="//www.youtube.com/v/L0BOZ4djafM?hl=en_US&amp;version=3&amp;rel=0" /><param name="allowFullScreen" value="true" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" width="596" height="335" src="//www.youtube.com/v/L0BOZ4djafM?hl=en_US&amp;version=3&amp;rel=0" allowscriptaccess="always" allowfullscreen="true"></embed></object><p><br /><span style="font-size: x-small;"><span style="color: #000000;"><strong>Brendan Murphy of Western Michigan University discusses the soft X-ray split-and-delay tool installed at SLAC.</strong></span> <em>(SLAC Multimedia Communications)</em></span></p></td>
</tr></tbody></table><p>In the first experiment using the system, a research team led by Berrah and Murphy measured the possible fundamental mechanisms for radiation damage in a large molecule to model damage in biomolecules. "We were watching how a big molecule falls apart after radiation damage," Berrah said, in order to understand how to best minimize this damage.</p>
<p>While there are already <a href="http://www6.slac.stanford.edu/news/2013-03-26-two-color.aspx">techniques</a> and <a href="http://www6.slac.stanford.edu/news/2013-03-12-X-ray-beam-sharing.aspx">tools</a> to divide X-ray pulses and produce closely spaced pulses, as well as several more in development for use at LCLS and other X-ray lasers, the new system is distinguished by its precise timing and the ability to measure the energy of every pulse. The first pulse "pumps" energy into the sample to create a specific response, and the following pulse probes and measures the resulting changes at a specific point in time. The energy signatures of the pump and probe pulses allow researchers to measure and interpret their effects on the sample.</p>
<p>Working in the soft X-ray range, this new system can be used to excite changes in atoms of a specific element, said Murphy, who is a part of Berrah\'s research group.</p>
<p>"You can pick which element you want to study in a given sample and even within a molecule," he said.</p>
<p>With other two-pulse techniques, a timing jitter, or fluctuations, typically make it difficult to precisely space the pulses. With this new split-delay tool, the spacing between pulses "is almost jitter-free on a scale of even the shortest X-ray pulses," Murphy said.</p>
<p>Currently installed at the <a href="https://portal.slac.stanford.edu/sites/lcls_public/instruments/amo/Pages/default.aspx">Atomic, Molecular and Optical Science (AMO)</a> experimental station at LCLS, the new tool is transportable and can be moved to a neighboring <a href="https://portal.slac.stanford.edu/sites/lcls_public/instruments/SXR/Pages/default.aspx">soft X-ray experimental station</a>.</p>
<p>The system was funded through a Single Individual and Small Group Research grant (SISGR) awarded to Western Michigan University by the U.S. Department of Energy Basic Energy Sciences Division of Chemical Sciences, Geosciences and Energy Biosciences, and was also paid for with LCLS funds.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_link' => array(),
  'field_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 27,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_news_category' => array(
    'und' => array(
      0 => array(
        'tid' => 20,
        'uuid' => 'eebfd8ab-8943-4b70-aeb1-a6ed3ba11e3d',
      ),
    ),
  ),
  'field_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-08-08 13:45:00',
        'timezone' => 'Europe/Helsinki',
        'timezone_db' => 'UTC',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'field_contact_information' => array(),
  'field_citation' => array(),
  'field_news_tags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 0,
  'data' => 'b:0;',
  'date' => '2013-08-08 16:49:38 +0300',
);
  return $nodes;
}
