<?php
/**
 * @file
 * slac_news_demo.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function slac_news_demo_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'title' => 'World\'s Most Powerful X-ray Laser Beam Refined to Scalpel Precision',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8db32f11-0ae0-42fd-9e69-cbcef31ed24e',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1350157617,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2cca6331-8a1b-0b97-b003-2f69ec11e8ca',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><strong>Menlo Park, Calif.&nbsp;</strong>&mdash; With a thin sliver of diamond, scientists at the U.S. Department of Energy&rsquo;s (DOE) SLAC National Accelerator Laboratory have transformed the&nbsp;<a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a>&nbsp;into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>

  <p>In a process called &ldquo;self-seeding,&rdquo; the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>

  <p>&ldquo;The more control you have, the finer the details you can see,&rdquo; said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. &ldquo;People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.&rdquo; Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>

  <p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>

  <p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>

  <p>Without self-seeding these X-ray laser pulses contain&nbsp;<a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a>&nbsp;(or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>

  <p>To create a precise X-ray wavelength band and make the LCLS even more &ldquo;laser-like,&rdquo; researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>

  <p>Producing the narrower wavelength band is just the beginning. &ldquo;The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators,&quot; said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>

  <p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>

  <p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>

  <p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, &ldquo;the entire group of observers was smiling from ear to ear.&quot; Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, &quot;I was very happy to see it work.&quot;</p>

  <p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE&rsquo;s Office of Science.</p>
  ',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><strong>Menlo Park, Calif. </strong>— With a thin sliver of diamond, scientists at the U.S. Department of Energy’s (DOE) SLAC National Accelerator Laboratory have transformed the <a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a> into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>
<p>In a process called “self-seeding,” the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>
<p>“The more control you have, the finer the details you can see,” said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. “People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.” Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>
<p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>
<p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>
<p>Without self-seeding these X-ray laser pulses contain <a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a> (or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>
<p>To create a precise X-ray wavelength band and make the LCLS even more “laser-like,” researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>
<p>Producing the narrower wavelength band is just the beginning. “The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators," said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>
<p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>
<p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>
<p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, “the entire group of observers was smiling from ear to ear." Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, "I was very happy to see it work."</p>
<p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE’s Office of Science.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
        'format' => NULL,
        'safe_value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 2,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
        'title' => 'Nature Photonics',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 68,
        'uuid' => '0ce6dd19-dde1-4daa-ae83-1879947970ac',
      ),
      1 => array(
        'tid' => 70,
        'uuid' => '98be32f4-4f1a-4cbc-98be-01c4fc935bf8',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 28,
        'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-12-02 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-10-13 13:46:57 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Stanford, SLAC researchers demonstrate \'accelerator on a chip\'',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8db32f11-8ae0-42fd-9e69-cbcef31ed24e',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1348256817,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2cca6331-8a1b-4b97-b003-2f69ec11e8ca',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>The tiny new technology could spawn new generations of smaller, less expensive devices for science and medicine.</p>

<p>The nanostructured glass chip is smaller than a grain of rice.<br>
	In an advance that could dramatically shrink particle accelerators for science and medicine, researchers used a laser to accelerate electrons at a rate 10 times higher than conventional technology in a nanostructured glass chip smaller than a grain of rice.</p>

<p>The achievement was reported today in the journal Nature by a team including scientists from the U.S. Department of Energy&#39;s SLAC National Accelerator Laboratory and Stanford University.</p>

<p>&quot;We still have a number of challenges before this technology becomes practical for real-world use, but eventually it would substantially reduce the size and cost of future high-energy particle colliders for exploring the world of fundamental particles and forces,&quot; said Joel England, the SLAC physicist who led the experiments.</p>

<p>&quot;It could also help enable compact accelerators and X-ray devices for security scanning, medical therapy and imaging, and research in biology and materials science.&quot;</p>

<p>Because it employs commercial lasers and low-cost, mass-production techniques, the researchers believe it will set the stage for new generations of &quot;tabletop&quot; accelerators.</p>

<p>At its full potential, the new &quot;accelerator on a chip&quot; could match the accelerating power of SLAC&#39;s 2-mile-long linear accelerator in just 100 feet, and deliver a million more electron pulses per second.</p>

<p>This initial demonstration achieved an acceleration gradient, or amount of energy gained per length of the accelerator, of 300 million electronvolts per meter. That&#39;s roughly 10 times the acceleration provided by the current SLAC linear accelerator.</p>

<p>&quot;Our ultimate goal for this structure is one billion electronvolts per meter, and we&#39;re already one-third of the way in our first experiment,&quot; said Stanford applied physics Professor Robert Byer, the principal investigator for this research.</p>

<p>Today&#39;s accelerators use microwaves to boost the energy of electrons. Researchers have been looking for more economical alternatives, and this new technique, which uses ultrafast lasers to drive the accelerator, is a leading candidate.</p>

<p>Particles are generally accelerated in two stages. First they are boosted to nearly the speed of light. Then any additional acceleration increases their energy, but not their speed; this is the challenging part.</p>

<p>In the accelerator-on-a-chip experiments, electrons are first accelerated to near light-speed in a conventional accelerator. Then they are focused into a tiny, half-micron-high channel within a glass chip just half a millimeter long. The channel had earlier been patterned with precisely spaced nanoscale ridges. Infrared laser light shining on the pattern generates electrical fields that interact with the electrons in the channel to boost their energy. (View animation for more detail.)</p>

<p>Turning the accelerator on a chip into a full-fledged tabletop accelerator will require a more compact way to get the electrons up to speed before they enter the device.</p>

<p>A collaborating research group in Germany, led by Peter Hommelhoff at Friedrich Alexander University and the Max Planck Institute of Quantum Optics, has been looking for such a solution. It simultaneously reports in Physical Review Letters its success in using a laser to accelerate lower-energy electrons.</p>

<p>Applications for these new particle accelerators would go well beyond particle physics research. Byer said laser accelerators could drive compact X-ray free-electron lasers, comparable to SLAC&#39;s Linac Coherent Light Source, that are all-purpose tools for a wide range of research.</p>

<p>Another possible application is small, portable X-ray sources to improve medical care for people injured in combat, as well as to provide more affordable medical imaging for hospitals and laboratories. That&#39;s one of the goals of the Defense Advanced Research Projects Agency&#39;s Advanced X-Ray Integrated Sources program, which partially funded this research. Primary funding for this research is from the U.S. Department of Energy Office of Science.</p>

<p>The study&#39;s lead authors were Stanford graduate students Edgar Peralta and Ken Soong. Peralta created the patterned fused silica chips in the Stanford Nanofabrication Facility. Soong implemented the high-precision laser optics for the experiment at SLAC&#39;s Next Linear Collider Test Accelerator. Additional contributors included researchers from the University of California-Los Angeles and Tech-X Corp. in Boulder, Colo.</p>

<p>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>The tiny new technology could spawn new generations of smaller, less expensive devices for science and medicine.</p>
<p>The nanostructured glass chip is smaller than a grain of rice.<br /><br />
	In an advance that could dramatically shrink particle accelerators for science and medicine, researchers used a laser to accelerate electrons at a rate 10 times higher than conventional technology in a nanostructured glass chip smaller than a grain of rice.</p>
<p>The achievement was reported today in the journal Nature by a team including scientists from the U.S. Department of Energy\'s SLAC National Accelerator Laboratory and Stanford University.</p>
<p>"We still have a number of challenges before this technology becomes practical for real-world use, but eventually it would substantially reduce the size and cost of future high-energy particle colliders for exploring the world of fundamental particles and forces," said Joel England, the SLAC physicist who led the experiments.</p>
<p>"It could also help enable compact accelerators and X-ray devices for security scanning, medical therapy and imaging, and research in biology and materials science."</p>
<p>Because it employs commercial lasers and low-cost, mass-production techniques, the researchers believe it will set the stage for new generations of "tabletop" accelerators.</p>
<p>At its full potential, the new "accelerator on a chip" could match the accelerating power of SLAC\'s 2-mile-long linear accelerator in just 100 feet, and deliver a million more electron pulses per second.</p>
<p>This initial demonstration achieved an acceleration gradient, or amount of energy gained per length of the accelerator, of 300 million electronvolts per meter. That\'s roughly 10 times the acceleration provided by the current SLAC linear accelerator.</p>
<p>"Our ultimate goal for this structure is one billion electronvolts per meter, and we\'re already one-third of the way in our first experiment," said Stanford applied physics Professor Robert Byer, the principal investigator for this research.</p>
<p>Today\'s accelerators use microwaves to boost the energy of electrons. Researchers have been looking for more economical alternatives, and this new technique, which uses ultrafast lasers to drive the accelerator, is a leading candidate.</p>
<p>Particles are generally accelerated in two stages. First they are boosted to nearly the speed of light. Then any additional acceleration increases their energy, but not their speed; this is the challenging part.</p>
<p>In the accelerator-on-a-chip experiments, electrons are first accelerated to near light-speed in a conventional accelerator. Then they are focused into a tiny, half-micron-high channel within a glass chip just half a millimeter long. The channel had earlier been patterned with precisely spaced nanoscale ridges. Infrared laser light shining on the pattern generates electrical fields that interact with the electrons in the channel to boost their energy. (View animation for more detail.)</p>
<p>Turning the accelerator on a chip into a full-fledged tabletop accelerator will require a more compact way to get the electrons up to speed before they enter the device.</p>
<p>A collaborating research group in Germany, led by Peter Hommelhoff at Friedrich Alexander University and the Max Planck Institute of Quantum Optics, has been looking for such a solution. It simultaneously reports in Physical Review Letters its success in using a laser to accelerate lower-energy electrons.</p>
<p>Applications for these new particle accelerators would go well beyond particle physics research. Byer said laser accelerators could drive compact X-ray free-electron lasers, comparable to SLAC\'s Linac Coherent Light Source, that are all-purpose tools for a wide range of research.</p>
<p>Another possible application is small, portable X-ray sources to improve medical care for people injured in combat, as well as to provide more affordable medical imaging for hospitals and laboratories. That\'s one of the goals of the Defense Advanced Research Projects Agency\'s Advanced X-Ray Integrated Sources program, which partially funded this research. Primary funding for this research is from the U.S. Department of Energy Office of Science.</p>
<p>The study\'s lead authors were Stanford graduate students Edgar Peralta and Ken Soong. Peralta created the patterned fused silica chips in the Stanford Nanofabrication Facility. Soong implemented the high-precision laser optics for the experiment at SLAC\'s Next Linear Collider Test Accelerator. Additional contributors included researchers from the University of California-Los Angeles and Tech-X Corp. in Boulder, Colo.</p>
<p>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
        'format' => NULL,
        'safe_value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 2,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
        'title' => 'Nature Photonics',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 68,
        'uuid' => '0ce6dd19-dde1-4daa-ae83-1879947970ac',
      ),
      1 => array(
        'tid' => 70,
        'uuid' => '98be32f4-4f1a-4cbc-98be-01c4fc935bf8',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 28,
        'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2014-02-02 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-09-21 13:46:57 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'X-ray Laser Probes Biomolecules to Individual Atoms',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8db32f61-8ae0-42fd-9e69-cbcef31ed24e',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1348516017,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2cca6331-8a7b-4b97-b003-2f69ec11e8ca',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>An international team led by the U.S. Department of Energy&#39;s (DOE) SLAC National Accelerator Laboratory has proved how the world&#39;s most powerful X-ray laser can assist in cracking the structures of biomolecules, and in the processes helped to pioneer critical new investigative avenues in biology.</p>

<p>The team&#39;s experiments, reported this week in Science, used SLAC&rsquo;s Linac Coherent Light Source (LCLS) to obtain ultra-high-resolution views of crystallized biomolecules, including a small protein found in egg whites called lysozyme.</p>

<p>For decades, scientists have reconstructed the shape of biological molecules and proteins by illuminating crystallized samples with X-rays to study how they scatter the light. The team&#39;s work with lysozyme represents the first-ever high-resolution experiments using serial femtosecond crystallography -- the split-second imaging of tiny crystals using ultrashort, ultrabright X-ray laser pulses (a femtosecond is one quadrillionth of a second).</p>

<p>The technique utilized a higher resolution than previously achieved using X-ray lasers, allowing scientists to use smaller crystals than typical with other methods, and could also enable researchers to view molecular dynamics in a way never before possible.</p>

<p>&ldquo;We were able to actually visualize the structure of the molecule at a resolution so high we start to infer the position of individual atoms,&rdquo; said Sébastien Boutet, a staff scientist at LCLS who led the research.</p>

<p>&ldquo;Not only that, but the structure we observed matches the known structure of lysozyme and shows no significant sign of radiation damage, despite the fact that the pulses completely destroy the sample. This is the first high-resolution demonstration of the &lsquo;diffraction-before-destruction&rsquo; technique on biological samples, where we&rsquo;re able to measure a sample before the powerful pulses of the LCLS damage it,&rdquo; he added.</p>

<p>The team chose lysozyme as the first sample for their research because it is easy to crystallize and has been extensively studied. Their work not only determined lysozyme&rsquo;s structure at such high resolution that it showed individual amino acids, but also proved the ability to use extremely small crystals for a range of applications. Boutet says the team has also studied more complex proteins and systems that they are analyzing now.</p>

<p>Ultimately, scientists using LCLS are driving toward an atomic- and molecular-scale understanding of complex biological systems -- such as the membrane proteins that are critical in cell functions and the mechanisms that power photosynthesis -- which could lead to discoveries in a range of sciences, from pharmaceutical breakthroughs to new sources of alternative energy.</p>

<p>The experiment was the first study performed on the new Coherent X-ray Imaging (CXI) instrument, a &ldquo;molecular camera&rdquo; designed, built and commissioned by SLAC and now available to the scientific community. Also key to the study was a novel custom-made detector, the Cornell-SLAC Pixel Array Detector (CSPAD), developed in collaboration between Cornell University and SLAC for use at the CXI instrument.<br>
	&quot;This important demonstration shows that the technique works, and it paves the way for a lot of exciting experiments to come,&quot; says Boutet.</p>

<p>Members of the international team included researchers from Max Planck Institutes, DESY, Arizona State University, Cornell University, SUNY Oswego, The Johns Hopkins University Applied Physics Laboratory, the Nikhef National Institute for Subatomic Physics, the European Synchrotron Radiation Facility, the University of Gothenburg, the University of Hamburg, the University of Lübeck and Uppsala University.</p>

<p>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science. To learn more, please visit www.slac.stanford.edu.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>An international team led by the U.S. Department of Energy\'s (DOE) SLAC National Accelerator Laboratory has proved how the world\'s most powerful X-ray laser can assist in cracking the structures of biomolecules, and in the processes helped to pioneer critical new investigative avenues in biology.</p>
<p>The team\'s experiments, reported this week in Science, used SLAC’s Linac Coherent Light Source (LCLS) to obtain ultra-high-resolution views of crystallized biomolecules, including a small protein found in egg whites called lysozyme.</p>
<p>For decades, scientists have reconstructed the shape of biological molecules and proteins by illuminating crystallized samples with X-rays to study how they scatter the light. The team\'s work with lysozyme represents the first-ever high-resolution experiments using serial femtosecond crystallography -- the split-second imaging of tiny crystals using ultrashort, ultrabright X-ray laser pulses (a femtosecond is one quadrillionth of a second).</p>
<p>The technique utilized a higher resolution than previously achieved using X-ray lasers, allowing scientists to use smaller crystals than typical with other methods, and could also enable researchers to view molecular dynamics in a way never before possible.</p>
<p>“We were able to actually visualize the structure of the molecule at a resolution so high we start to infer the position of individual atoms,” said Sébastien Boutet, a staff scientist at LCLS who led the research.</p>
<p>“Not only that, but the structure we observed matches the known structure of lysozyme and shows no significant sign of radiation damage, despite the fact that the pulses completely destroy the sample. This is the first high-resolution demonstration of the ‘diffraction-before-destruction’ technique on biological samples, where we’re able to measure a sample before the powerful pulses of the LCLS damage it,” he added.</p>
<p>The team chose lysozyme as the first sample for their research because it is easy to crystallize and has been extensively studied. Their work not only determined lysozyme’s structure at such high resolution that it showed individual amino acids, but also proved the ability to use extremely small crystals for a range of applications. Boutet says the team has also studied more complex proteins and systems that they are analyzing now.</p>
<p>Ultimately, scientists using LCLS are driving toward an atomic- and molecular-scale understanding of complex biological systems -- such as the membrane proteins that are critical in cell functions and the mechanisms that power photosynthesis -- which could lead to discoveries in a range of sciences, from pharmaceutical breakthroughs to new sources of alternative energy.</p>
<p>The experiment was the first study performed on the new Coherent X-ray Imaging (CXI) instrument, a “molecular camera” designed, built and commissioned by SLAC and now available to the scientific community. Also key to the study was a novel custom-made detector, the Cornell-SLAC Pixel Array Detector (CSPAD), developed in collaboration between Cornell University and SLAC for use at the CXI instrument.<br /><br />
	"This important demonstration shows that the technique works, and it paves the way for a lot of exciting experiments to come," says Boutet.</p>
<p>Members of the international team included researchers from Max Planck Institutes, DESY, Arizona State University, Cornell University, SUNY Oswego, The Johns Hopkins University Applied Physics Laboratory, the Nikhef National Institute for Subatomic Physics, the European Synchrotron Radiation Facility, the University of Gothenburg, the University of Hamburg, the University of Lübeck and Uppsala University.</p>
<p>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science. To learn more, please visit <a href="http://www.slac.stanford.edu">www.slac.stanford.edu</a>.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
        'format' => NULL,
        'safe_value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 2,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
        'title' => 'Nature Photonics',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 68,
        'uuid' => '0ce6dd19-dde1-4daa-ae83-1879947970ac',
      ),
      1 => array(
        'tid' => 70,
        'uuid' => '98be32f4-4f1a-4cbc-98be-01c4fc935bf8',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 28,
        'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-11-12 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-09-24 13:46:57 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Stanford scientists build a \'brain stethoscope\' to turn seizures into music',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8db12f61-7ae0-42fd-9e69-cbcef31ed24e',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1348602417,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2cca6931-0a7b-4b97-b003-2f69ec11e8ca',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>When Chris Chafe and Josef Parvizi began transforming recordings of brain activity into music, they did so with artistic aspirations. The professors soon realized, though, that the work could lead to a powerful biofeedback tool for identifying brain patterns associated with seizures.&nbsp;</p>

<p>Josef Parvizi was enjoying a performance by the Kronos Quartet when the idea struck. The musical troupe was midway through a piece in which the melodies were based on radio signals from outer space, and Parvizi, a neurologist at Stanford Medical Center, began wondering what the brain&#39;s electrical activity might sound like set to music.</p>

<p>He didn&#39;t have to look far for help. Chris Chafe, a professor of music research at Stanford, is one of the world&#39;s foremost experts in &quot;musification,&quot; the process of converting natural signals into music. One of his previous works involved measuring the changing carbon dioxide levels near ripening tomatoes and converting those changing levels into electronic performances.</p>

<p>Parvizi, an associate professor, specializes in treating patients suffering from intractable seizures. To locate the source of a seizure, he places electrodes in patients&#39; brains to create electroencephalogram (EEG) recordings of both normal brain activity and a seizure state.</p>

<p>He shared a consenting patient&#39;s EEG data with Chafe, who began setting the electrical spikes of the rapidly firing neurons to music. Chafe used a tone close to a human&#39;s voice, in hopes of giving the listener an empathetic and intuitive understanding of the neural activity.</p>

<p>Upon a first listen, the duo realized they had done more than create an interesting piece of music. [Listen to the audio here]</p>

<p>&quot;My initial interest was an artistic one at heart, but, surprisingly, we could instantly differentiate seizure activity from non-seizure states with just our ears,&quot; Chafe said. &quot;It was like turning a radio dial from a static-filled station to a clear one.&quot;</p>

<p>If they could achieve the same result with real-time brain activity data, they might be able to develop a tool to allow caregivers for people with epilepsy to quickly listen to the patient&#39;s brain waves to hear whether an undetected seizure might be occurring.</p>

<p>Parvizi and Chafe dubbed the device a &quot;brain stethoscope.&quot;</p>

<p>The sound of a seizure</p>

<p>The EEGs Parvizi conducts register brain activity from more than 100 electrodes placed inside the brain; Chafe selects certain electrode/neuron pairings and allows them to modulate notes sung by a female singer. As the electrode captures increased activity, it changes the pitch and inflection of the singer&#39;s voice.</p>

<p>Before the seizure begins &ndash; during the so-called pre-ictal stage &ndash; the peeps and pops from each &quot;singer&quot; almost synchronize and fall into a clear rhythm, as if they&#39;re following a conductor, Chafe said.</p>

<p>In the moments leading up to the seizure event, though, each of the singers begins to improvise. The notes become progressively louder and more scattered, as the full seizure event occurs (the ictal state). The way Chafe has orchestrated his singers, one can hear the electrical storm originate on one side of the brain and eventually cross over into the other hemisphere, creating a sort of sing-off between the two sides of the brain.</p>

<p>After about 30 seconds of full-on chaos, the singers begin to calm, trailing off into their post-ictal rhythm. Occasionally, one or two will pipe up erratically, but on the whole, the choir sounds extremely fatigued.</p>

<p>It&#39;s the perfect representation of the three phases of a seizure event, Parvizi said.</p>

<p>Part art exhibit, part experiment</p>

<p>Caring for a person with seizures can be very difficult, as not all seizure activity manifests itself with behavioral cues. It&#39;s often impossible to know whether a person with epilepsy is acting confused because they are having a seizure, or if they are experiencing the type of confusion that is a marker of the post-ictal seizure phase.</p>

<p>To that end, Parvizi and Chafe hope to apply their work to develop a device that listens for the telltale brain patterns of an ongoing seizure or a post-ictal fatigued brain state.</p>

<p>&quot;Someone &ndash; perhaps a mother caring for a child &ndash; who hasn&#39;t received training in interpreting visual EEGs can hear the seizure rhythms and easily appreciate that there is a pathological brain phenomenon taking place,&quot; Parvizi said.</p>

<p>The device can also offer biofeedback to non-epileptic patients who want to hear the music their own brain waves create.</p>

<p>The effort to build this device is funded by Stanford&#39;s Bio-X Interdisciplinary Initiatives Program (Bio-X IIP), which provides money for &nbsp;interdisciplinary projects that have potential to improve human health in innovative ways. Bio-X seed grants have funded 141 research collaborations connecting hundreds of faculty since 2000. The proof-of-concept projects have produced hundreds of publications, dozens of patents, and more than a tenfold return on research funds to Stanford.</p>

<p>From a clinical perspective, the work is still very experimental.</p>

<p>&quot;We&#39;ve really just stuck our finger in there,&quot; Chafe said. &quot;We know that the music is fascinating and that we can hear important dynamics, but there are still wonderful revelations to be made.&quot;</p>

<p>Next year, Chafe and Parvizi plan to unveil a version of the system at Stanford&#39;s Cantor Arts Center. Visitors will don a headset that will transmit an EEG of their brain activity to their handheld device, which will convert it into music in real time.</p>

<p>&quot;This is what I like about Stanford,&quot; Parvizi said. &quot;It nurtures collaboration between fields that are seemingly light-years apart &nbsp;&ndash; we&#39;re neurology and music professors! &ndash; and our work together will hopefully make a positive impact on the world we live in.&quot;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>When Chris Chafe and Josef Parvizi began transforming recordings of brain activity into music, they did so with artistic aspirations. The professors soon realized, though, that the work could lead to a powerful biofeedback tool for identifying brain patterns associated with seizures. </p>
<p>Josef Parvizi was enjoying a performance by the Kronos Quartet when the idea struck. The musical troupe was midway through a piece in which the melodies were based on radio signals from outer space, and Parvizi, a neurologist at Stanford Medical Center, began wondering what the brain\'s electrical activity might sound like set to music.</p>
<p>He didn\'t have to look far for help. Chris Chafe, a professor of music research at Stanford, is one of the world\'s foremost experts in "musification," the process of converting natural signals into music. One of his previous works involved measuring the changing carbon dioxide levels near ripening tomatoes and converting those changing levels into electronic performances.</p>
<p>Parvizi, an associate professor, specializes in treating patients suffering from intractable seizures. To locate the source of a seizure, he places electrodes in patients\' brains to create electroencephalogram (EEG) recordings of both normal brain activity and a seizure state.</p>
<p>He shared a consenting patient\'s EEG data with Chafe, who began setting the electrical spikes of the rapidly firing neurons to music. Chafe used a tone close to a human\'s voice, in hopes of giving the listener an empathetic and intuitive understanding of the neural activity.</p>
<p>Upon a first listen, the duo realized they had done more than create an interesting piece of music. [Listen to the audio here]</p>
<p>"My initial interest was an artistic one at heart, but, surprisingly, we could instantly differentiate seizure activity from non-seizure states with just our ears," Chafe said. "It was like turning a radio dial from a static-filled station to a clear one."</p>
<p>If they could achieve the same result with real-time brain activity data, they might be able to develop a tool to allow caregivers for people with epilepsy to quickly listen to the patient\'s brain waves to hear whether an undetected seizure might be occurring.</p>
<p>Parvizi and Chafe dubbed the device a "brain stethoscope."</p>
<p>The sound of a seizure</p>
<p>The EEGs Parvizi conducts register brain activity from more than 100 electrodes placed inside the brain; Chafe selects certain electrode/neuron pairings and allows them to modulate notes sung by a female singer. As the electrode captures increased activity, it changes the pitch and inflection of the singer\'s voice.</p>
<p>Before the seizure begins – during the so-called pre-ictal stage – the peeps and pops from each "singer" almost synchronize and fall into a clear rhythm, as if they\'re following a conductor, Chafe said.</p>
<p>In the moments leading up to the seizure event, though, each of the singers begins to improvise. The notes become progressively louder and more scattered, as the full seizure event occurs (the ictal state). The way Chafe has orchestrated his singers, one can hear the electrical storm originate on one side of the brain and eventually cross over into the other hemisphere, creating a sort of sing-off between the two sides of the brain.</p>
<p>After about 30 seconds of full-on chaos, the singers begin to calm, trailing off into their post-ictal rhythm. Occasionally, one or two will pipe up erratically, but on the whole, the choir sounds extremely fatigued.</p>
<p>It\'s the perfect representation of the three phases of a seizure event, Parvizi said.</p>
<p>Part art exhibit, part experiment</p>
<p>Caring for a person with seizures can be very difficult, as not all seizure activity manifests itself with behavioral cues. It\'s often impossible to know whether a person with epilepsy is acting confused because they are having a seizure, or if they are experiencing the type of confusion that is a marker of the post-ictal seizure phase.</p>
<p>To that end, Parvizi and Chafe hope to apply their work to develop a device that listens for the telltale brain patterns of an ongoing seizure or a post-ictal fatigued brain state.</p>
<p>"Someone – perhaps a mother caring for a child – who hasn\'t received training in interpreting visual EEGs can hear the seizure rhythms and easily appreciate that there is a pathological brain phenomenon taking place," Parvizi said.</p>
<p>The device can also offer biofeedback to non-epileptic patients who want to hear the music their own brain waves create.</p>
<p>The effort to build this device is funded by Stanford\'s Bio-X Interdisciplinary Initiatives Program (Bio-X IIP), which provides money for  interdisciplinary projects that have potential to improve human health in innovative ways. Bio-X seed grants have funded 141 research collaborations connecting hundreds of faculty since 2000. The proof-of-concept projects have produced hundreds of publications, dozens of patents, and more than a tenfold return on research funds to Stanford.</p>
<p>From a clinical perspective, the work is still very experimental.</p>
<p>"We\'ve really just stuck our finger in there," Chafe said. "We know that the music is fascinating and that we can hear important dynamics, but there are still wonderful revelations to be made."</p>
<p>Next year, Chafe and Parvizi plan to unveil a version of the system at Stanford\'s Cantor Arts Center. Visitors will don a headset that will transmit an EEG of their brain activity to their handheld device, which will convert it into music in real time.</p>
<p>"This is what I like about Stanford," Parvizi said. "It nurtures collaboration between fields that are seemingly light-years apart  – we\'re neurology and music professors! – and our work together will hopefully make a positive impact on the world we live in."</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Andy Freeberg, Media Relations Manager
SLAC National Accelerator Laboratory
Office: 650-926-4359
afreeberg@slac.stanford.edu',
        'format' => NULL,
        'safe_value' => 'Andy Freeberg, Media Relations Manager
SLAC National Accelerator Laboratory
Office: 650-926-4359
afreeberg@slac.stanford.edu',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 2,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
        'title' => 'Nature Photonics',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 68,
        'uuid' => '0ce6dd19-dde1-4daa-ae83-1879947970ac',
      ),
      1 => array(
        'tid' => 70,
        'uuid' => '98be32f4-4f1a-4cbc-98be-01c4fc935bf8',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 28,
        'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2014-01-05 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-09-25 13:46:57 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'To encourage green living, Stanford students build a better light switch',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8db12f61-8ae0-42fd-9e69-cbcef31ed24e',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1348170417,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2cca6931-8a7b-4b97-b003-2f69ec11e8ca',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>People are more likely to conserve energy if it&#39;s easy to do. Knowing this, the students working on Stanford&#39;s entry in the Solar Decathlon green-building competition have redesigned household mainstays to make reducing energy and water consumption a cinch.</p>

<p>When Stanford students began designing their entry into the Solar Decathlon green-building competition, they wanted to do two things: make the most energy-efficient house possible, and encourage people to make conscious decisions about their energy consumption.</p>

<p>That&#39;s why when you switch off the light in the Start.Home, you do so by swiping your fingers across a glowing touchpad.</p>

<p>The redesigned light switch was born from a brainstorming session on how to eliminate excess energy consumption throughout the house. The students zeroed in on two common culprits: people leaving lights on in empty rooms, and so-called vampire power, the small amount of electricity that electronics pull from the socket even when they&#39;ve been switched &quot;off.&quot;</p>

<p>The design team approached the task of making the Start.Home more energy efficient knowing that the most energy-efficient option should require the least amount of effort, said Jason Bade, &#39;13, who leads the project&#39;s interaction design team. Crawling under cabinets to unplug appliances or switching off each lamp in a room is the energy-responsible thing to do, but it&#39;s too much of a hassle to become a consistent behavior.</p>

<p>An easy and effective solution would have been to connect all the lights and outlets to an automatic motion sensor that shuts everything off when a person leaves the room, Bade said. But installing such a sensor is a one-time decision that the homeowner makes to be energy conscious, and has limited impact on encouraging people to make better energy decisions. It places control in the technology, not the person.</p>

<p>&quot;What happens if the system breaks, or what happens if you&#39;re in a house or office building that doesn&#39;t have the same design features?&quot; Bade said. &quot;We want to give people a sense of understanding of their energy consumption, and to empower them to make better energy behaviors because they want to. If they actively reduce their energy consumption in the house, then hopefully they&#39;ll behave that way in the rest of the world too.&quot;</p>

<p>The Start.Home features a custom-made &quot;room switch.&quot; As you leave a room, a touchpad mounted near the doorway will gently glow to remind you to turn off lights and unnecessary outlets. The switch operates much like a touchpad mouse on a laptop computer, and various tap or swipe sequences can issue different commands to turn off some or all electricity to a room.</p>

<p>The design group applied the same design philosophy when designing another type of switch. People waste a huge amount of water by leaving the bathroom sink running while they brush their teeth or shave. The Start.Home&#39;s solution is a knee-operated switch built into the sink cabinet. Simply lean against it, and water flows as you need it; remove pressure, and the water stops.</p>

<p>&quot;We&#39;re redesigning things that have been around for a hundred years,&quot; Bade said. &quot;To get people to adopt this, we had to also design them to be better than what we&#39;re used to.&quot;</p>

<p>So far, focus groups have responded well to prototypes of both devices, and the students calculate that the devices will make significant energy and water savings over the long haul.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>People are more likely to conserve energy if it\'s easy to do. Knowing this, the students working on Stanford\'s entry in the Solar Decathlon green-building competition have redesigned household mainstays to make reducing energy and water consumption a cinch.</p>
<p>When Stanford students began designing their entry into the Solar Decathlon green-building competition, they wanted to do two things: make the most energy-efficient house possible, and encourage people to make conscious decisions about their energy consumption.</p>
<p>That\'s why when you switch off the light in the Start.Home, you do so by swiping your fingers across a glowing touchpad.</p>
<p>The redesigned light switch was born from a brainstorming session on how to eliminate excess energy consumption throughout the house. The students zeroed in on two common culprits: people leaving lights on in empty rooms, and so-called vampire power, the small amount of electricity that electronics pull from the socket even when they\'ve been switched "off."</p>
<p>The design team approached the task of making the Start.Home more energy efficient knowing that the most energy-efficient option should require the least amount of effort, said Jason Bade, \'13, who leads the project\'s interaction design team. Crawling under cabinets to unplug appliances or switching off each lamp in a room is the energy-responsible thing to do, but it\'s too much of a hassle to become a consistent behavior.</p>
<p>An easy and effective solution would have been to connect all the lights and outlets to an automatic motion sensor that shuts everything off when a person leaves the room, Bade said. But installing such a sensor is a one-time decision that the homeowner makes to be energy conscious, and has limited impact on encouraging people to make better energy decisions. It places control in the technology, not the person.</p>
<p>"What happens if the system breaks, or what happens if you\'re in a house or office building that doesn\'t have the same design features?" Bade said. "We want to give people a sense of understanding of their energy consumption, and to empower them to make better energy behaviors because they want to. If they actively reduce their energy consumption in the house, then hopefully they\'ll behave that way in the rest of the world too."</p>
<p>The Start.Home features a custom-made "room switch." As you leave a room, a touchpad mounted near the doorway will gently glow to remind you to turn off lights and unnecessary outlets. The switch operates much like a touchpad mouse on a laptop computer, and various tap or swipe sequences can issue different commands to turn off some or all electricity to a room.</p>
<p>The design group applied the same design philosophy when designing another type of switch. People waste a huge amount of water by leaving the bathroom sink running while they brush their teeth or shave. The Start.Home\'s solution is a knee-operated switch built into the sink cabinet. Simply lean against it, and water flows as you need it; remove pressure, and the water stops.</p>
<p>"We\'re redesigning things that have been around for a hundred years," Bade said. "To get people to adopt this, we had to also design them to be better than what we\'re used to."</p>
<p>So far, focus groups have responded well to prototypes of both devices, and the students calculate that the devices will make significant energy and water savings over the long haul.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
        'format' => NULL,
        'safe_value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 2,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
        'title' => 'Nature Photonics',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 69,
        'uuid' => '1aa88d95-a2ea-4001-978d-fcacdf96213e',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 28,
        'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2012-01-09 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-09-20 13:46:57 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Disorder can improve the performance of plastic solar cells, Stanford scientists say',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '1226bc1e-be2e-47b2-af31-9780bb060506',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1366055115,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '9r850fab-9ad9-45dc-9e52-9c4901fbad53',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>

  <p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers&#39; performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal&nbsp;<a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>

  <p>&quot;People used to think that if you made the polymers more like silicon they would perform better,&quot; said study co-author&nbsp;<a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. &quot;But we found that polymers don&#39;t naturally form nice, well-ordered crystals. They form small, disordered ones, and that&#39;s perfectly fine.&quot;</p>

  <p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>

  <h3><strong>Speedy electrons</strong></h3>

  <p><strong>&nbsp;</strong>In the study, the Stanford team focused on a class of organic materials known as&nbsp;<a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a>&nbsp;&ndash; chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>

  <p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren&#39;t buildings today covered with plastic solar cells?</p>

  <p>&quot;One reason they haven&#39;t been commercialized is because of poor performance,&quot; Salleo said. &quot;In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility.&quot;</p>

  <p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. &quot;Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor,&quot; Salleo said. &quot;Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones.&quot;</p>

  <h3><strong>X-ray analysis</strong></h3>

  <p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the&nbsp;<a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a>&nbsp;for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>

  <p>&quot;The crystals were so small and disordered you could barely infer their presence from X-rays,&quot; Salleo said. &quot;In fact, scientists had assumed they weren&#39;t there.&quot;</p>

  <p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>

  <p>&quot;Being small enables a charged electron to go through one crystal and rapidly move on to the next one,&quot; he said. &quot;The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals.&quot;</p>

  <p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>

  <p>&quot;Our conclusion is that you don&#39;t need to make something so rigid that it forms large crystals,&quot; Salleo said. &quot;You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>

  <p>&quot;In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn&#39;t know why they worked so well,&quot; he said. &quot;Now that they know, they can go out and design even better ones.&quot;</p>

  <p>And Salleo offered a final piece of advice. &quot;Try to design a material that can live with as much disorder as possible,&quot; he said. &quot;Take the disorder for granted. Personally, I really like disorder. Just look at my office.&quot;</p>

  <p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of&nbsp;<a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of&nbsp;<a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC&nbsp;<a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>

  <p>The study was supported by a Stanford&nbsp;<a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a>&nbsp;award from the King Abdullah University of Science and Technology; and by the&nbsp;<a href="http://erc.europa.eu/">European Research Council</a>.</p>
  ',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>
<p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers\' performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal <a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>
<p>"People used to think that if you made the polymers more like silicon they would perform better," said study co-author <a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. "But we found that polymers don\'t naturally form nice, well-ordered crystals. They form small, disordered ones, and that\'s perfectly fine."</p>
<p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>
<h3><strong>Speedy electrons</strong></h3>
<p><strong> </strong>In the study, the Stanford team focused on a class of organic materials known as <a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a> – chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>
<p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren\'t buildings today covered with plastic solar cells?</p>
<p>"One reason they haven\'t been commercialized is because of poor performance," Salleo said. "In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility."</p>
<p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. "Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor," Salleo said. "Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones."</p>
<h3><strong>X-ray analysis</strong></h3>
<p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the <a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a> for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>
<p>"The crystals were so small and disordered you could barely infer their presence from X-rays," Salleo said. "In fact, scientists had assumed they weren\'t there."</p>
<p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>
<p>"Being small enables a charged electron to go through one crystal and rapidly move on to the next one," he said. "The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals."</p>
<p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>
<p>"Our conclusion is that you don\'t need to make something so rigid that it forms large crystals," Salleo said. "You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>
<p>"In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn\'t know why they worked so well," he said. "Now that they know, they can go out and design even better ones."</p>
<p>And Salleo offered a final piece of advice. "Try to design a material that can live with as much disorder as possible," he said. "Take the disorder for granted. Personally, I really like disorder. Just look at my office."</p>
<p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of <a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of <a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC <a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>
<p>The study was supported by a Stanford <a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a> award from the King Abdullah University of Science and Technology; and by the <a href="http://erc.europa.eu/">European Research Council</a>.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 1,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
        'title' => 'Stanford Report',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 72,
        'uuid' => 'dad41187-6745-43bc-b95a-7851a7b2c825',
      ),
      1 => array(
        'tid' => 71,
        'uuid' => 'aaa4a1c8-fb65-4eeb-9bfe-909031f5e18b',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 29,
        'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-08-02 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2013-04-15 13:45:15 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Will 2-D Tin be the Next Super Material?',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'd56d508d-12ea-49c5-a7bf-ca78cf591bd6',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1354436526,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a2007803-a627-4cc4-9d06-51646486bbca',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><em>Menlo Park, Calif.</em> &mdash; A single layer of tin atoms could be the world&rsquo;s first material to conduct electricity with 100 percent efficiency at the temperatures that computer chips operate, according to a team of theoretical physicists led by researchers from the U.S. Department of Energy&rsquo;s (DOE) SLAC National Accelerator Laboratory and Stanford University.</p>

<p>Researchers call the new material &quot;stanene,&quot; combining the Latin name for tin (<em>stannum</em>) with the suffix used in graphene, another single-layer material whose novel electrical properties hold promise for a wide range of applications.</p>

<p>&quot;Stanene could increase the speed and lower the power needs of future generations of computer chips, if our prediction is confirmed by experiments that are underway in several laboratories around the world,&quot; said the team leader, Shoucheng Zhang, a physics professor at Stanford and the Stanford Institute for Materials and Energy Sciences (SIMES), a joint institute with SLAC. The team&rsquo;s work was <a href="http://prl.aps.org/abstract/PRL/v111/i13/e136804">published recently in <em>Physical Review Letters</em></a>.</p>

<p><strong>The Path to Stanene</strong></p>

<p>For the past decade, Zhang and colleagues have been calculating and predicting the electronic properties of a special class of materials known as topological insulators, which conduct electricity only on their outside edges or surfaces and not through their interiors. When topological insulators are just one atom thick, their edges conduct electricity with 100 percent efficiency. These unusual properties result from complex interactions between the electrons and nuclei of heavy atoms in the materials.</p>

<p>&ldquo;The magic of topological insulators is that by their very nature, they force electrons to move in defined lanes without any speed limit, like the German autobahn,&rdquo; Zhang said. &ldquo;As long as they&rsquo;re on the freeway &ndash; the edges or surfaces &ndash; the electrons will travel without resistance.&rdquo;</p>

<p>In 2006 and 2009, Zhang&rsquo;s group predicted that mercury telluride and several combinations of bismuth, antimony, selenium and tellurium should be topological insulators, and they were soon proven right in experiments performed by others. But none of those materials is a perfect conductor of electricity at room temperature, limiting their potential for commercial applications.</p>

<p>Earlier this year, visiting scientist Yong Xu, who is now at Tsinghua University in Beijing, collaborated with Zhang&rsquo;s group to consider the properties of a single layer of pure tin.</p>

<p><span>&ldquo;We knew we should be looking at elements in the lower-right portion of the periodic table,&rdquo; Xu said. &ldquo;All previous topological insulators have involved the heavy and electron-rich elements located there.&rdquo;</span></p>

<p>Their calculations indicated that a single layer of tin would be a topological insulator at and above room temperature, and that adding fluorine atoms to the tin would extend its operating range to at least 100 degrees Celsius (212 degrees Fahrenheit).</p>

<p><strong>Ultimately a Substitute for Silicon?</strong></p>

<p>Zhang said the first application for this stanene-fluorine combination could be in wiring that connects the many sections of a microprocessor, allowing electrons to flow as freely as cars on a highway. Traffic congestion would still occur at on- and off-ramps made of conventional conductors, he said. But stanene wiring should significantly reduce the power consumption and heat production of microprocessors.</p>

<p><span>Manufacturing challenges include ensuring that only a single layer of tin is deposited and keeping that single layer intact during high-temperature chip-making processes.</span></p>

<p>&ldquo;Eventually, we can imagine stanene being used for many more circuit structures, including replacing silicon in the hearts of transistors,&rdquo; Zhang said. &ldquo;Someday we might even call this area Tin Valley rather than Silicon Valley.&rdquo;</p>

<p>Additional contributors included researchers from Tsinghua University in Beijing and the Max Planck Institute for Chemical Physics of Solids in Dresden, Germany. The research was supported by the Mesodynamic Architectures program of the Defense Advanced Research Projects Agency.</p>

<p><em>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science. To learn more, please visit </em><a href="http://www.slac.stanford.edu"><em>www.slac.stanford.edu</em></a><em>.</em></p>

<p><em>The Stanford Institute for Materials and Energy Sciences (SIMES) is a joint institute of SLAC National Accelerator Laboratory and Stanford University. SIMES studies the nature, properties and synthesis of complex and novel materials in the effort to create clean, renewable energy technologies. For more information, please visit </em><a href="http://simes.slac.stanford.edu/"><em>simes.slac.stanford.edu</em></a><em>.</em></p>

<p><em>DOE&rsquo;s Office of Science is the single largest supporter of basic research in the physical sciences in the United States, and is working to address some of the most pressing challenges of our time. For more information, please visit </em><a href="http://science.energy.gov/"><em>science.energy.gov</em></a><em>.</em></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><em>Menlo Park, Calif.</em> — A single layer of tin atoms could be the world’s first material to conduct electricity with 100 percent efficiency at the temperatures that computer chips operate, according to a team of theoretical physicists led by researchers from the U.S. Department of Energy’s (DOE) SLAC National Accelerator Laboratory and Stanford University.</p>
<p>Researchers call the new material "stanene," combining the Latin name for tin (<em>stannum</em>) with the suffix used in graphene, another single-layer material whose novel electrical properties hold promise for a wide range of applications.</p>
<p>"Stanene could increase the speed and lower the power needs of future generations of computer chips, if our prediction is confirmed by experiments that are underway in several laboratories around the world," said the team leader, Shoucheng Zhang, a physics professor at Stanford and the Stanford Institute for Materials and Energy Sciences (SIMES), a joint institute with SLAC. The team’s work was <a href="http://prl.aps.org/abstract/PRL/v111/i13/e136804">published recently in <em>Physical Review Letters</em></a>.</p>
<p><strong>The Path to Stanene</strong></p>
<p>For the past decade, Zhang and colleagues have been calculating and predicting the electronic properties of a special class of materials known as topological insulators, which conduct electricity only on their outside edges or surfaces and not through their interiors. When topological insulators are just one atom thick, their edges conduct electricity with 100 percent efficiency. These unusual properties result from complex interactions between the electrons and nuclei of heavy atoms in the materials.</p>
<p>“The magic of topological insulators is that by their very nature, they force electrons to move in defined lanes without any speed limit, like the German autobahn,” Zhang said. “As long as they’re on the freeway – the edges or surfaces – the electrons will travel without resistance.”</p>
<p>In 2006 and 2009, Zhang’s group predicted that mercury telluride and several combinations of bismuth, antimony, selenium and tellurium should be topological insulators, and they were soon proven right in experiments performed by others. But none of those materials is a perfect conductor of electricity at room temperature, limiting their potential for commercial applications.</p>
<p>Earlier this year, visiting scientist Yong Xu, who is now at Tsinghua University in Beijing, collaborated with Zhang’s group to consider the properties of a single layer of pure tin.</p>
<p><span>“We knew we should be looking at elements in the lower-right portion of the periodic table,” Xu said. “All previous topological insulators have involved the heavy and electron-rich elements located there.”</span></p>
<p>Their calculations indicated that a single layer of tin would be a topological insulator at and above room temperature, and that adding fluorine atoms to the tin would extend its operating range to at least 100 degrees Celsius (212 degrees Fahrenheit).</p>
<p><strong>Ultimately a Substitute for Silicon?</strong></p>
<p>Zhang said the first application for this stanene-fluorine combination could be in wiring that connects the many sections of a microprocessor, allowing electrons to flow as freely as cars on a highway. Traffic congestion would still occur at on- and off-ramps made of conventional conductors, he said. But stanene wiring should significantly reduce the power consumption and heat production of microprocessors.</p>
<p><span>Manufacturing challenges include ensuring that only a single layer of tin is deposited and keeping that single layer intact during high-temperature chip-making processes.</span></p>
<p>“Eventually, we can imagine stanene being used for many more circuit structures, including replacing silicon in the hearts of transistors,” Zhang said. “Someday we might even call this area Tin Valley rather than Silicon Valley.”</p>
<p>Additional contributors included researchers from Tsinghua University in Beijing and the Max Planck Institute for Chemical Physics of Solids in Dresden, Germany. The research was supported by the Mesodynamic Architectures program of the Defense Advanced Research Projects Agency.</p>
<p><em>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science. To learn more, please visit </em><a href="http://www.slac.stanford.edu"><em>www.slac.stanford.edu</em></a><em>.</em></p>
<p><em>The Stanford Institute for Materials and Energy Sciences (SIMES) is a joint institute of SLAC National Accelerator Laboratory and Stanford University. SIMES studies the nature, properties and synthesis of complex and novel materials in the effort to create clean, renewable energy technologies. For more information, please visit </em><a href="http://simes.slac.stanford.edu/"><em>simes.slac.stanford.edu</em></a><em>.</em></p>
<p><em>DOE’s Office of Science is the single largest supporter of basic research in the physical sciences in the United States, and is working to address some of the most pressing challenges of our time. For more information, please visit </em><a href="http://science.energy.gov/"><em>science.energy.gov</em></a><em>.</em></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(
    'und' => array(
      0 => array(
        'value' => '<p><a href="http://prl.aps.org/abstract/PRL/v111/i13/e136804">Yong Xu <em>et al</em>., <em>Physical Review Letters</em>, 27 Sept 2013 (10.1103/PhysRevLett.111.136804)</a></p>
',
        'format' => 'full_html',
        'safe_value' => ' <p><a href="http://prl.aps.org/abstract/PRL/v111/i13/e136804">Yong Xu <em>et al</em>., <em>Physical Review Letters</em>, 27 Sept 2013 (10.1103/PhysRevLett.111.136804)</a></p>
 ',
      ),
    ),
  ),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Shoucheng Zhang, SLAC / Stanford University: sczhang@stanford.edu, (650) 723-2894 ',
        'format' => NULL,
        'safe_value' => 'Shoucheng Zhang, SLAC / Stanford University: sczhang@stanford.edu, (650) 723-2894 ',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 1,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'https://www6.slac.stanford.edu/news/2013-11-21-tin-super-material-stanene.aspx',
        'title' => 'SLAC',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 29,
        'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-05-02 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-12-02 01:22:06 -0700',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Stanford scientists working to develop broad-spectrum antiviral drug',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '1e26bc1e-be6e-47b2-af31-9780bb060506',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1379879115,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'bb850fab-95d9-45dc-9e52-9c4901fbad53',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>There are currently no vaccines or antiviral drugs for many of the most troubling viruses, in part because of the traditional one drug/one bug strategy to developing antiviral drugs. Stanford scientists are developing a new approach that could help identify drug pathways that could be effective across entire families of viruses.</p>

<p>When a virus infects a person, it hijacks the body&#39;s natural processes in order to fuel its rampage.</p>

<p>A pair of Stanford scientists aims to turn this strength into a weakness and develop what could become a broad-spectrum antiviral drug.</p>

<p>Most antiviral drugs are concocted to act against a specific viral protein. As such, they usually provide a &quot;one drug/one bug&quot; approach.</p>

<p>&quot;Penicillin can kill many types of bacteria, but most antiviral drugs work only against one virus, and sometimes a single subtype of a virus,&quot; said Shirit Einav, an assistant professor of medicine and of microbiology and immunology at Stanford School of Medicine.</p>

<p>Additionally, targeting viral proteins is problematic; viruses can mutate quickly, and a single change in the viral sequence can render it fully resistant to the drug.</p>

<p>&quot;With the exception of HIV, we still have very few antiviral drugs to offer patients with viral infections, and even those are often quite limited,&quot; Einav said. &quot;No approved antiviral drugs or vaccines are available for emerging viruses, such as dengue, which pose major challenges to global health.&quot;</p>

<p>Viruses live within our cells and rely upon host cell machineries in order to replicate. Instead of targeting the virus directly, the solution, Einav said, may be to instead interfere with host cell proteins that are utilized by multiple viruses. &quot;We treat diabetes and hypertension by targeting host proteins, so why not viral infections?&quot; Einav said.</p>

<p>With support from Stanford&#39;s Bio-X Interdisciplinary Initiatives Program (Bio-X IIP), Einav and Stephen Quake, a professor of bioengineering, have developed a process of identifying human proteins that wide families of viruses depend on for their success.</p>

<p>The initial focus of the work has involved identifying host proteins that, if knocked out, could inhibit both hepatitis C virus and HIV. This requires combing through incredibly large libraries of thousands of proteins, and a careful understanding of their role in both the virus and the host.</p>

<p>To find the needle in the haystack, Einav and Quake have developed a sequential approach that integrates advanced proteomic technologies with genomic and molecular virology approaches. The researchers have developed a high-fidelity platform that uses microfluidic chips created by Quake to express small amounts of a wide variety of host and viral proteins, and screens for direct interactions between them. This innovative proteomic technology overcomes some important limitations of existing technologies, such as ability to study weak and transient protein interactions, and those involving membrane proteins.</p>

<p>Once the researchers discover a positive protein interaction between virus and host, they knock out the corresponding host gene in an infected cell to determine if the protein plays a vital role in the virus&#39; life cycle. If it does, they then investigate whether other viruses require this protein.</p>

<p>In just a year, the researchers have shown that this approach can accurately identify host proteins or pathways that play critical roles in multiple infections by unrelated viruses. Based primarily on this work, the researchers are building a catalog of such overlapping host proteins that represent potential attractive targets for broad-spectrum antivirals.</p>

<p>The Einav lab has also produced proof-of-concept evidence that drugs that are already FDA approved for other indications, and target host proteins required by multiple viruses, could be repurposed as broad spectrum antivirals, with activity against hepatitis C virus, HIV, as well as the currently untreatable dengue and ebola viruses.</p>

<p>&quot;We have to make sure that the single targeted protein is absolutely crucial to multiple viruses,&quot; Einav said. &quot;At the same time, we need to make sure that the drug that inhibits this host protein is safe. As long as viral replication is inhibited at a drug level that is not toxic and allows the host cell to function as close to normal as possible, this could work.</p>

<p>&quot;This is just the beginning, but the more we look, the more we find.&quot;</p>

<p>Since 2000, Bio-X has provided funding for interdisciplinary projects that have the potential to improve human health in innovative ways. Bio-X seed grants have funded 141 research collaborations connecting hundreds of faculty. The proof-of-concept projects have produced hundreds of scientific publications, dozens of patents and more than a tenfold return on research funds to Stanford.</p>

<p>&quot;Bio-X has really made this possible for me,&quot; Einav said. &quot;I&#39;m a new assistant professor, and this is essentially defined as discovery-based research, which is very difficult to get funded by conventional funding mechanisms. Many funding agencies want you to catch, prepare and cook the fish, and they will provide you funding just before you take the first bite. So to get early-stage funding for high-risk but high-reward research like this is really quite remarkable.&quot;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>There are currently no vaccines or antiviral drugs for many of the most troubling viruses, in part because of the traditional one drug/one bug strategy to developing antiviral drugs. Stanford scientists are developing a new approach that could help identify drug pathways that could be effective across entire families of viruses.</p>
<p>When a virus infects a person, it hijacks the body\'s natural processes in order to fuel its rampage.</p>
<p>A pair of Stanford scientists aims to turn this strength into a weakness and develop what could become a broad-spectrum antiviral drug.</p>
<p>Most antiviral drugs are concocted to act against a specific viral protein. As such, they usually provide a "one drug/one bug" approach.</p>
<p>"Penicillin can kill many types of bacteria, but most antiviral drugs work only against one virus, and sometimes a single subtype of a virus," said Shirit Einav, an assistant professor of medicine and of microbiology and immunology at Stanford School of Medicine.</p>
<p>Additionally, targeting viral proteins is problematic; viruses can mutate quickly, and a single change in the viral sequence can render it fully resistant to the drug.</p>
<p>"With the exception of HIV, we still have very few antiviral drugs to offer patients with viral infections, and even those are often quite limited," Einav said. "No approved antiviral drugs or vaccines are available for emerging viruses, such as dengue, which pose major challenges to global health."</p>
<p>Viruses live within our cells and rely upon host cell machineries in order to replicate. Instead of targeting the virus directly, the solution, Einav said, may be to instead interfere with host cell proteins that are utilized by multiple viruses. "We treat diabetes and hypertension by targeting host proteins, so why not viral infections?" Einav said.</p>
<p>With support from Stanford\'s Bio-X Interdisciplinary Initiatives Program (Bio-X IIP), Einav and Stephen Quake, a professor of bioengineering, have developed a process of identifying human proteins that wide families of viruses depend on for their success.</p>
<p>The initial focus of the work has involved identifying host proteins that, if knocked out, could inhibit both hepatitis C virus and HIV. This requires combing through incredibly large libraries of thousands of proteins, and a careful understanding of their role in both the virus and the host.</p>
<p>To find the needle in the haystack, Einav and Quake have developed a sequential approach that integrates advanced proteomic technologies with genomic and molecular virology approaches. The researchers have developed a high-fidelity platform that uses microfluidic chips created by Quake to express small amounts of a wide variety of host and viral proteins, and screens for direct interactions between them. This innovative proteomic technology overcomes some important limitations of existing technologies, such as ability to study weak and transient protein interactions, and those involving membrane proteins.</p>
<p>Once the researchers discover a positive protein interaction between virus and host, they knock out the corresponding host gene in an infected cell to determine if the protein plays a vital role in the virus\' life cycle. If it does, they then investigate whether other viruses require this protein.</p>
<p>In just a year, the researchers have shown that this approach can accurately identify host proteins or pathways that play critical roles in multiple infections by unrelated viruses. Based primarily on this work, the researchers are building a catalog of such overlapping host proteins that represent potential attractive targets for broad-spectrum antivirals.</p>
<p>The Einav lab has also produced proof-of-concept evidence that drugs that are already FDA approved for other indications, and target host proteins required by multiple viruses, could be repurposed as broad spectrum antivirals, with activity against hepatitis C virus, HIV, as well as the currently untreatable dengue and ebola viruses.</p>
<p>"We have to make sure that the single targeted protein is absolutely crucial to multiple viruses," Einav said. "At the same time, we need to make sure that the drug that inhibits this host protein is safe. As long as viral replication is inhibited at a drug level that is not toxic and allows the host cell to function as close to normal as possible, this could work.</p>
<p>"This is just the beginning, but the more we look, the more we find."</p>
<p>Since 2000, Bio-X has provided funding for interdisciplinary projects that have the potential to improve human health in innovative ways. Bio-X seed grants have funded 141 research collaborations connecting hundreds of faculty. The proof-of-concept projects have produced hundreds of scientific publications, dozens of patents and more than a tenfold return on research funds to Stanford.</p>
<p>"Bio-X has really made this possible for me," Einav said. "I\'m a new assistant professor, and this is essentially defined as discovery-based research, which is very difficult to get funded by conventional funding mechanisms. Many funding agencies want you to catch, prepare and cook the fish, and they will provide you funding just before you take the first bite. So to get early-stage funding for high-risk but high-reward research like this is really quite remarkable."</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 1,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
        'title' => 'Stanford Report',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 72,
        'uuid' => 'dad41187-6745-43bc-b95a-7851a7b2c825',
      ),
      1 => array(
        'tid' => 71,
        'uuid' => 'aaa4a1c8-fb65-4eeb-9bfe-909031f5e18b',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 29,
        'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2014-01-23 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2013-09-22 13:45:15 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Scientists Prove X-ray Laser Can Solve Protein Structures from Scratch',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '6c5ef37d-c299-4397-b2fd-2e589faca227',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1385972261,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'da567b81-da7d-48ac-ac1a-bc1e51e5478b',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><em>Menlo Park, Calif. &mdash;</em> A study shows for the first time that X-ray lasers can be used to generate a complete 3-D model of a protein without any prior knowledge of its structure.</p>

<p>An international team of researchers working at the Department of Energy&#39;s (DOE) SLAC National Accelerator Laboratory produced from scratch an accurate model of lysozyme, a well-studied enzyme found in egg whites, using the Linac Coherent Light Source (LCLS) X-ray laser and sophisticated computer analysis tools.</p>

<p>The experiment proves that X-ray lasers can play a leading role in studying important biomolecules of unknown structure. The special attributes of LCLS, which allow the study of very small crystals, could cement its role in hunting down many important biological structures that have so far remained out of reach because they form crystals too small for analysis with conventional X-ray sources.</p>

<p>&quot;Determining protein structures using X-ray lasers requires averaging a gigantic amount of data to get a sufficiently accurate signal, and people wondered if this really could be done,&rdquo; said Thomas Barends, a staff scientist at the Max Planck Institute for Medical Research in Germany who participated in the research. &quot;Now we have experimental evidence. This really opens the door to new discoveries.&quot;</p>

<p>Collaborators from SLAC and Arizona State University also participated in the research, which was <a href="http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12773.html" target="_blank">published Nov. 24 in <em>Nature</em></a><em>.</em></p>

<p>The underlying technique, called X-ray crystallography, is credited with solving the vast majority of all known protein structures and is <a href="http://www.iucr.org/people/nobel-prize">associated with numerous Nobel Prizes</a> since its first use just over a century ago.</p>

<p>Protein structures tie directly to their functions, such as how they bind and interact with other molecules, and thus provide vital details for developing highly targeted disease-fighting drugs. But many protein structures that are considered promising targets for new medicines remain unknown, mainly because they don&#39;t form crystals that can be deciphered with existing techniques.</p>

<p>This work is the latest in a rapid progression of important advances at LCLS, which began operations for users in 2010. For example, <a href="https://www6.slac.stanford.edu/news/2012-11-29-sleepingsickness.aspx">last year</a> researchers used LCLS to determine the structure of an enzyme that can hold African sleeping sickness in check, which makes it a promising drug target. However, those previous studies relied on data from similar, known structures to fill in common data gaps.</p>

<p>For this study the researchers chose lysozyme, whose structure has been known for decades, because it offered a good test of whether their method produced accurate results. They soaked lysozyme crystals in a solution containing gadolinium, a metal that bonded with the lysozyme to produce a strong signal when subjected to the intense X-ray light. It was this signal from the gadolinium atoms that enabled exact reconstruction of the lysozyme molecule.</p>

<p>The team hopes to adapt and refine the technique to explore more complex proteins such as membrane proteins, which serve a range of important cellular functions and are the target of more than half of all new drugs in development. Only a small fraction of the thousands of membrane proteins have been completely mapped.</p>

<p>&quot;This study is an important milestone on which the field will build further,&quot; said John R. Helliwell, emeritus professor of chemistry at the University of Manchester and formerly a director of the Synchrotron Radiation Source at Daresbury Laboratory in England. &quot;The X-ray laser is bringing new opportunities and new ideas for 3-D structure determination of ever-smaller samples. The use of computers to automate this process is a triumph.&quot;</p>

<p>Barends said the latest results are a remarkable achievement, given that it took just a few years for LCLS to reach this milestone. &quot;Further improvements in X-ray detectors, software and crystal formation and delivery techniques should enable more discoveries in the coming years,&quot; he said.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><em>Menlo Park, Calif. —</em> A study shows for the first time that X-ray lasers can be used to generate a complete 3-D model of a protein without any prior knowledge of its structure.</p>
<p>An international team of researchers working at the Department of Energy\'s (DOE) SLAC National Accelerator Laboratory produced from scratch an accurate model of lysozyme, a well-studied enzyme found in egg whites, using the Linac Coherent Light Source (LCLS) X-ray laser and sophisticated computer analysis tools.</p>
<p>The experiment proves that X-ray lasers can play a leading role in studying important biomolecules of unknown structure. The special attributes of LCLS, which allow the study of very small crystals, could cement its role in hunting down many important biological structures that have so far remained out of reach because they form crystals too small for analysis with conventional X-ray sources.</p>
<p>"Determining protein structures using X-ray lasers requires averaging a gigantic amount of data to get a sufficiently accurate signal, and people wondered if this really could be done,” said Thomas Barends, a staff scientist at the Max Planck Institute for Medical Research in Germany who participated in the research. "Now we have experimental evidence. This really opens the door to new discoveries."</p>
<p>Collaborators from SLAC and Arizona State University also participated in the research, which was <a href="http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12773.html" target="_blank">published Nov. 24 in <em>Nature</em></a><em>.</em></p>
<p>The underlying technique, called X-ray crystallography, is credited with solving the vast majority of all known protein structures and is <a href="http://www.iucr.org/people/nobel-prize">associated with numerous Nobel Prizes</a> since its first use just over a century ago.</p>
<p>Protein structures tie directly to their functions, such as how they bind and interact with other molecules, and thus provide vital details for developing highly targeted disease-fighting drugs. But many protein structures that are considered promising targets for new medicines remain unknown, mainly because they don\'t form crystals that can be deciphered with existing techniques.</p>
<p>This work is the latest in a rapid progression of important advances at LCLS, which began operations for users in 2010. For example, <a href="https://www6.slac.stanford.edu/news/2012-11-29-sleepingsickness.aspx">last year</a> researchers used LCLS to determine the structure of an enzyme that can hold African sleeping sickness in check, which makes it a promising drug target. However, those previous studies relied on data from similar, known structures to fill in common data gaps.</p>
<p>For this study the researchers chose lysozyme, whose structure has been known for decades, because it offered a good test of whether their method produced accurate results. They soaked lysozyme crystals in a solution containing gadolinium, a metal that bonded with the lysozyme to produce a strong signal when subjected to the intense X-ray light. It was this signal from the gadolinium atoms that enabled exact reconstruction of the lysozyme molecule.</p>
<p>The team hopes to adapt and refine the technique to explore more complex proteins such as membrane proteins, which serve a range of important cellular functions and are the target of more than half of all new drugs in development. Only a small fraction of the thousands of membrane proteins have been completely mapped.</p>
<p>"This study is an important milestone on which the field will build further," said John R. Helliwell, emeritus professor of chemistry at the University of Manchester and formerly a director of the Synchrotron Radiation Source at Daresbury Laboratory in England. "The X-ray laser is bringing new opportunities and new ideas for 3-D structure determination of ever-smaller samples. The use of computers to automate this process is a triumph."</p>
<p>Barends said the latest results are a remarkable achievement, given that it took just a few years for LCLS to reach this milestone. "Further improvements in X-ray detectors, software and crystal formation and delivery techniques should enable more discoveries in the coming years," he said.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(
    'und' => array(
      0 => array(
        'value' => '<p><a href="http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12773.html" target="_blank">T. Barends et al., Nature, 24 November 2013 (10.1038/nature12773)</a></p>
',
        'format' => 'full_html',
        'safe_value' => ' <p><a href="http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12773.html" target="_blank">T. Barends et al., Nature, 24 November 2013 (10.1038/nature12773)</a></p>
 ',
      ),
    ),
  ),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Thomas Barends, Max Planck Institute for Medical Research: Thomas.Barends@mpimf-heidelberg.mpg.de
Ilme Schlichting, Max Planck Institute for Medical Research: Ilme.Schlichting@mpimf-heidelberg.mpg.de
Sebastien Boutet, SLAC National Accelerator Laboratory: sboutet@slac.stanford.edu',
        'format' => NULL,
        'safe_value' => 'Thomas Barends, Max Planck Institute for Medical Research: Thomas.Barends@mpimf-heidelberg.mpg.de
Ilme Schlichting, Max Planck Institute for Medical Research: Ilme.Schlichting@mpimf-heidelberg.mpg.de
Sebastien Boutet, SLAC National Accelerator Laboratory: sboutet@slac.stanford.edu',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 2,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'https://www6.slac.stanford.edu/news/2013-11-24-x-ray-laser-solves-protein-structure-from-scratch.aspx',
        'title' => 'SLAC',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 28,
        'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-09-07 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2013-12-02 01:17:41 -0700',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Global warming has increased risk of record heat, say Stanford scientists',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8e26bc1e-be6e-47b2-af31-9780bb060506',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1348688715,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'eb850fab-95d9-45dc-9e52-9c4901fbad53',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Researchers calculate that intense heat like that in the summer of 2012 is up to four times more likely to occur now than in pre-industrial America, when there was much less carbon dioxide in the atmosphere.</p>

<p>Drought shriveled crops in the Midwest, massive wildfires raged in the West and East Coast cities sweltered. The summer of 2012 was a season of epic proportions, especially July, the hottest month in the history of U.S. weather record keeping.</p>

<p>And it&#39;s likely that we&#39;ll continue to see such calamitous weather.</p>

<p>In the north-central and northeastern United States, extreme weather is more than four times as likely to occur than it was in the pre-industrial era, according to a new study by Noah Diffenbaugh, a Stanford associate professor of environmental Earth system science, and Martin Scherer, a research assistant in the department.</p>

<p>Diffenbaugh and Scherer found strong evidence that the high levels of greenhouse gases now in the atmosphere have increased the likelihood of severe heat such as occurred in the United States in 2012.</p>

<p>The researchers focused primarily on understanding the physical processes that created the hazardous weather. They looked at how rare those conditions were over the history of available weather records, going back over the last century.</p>

<p>Then, using climate models, they quantified how the risk of such damaging weather has changed in the current climate of high greenhouse gas concentrations, as opposed to an era of significantly lower concentrations and no global warming. Their findings don&#39;t pinpoint global warming as the cause of particular extreme weather events, but they do reveal the increasing risk of such events as the world warms.</p>

<p>&quot;Going forward, if we want to understand and manage climate risks, it&#39;s more practically relevant to understand the likelihood of the hazard than to ask whether any particular disaster was caused by global warming,&quot; said Diffenbaugh, a senior fellow at the Stanford Woods Institute for the Environment.</p>

<p>In 2012 alone, the United States suffered 11 extreme weather events that each caused at least $1 billion in damage. &quot;It&#39;s clear that our greenhouse gas emissions have increased the likelihood of some kinds of extremes, and it&#39;s clear that we&#39;re not optimally adapted to that new climate,&quot; Diffenbaugh said.</p>

<p>While Diffenbaugh cautions against trying to determine whether global warming caused any individual extreme event, the observed global warming clearly appears to have affected the likelihood of record heat, according to Diffenbaugh and Scherer.</p>

<p>The study, looking at the likelihood of July 2012 U.S. temperatures recurring, is part of a larger report edited by scientists at the National Oceanic and Atmospheric Administration (NOAA) and published Sept. 5 in the Bulletin of the American Meteorological Society. The report includes studies of a dozen 2012 extreme weather events by research teams around the world, about half of which found some evidence that human-caused climate change contributed to an extreme weather event.</p>

<p>Close study of extreme weather events can help quantify the likelihood that society will face conditions similar to those that occurred in the summer of 2012, thereby informing efforts to reduce vulnerability and increase resilience. Diffenbaugh argues that the new results can also help to quantify the true cost of emissions to society, since the cost of the disaster is measurable.</p>

<p>&quot;Knowing how much our emissions have changed the likelihood of this kind of severe heat event can help us to minimize the impacts of the next heat wave, and to determine the value of avoiding further changes in climate,&quot; Diffenbaugh said.</p>

<p>Funding for this research was provided by the National Science Foundation and the National Institutes of Health.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>Researchers calculate that intense heat like that in the summer of 2012 is up to four times more likely to occur now than in pre-industrial America, when there was much less carbon dioxide in the atmosphere.</p>
<p>Drought shriveled crops in the Midwest, massive wildfires raged in the West and East Coast cities sweltered. The summer of 2012 was a season of epic proportions, especially July, the hottest month in the history of U.S. weather record keeping.</p>
<p>And it\'s likely that we\'ll continue to see such calamitous weather.</p>
<p>In the north-central and northeastern United States, extreme weather is more than four times as likely to occur than it was in the pre-industrial era, according to a new study by Noah Diffenbaugh, a Stanford associate professor of environmental Earth system science, and Martin Scherer, a research assistant in the department.</p>
<p>Diffenbaugh and Scherer found strong evidence that the high levels of greenhouse gases now in the atmosphere have increased the likelihood of severe heat such as occurred in the United States in 2012.</p>
<p>The researchers focused primarily on understanding the physical processes that created the hazardous weather. They looked at how rare those conditions were over the history of available weather records, going back over the last century.</p>
<p>Then, using climate models, they quantified how the risk of such damaging weather has changed in the current climate of high greenhouse gas concentrations, as opposed to an era of significantly lower concentrations and no global warming. Their findings don\'t pinpoint global warming as the cause of particular extreme weather events, but they do reveal the increasing risk of such events as the world warms.</p>
<p>"Going forward, if we want to understand and manage climate risks, it\'s more practically relevant to understand the likelihood of the hazard than to ask whether any particular disaster was caused by global warming," said Diffenbaugh, a senior fellow at the Stanford Woods Institute for the Environment.</p>
<p>In 2012 alone, the United States suffered 11 extreme weather events that each caused at least $1 billion in damage. "It\'s clear that our greenhouse gas emissions have increased the likelihood of some kinds of extremes, and it\'s clear that we\'re not optimally adapted to that new climate," Diffenbaugh said.</p>
<p>While Diffenbaugh cautions against trying to determine whether global warming caused any individual extreme event, the observed global warming clearly appears to have affected the likelihood of record heat, according to Diffenbaugh and Scherer.</p>
<p>The study, looking at the likelihood of July 2012 U.S. temperatures recurring, is part of a larger report edited by scientists at the National Oceanic and Atmospheric Administration (NOAA) and published Sept. 5 in the Bulletin of the American Meteorological Society. The report includes studies of a dozen 2012 extreme weather events by research teams around the world, about half of which found some evidence that human-caused climate change contributed to an extreme weather event.</p>
<p>Close study of extreme weather events can help quantify the likelihood that society will face conditions similar to those that occurred in the summer of 2012, thereby informing efforts to reduce vulnerability and increase resilience. Diffenbaugh argues that the new results can also help to quantify the true cost of emissions to society, since the cost of the disaster is measurable.</p>
<p>"Knowing how much our emissions have changed the likelihood of this kind of severe heat event can help us to minimize the impacts of the next heat wave, and to determine the value of avoiding further changes in climate," Diffenbaugh said.</p>
<p>Funding for this research was provided by the National Science Foundation and the National Institutes of Health.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 1,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
        'title' => 'Stanford Report',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 73,
        'uuid' => '971c94e1-0a7e-474c-96ca-9e1a4da2d6a5',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 29,
        'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2014-01-22 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-09-26 13:45:15 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Stanford research helps people with social phobia face their fears',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '7a26bc1e-be6e-47b2-af31-9780bb060506',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1348775115,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'er850fab-95d9-45dc-9e52-9c4901fbad53',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Study finds therapy that teaches patients how to reframe negative thoughts reduces symptoms of anxiety associated with social situations.</p>

<p>Social anxiety disorder &ndash; which can include being afraid of speaking in public, fear of interacting with people, and intense nervousness at being the center of attention &ndash; affects millions of people each year.</p>

<p>Those living with it suffer from distorted thinking, including false beliefs about social situations and the negative opinions of others. They feel judged, embarrassed and criticized. The disorder can interfere with school, work, activities and relationships.</p>

<p>A team of research scientists at Stanford&#39;s Clinically Applied Affective Neuroscience project at the Department of Psychology has been studying treatment options, using functional magnetic resonance imaging and clinical interventions to examine the factors that cause and maintain emotional balance and imbalance.</p>

<p>A new study from the lab looked at one of the most popular non-drug methods to treat social anxiety disorder &ndash; cognitive behavioral therapy &ndash; to see what changes happen in the brain after a person receives this remedy.</p>

<p>Through a series of experiments, the researchers found that the therapy, a kind of mental health counseling that helps people learn to respond more skillfully to negative emotions, indeed was effective in significantly reducing symptoms of social anxiety disorder.</p>

<p>Further, they found that the therapy increased brain activity in areas associated with emotion regulation.</p>

<p>Why does it work?</p>

<p>Philippe Goldin, one of the main researchers, said that understanding how the brain responds to and changes with the therapy can help elucidate how and why cognitive behavioral therapy works.</p>

<p>With that knowledge, Goldin said, future studies could investigate how different forms of the therapy &ndash; for example, group therapy versus individual therapy &ndash; influence the dynamics of brain networks involved in emotion regulation strategies.</p>

<p>In the study, published this month online in the journal JAMA Psychiatry, patients diagnosed with social anxiety disorder underwent 16 psychotherapy sessions over four months, during which they were trained to change the way they deal with certain negative emotions.</p>

<p>This training in &quot;cognitive reappraisal or restructuring&quot; allows a person to revisit his or her emotional response to a situation and change the reaction.</p>

<p>For example, Goldin said, imagine a person who fails a series of tests. He first thinks negatively about his performance. But once he reframes his response, he can later view the results as a way to challenge and better himself.</p>

<p>Another example, described in the study, would be someone thinking, &quot;No one likes me.&quot; A way of reframing that thinking may be to tell oneself, &quot;That&#39;s not always true,&quot; &quot;Some people like me,&quot; or &quot;This is only a thought, not a fact.&quot;</p>

<p>Prior neuroimaging studies have found that patients with social anxiety disorder show delays in regions of the brain associated with emotion regulation and abnormalities in neural circuitry there, compared with healthy people.</p>

<p>But those studies left questions about whether clinical interventions like psychotherapy could affect how the brain responds.</p>

<p>Reactions in the brain</p>

<p>For this study, patients were scanned using fMRI to investigate brain responses when reacting to and reframing negative-self-beliefs. During the scan, patients read autobiographical social situations with situation-specific beliefs embedded in the story that were used to probe reactivity and reappraisal.</p>

<p>After each negative self-belief came up, patients rated how they felt.</p>

<p>Goldin said the study further reveals that counseling is effective in changing the behavior of the brain, helping people respond to and reframe negative emotions more quickly.</p>

<p>The effectiveness of cognitive behavioral therapy gives hope to many of the sufferers of social anxiety disorder that there is a treatment that can last and endure without drugs.</p>

<p>Besides Goldin, the research team includes Stanford Professor James Gross, researchers Michal Ziv, Hooria Jazaieri and Kevin Hahn; and Professor Richard Heimberg of Temple University.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>Study finds therapy that teaches patients how to reframe negative thoughts reduces symptoms of anxiety associated with social situations.</p>
<p>Social anxiety disorder – which can include being afraid of speaking in public, fear of interacting with people, and intense nervousness at being the center of attention – affects millions of people each year.</p>
<p>Those living with it suffer from distorted thinking, including false beliefs about social situations and the negative opinions of others. They feel judged, embarrassed and criticized. The disorder can interfere with school, work, activities and relationships.</p>
<p>A team of research scientists at Stanford\'s Clinically Applied Affective Neuroscience project at the Department of Psychology has been studying treatment options, using functional magnetic resonance imaging and clinical interventions to examine the factors that cause and maintain emotional balance and imbalance.</p>
<p>A new study from the lab looked at one of the most popular non-drug methods to treat social anxiety disorder – cognitive behavioral therapy – to see what changes happen in the brain after a person receives this remedy.</p>
<p>Through a series of experiments, the researchers found that the therapy, a kind of mental health counseling that helps people learn to respond more skillfully to negative emotions, indeed was effective in significantly reducing symptoms of social anxiety disorder.</p>
<p>Further, they found that the therapy increased brain activity in areas associated with emotion regulation.</p>
<p>Why does it work?</p>
<p>Philippe Goldin, one of the main researchers, said that understanding how the brain responds to and changes with the therapy can help elucidate how and why cognitive behavioral therapy works.</p>
<p>With that knowledge, Goldin said, future studies could investigate how different forms of the therapy – for example, group therapy versus individual therapy – influence the dynamics of brain networks involved in emotion regulation strategies.</p>
<p>In the study, published this month online in the journal JAMA Psychiatry, patients diagnosed with social anxiety disorder underwent 16 psychotherapy sessions over four months, during which they were trained to change the way they deal with certain negative emotions.</p>
<p>This training in "cognitive reappraisal or restructuring" allows a person to revisit his or her emotional response to a situation and change the reaction.</p>
<p>For example, Goldin said, imagine a person who fails a series of tests. He first thinks negatively about his performance. But once he reframes his response, he can later view the results as a way to challenge and better himself.</p>
<p>Another example, described in the study, would be someone thinking, "No one likes me." A way of reframing that thinking may be to tell oneself, "That\'s not always true," "Some people like me," or "This is only a thought, not a fact."</p>
<p>Prior neuroimaging studies have found that patients with social anxiety disorder show delays in regions of the brain associated with emotion regulation and abnormalities in neural circuitry there, compared with healthy people.</p>
<p>But those studies left questions about whether clinical interventions like psychotherapy could affect how the brain responds.</p>
<p>Reactions in the brain</p>
<p>For this study, patients were scanned using fMRI to investigate brain responses when reacting to and reframing negative-self-beliefs. During the scan, patients read autobiographical social situations with situation-specific beliefs embedded in the story that were used to probe reactivity and reappraisal.</p>
<p>After each negative self-belief came up, patients rated how they felt.</p>
<p>Goldin said the study further reveals that counseling is effective in changing the behavior of the brain, helping people respond to and reframe negative emotions more quickly.</p>
<p>The effectiveness of cognitive behavioral therapy gives hope to many of the sufferers of social anxiety disorder that there is a treatment that can last and endure without drugs.</p>
<p>Besides Goldin, the research team includes Stanford Professor James Gross, researchers Michal Ziv, Hooria Jazaieri and Kevin Hahn; and Professor Richard Heimberg of Temple University.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 1,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
        'title' => 'Stanford Report',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 74,
        'uuid' => '4538f295-cc43-4d99-ba1d-6a7f23e86663',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 29,
        'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-10-05 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-09-27 13:45:15 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Two Stanford professors win MacArthur \'genius\' awards',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '7a26bc1e-be2e-47b2-af31-9780bb060506',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1348429515,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'er850fab-9ad9-45dc-9e52-9c4901fbad53',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>David Lobell was honored with a MacArthur Fellowship for research on the impact of climate change on crop production and food security. Kevin Boyce won his fellowship for establishing links between ancient plant remains and present-day ecosystems.</p>

<p>Two professors in the Stanford School of Earth Sciences &ndash; David Lobell, an associate professor of environmental Earth system science and Kevin Boyce, an associate professor of geological and environmental sciences &ndash; have been named 2013 MacArthur Fellows.</p>

<p>Lobell was cited &quot;for unearthing richly informative, but often underutilized sources of data to investigate the impact of climate change on crop production and global food security.&quot; He received his doctorate degree from Stanford in 2005 and was appointed to the faculty in 2009.</p>

<p>The MacArthur Foundation recognized Boyce &quot;for establishing links between ancient plant remains and present-day ecosystems through a pioneering and integrative approach to evolutionary plant biology.&quot; Boyce joined Stanford&#39;s geobiology program from the University of Chicago in July.</p>

<p>Lobell and Boyce are among 24 individuals honored this year by the John D. and Catherine T. MacArthur Foundation. &nbsp;According to the foundation, fellowships are awarded to talented individuals in a variety of fields in recognition of originality, creativity, self-direction and capacity to contribute importantly to society through their work. The fellows receive a $625,000 &quot;no-strings-attached&quot; grant over five years to use in any way they see fit.</p>

<p>&quot;Both Kevin and David are distinguished researchers who work at the intersection of many scientific disciplines, where they can draw upon multiple approaches to find creative solutions to some of our greatest challenges &ndash; whether it is feeding the world or the possible impacts of ecological changes on the evolution of plant life,&quot; said Stanford President John Hennessy and Provost John Etchemendy in a joint statement. &quot; We couldn&#39;t be more pleased that this multidisciplinary strength has been recognized in the awarding of two MacArthur Fellowships to our accomplished faculty in the School of Earth Sciences.&quot;</p>

<p>David Lobell: &quot;Climate change is one of the reasons for concern about feeding people in the future, but it&#39;s not insurmountable.&quot;</p>

<p>A pioneer of the emerging field of crop informatics, Lobell is revolutionizing the understanding of the environmental factors controlling crop yields, with a particular emphasis on adaptation to climate change. His work provides decision makers, for the first time, with critical information about how to adapt agricultural development to climate change.</p>

<p>&quot;I was completely surprised by this recognition, but am really excited by the opportunity it presents,&quot; said Lobell, who in addition to his faculty position is associate director of the Center on Food Security and the Environment at Stanford, a joint center of the Freeman Spogli Institute and the Stanford Woods Institute for the Environment. &nbsp;&quot;To have the MacArthur Foundation recognize the value of taking new approaches and the importance of the topics of hunger and food production is deeply gratifying.&quot;</p>

<p>Lobell&#39;s research focuses on identifying opportunities to increase yields of crops including wheat and corn in major agricultural regions, with projects currently underway in Africa, South Asia, Mexico and the United States. &nbsp;&quot;I&#39;m interested in how to feed the world and protect the environment at the same time,&quot; he said. &quot;While there are many theories about how to do that, my work tries to test these theories, often using data that were collected for completely different reasons.&quot;</p>

<p>The citation emphasized Lobell&#39;s work on understanding the risks of climate change, and options for adaptation. &quot;Climate change is one of the reasons for concern about feeding people in the future, but it&#39;s not insurmountable if good decisions are made,&quot; he said.&nbsp;</p>

<p>When asked how he would use the funding, Lobell said he would not rush the decision. He said that some of the award would likely relieve him of writing grant proposals. In addition, he said he would consider using some toward more travel. &quot;A lot of my better ideas in the past have started with travel and interactions with international collaborations,&quot; he said. &nbsp;&quot;And there&#39;s always a tradeoff between my work travel and family. &nbsp;I now might take my wife and young sons with me on some extended trips.&quot;</p>

<p>Widely sought throughout the world to provide expert advice, Lobell is a lead author for the Intergovernmental Panel on Climate Change Fifth Assessment Report chapter on food security, to be published in 2014.&nbsp;</p>

<p>Lobell studied applied mathematics at Brown University, and before receiving his bachelor&#39;s degree in 2000, he spent the summer of 1999 as a research intern at Stanford, developing remote sensing algorithms. He then pursued graduate studies at Stanford, receiving his doctorate in geological and environmental sciences in 2005. He was a postdoctoral fellow at Lawrence Livermore National Laboratory from 2005-2007, and returned to Stanford as a senior research scholar in the Program on Food Security and the Environment in 2008-2009. &nbsp;He accepted an appointment as assistant professor in the Stanford School of Earth Sciences in 2009.&nbsp;</p>

<p>In addition to his research, Lobell teaches several courses open to both undergraduates and graduate students, including &quot;Feeding Nine Billion,&quot; &quot;Climate and Agriculture,&quot; and &quot;Global Land Use to 2050,&quot; as well as modeling and statistical methods classes.</p>

<p>Lobell received a NASA New Investigator Program Award for 2008-2011. He received the James B. Macelwane Medal from the American Geophysical Union in 2010, awarded for significant contributions to the geophysical sciences by an outstanding scientist under the age of 36.</p>

<p>Kevin Boyce: &quot;The evolution of plants is the evolution of the Earth&#39;s surface.&quot;</p>

<p>Boyce is a paleontologist whose studies of both extinct and living plants across multiple timescales are establishing direct links between ancient remains and present-day ecosystems and advancing the understanding of potential ecological changes. &nbsp;He has emerged as a leader in a new subfield of paleontology that brings patterns of development and physiological processes of living organisms to bear on the study of fossils.</p>

<p>&quot;Plants represent most of the Earth&#39;s biomass and they strongly influence global chemical cycling, climate, atmospheric composition, sedimentary processes, etc.,&quot; Boyce said. &nbsp;&quot;So, in a real sense, the evolution of plants is the evolution of the Earth&#39;s surface.&quot;</p>

<p>In collaboration with colleagues in plant physiology, and climate science, Boyce has advanced interpretations of how major plant components have evolved by using such modern technology as X-ray spectromicroscopy to examine plant specimens at the tissue and cellular level. The MacArthur award cited Boyce for solving mysteries about the morphology of plants that have puzzled scientists for decades and establishing macroecological perspectives of emergent biodiversity, while also challenging evolutionary scientists to embrace new angles of research to advance knowledge and discovery.</p>

<p>&quot;I am surprised to receive the MacArthur fellowship, but am happy to see geobiology and the plant fossil record get attention,&quot; Boyce said. &nbsp;&quot;Often the most interesting projects are the ones that can&#39;t be funded directly because they are riskier and there is no guaranteed outcome. &nbsp;An award such as this allows you to focus on the fun stuff.&quot;</p>

<p>Boyce received dual degrees in literature and biology from the California Institute of Technology in 1995. He received his doctorate in paleontology in 2001 from Harvard University. From 2001 to 2003, he held a National Research Council Associateship with the NASA Astrobiology Institute. Prior to joining Stanford, he was on the faculty of the University of Chicago from 2003-13, most recently as an associate professor of geophysical sciences.</p>

<p>In the next academic year, he is planning to teach courses including &quot;Evolution of Terrestrial Ecosystems&quot; and &quot;The Evolution of Plant Form and Function.&quot;</p>

<p>In 2011, Boyce received the Charles Schuchert Award from the Paletontological Society, presented to scientists under age 40 for early career work reflecting excellence and promise in the science of paleontology. &nbsp;Concurrently he was named a fellow of the Paleontological Society. He received the William S. Cooper Award from the Ecological Society of America in 2012 in honor of outstanding contributions in the field of biogeography.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>David Lobell was honored with a MacArthur Fellowship for research on the impact of climate change on crop production and food security. Kevin Boyce won his fellowship for establishing links between ancient plant remains and present-day ecosystems.</p>
<p>Two professors in the Stanford School of Earth Sciences – David Lobell, an associate professor of environmental Earth system science and Kevin Boyce, an associate professor of geological and environmental sciences – have been named 2013 MacArthur Fellows.</p>
<p>Lobell was cited "for unearthing richly informative, but often underutilized sources of data to investigate the impact of climate change on crop production and global food security." He received his doctorate degree from Stanford in 2005 and was appointed to the faculty in 2009.</p>
<p>The MacArthur Foundation recognized Boyce "for establishing links between ancient plant remains and present-day ecosystems through a pioneering and integrative approach to evolutionary plant biology." Boyce joined Stanford\'s geobiology program from the University of Chicago in July.</p>
<p>Lobell and Boyce are among 24 individuals honored this year by the John D. and Catherine T. MacArthur Foundation.  According to the foundation, fellowships are awarded to talented individuals in a variety of fields in recognition of originality, creativity, self-direction and capacity to contribute importantly to society through their work. The fellows receive a $625,000 "no-strings-attached" grant over five years to use in any way they see fit.</p>
<p>"Both Kevin and David are distinguished researchers who work at the intersection of many scientific disciplines, where they can draw upon multiple approaches to find creative solutions to some of our greatest challenges – whether it is feeding the world or the possible impacts of ecological changes on the evolution of plant life," said Stanford President John Hennessy and Provost John Etchemendy in a joint statement. " We couldn\'t be more pleased that this multidisciplinary strength has been recognized in the awarding of two MacArthur Fellowships to our accomplished faculty in the School of Earth Sciences."</p>
<p>David Lobell: "Climate change is one of the reasons for concern about feeding people in the future, but it\'s not insurmountable."</p>
<p>A pioneer of the emerging field of crop informatics, Lobell is revolutionizing the understanding of the environmental factors controlling crop yields, with a particular emphasis on adaptation to climate change. His work provides decision makers, for the first time, with critical information about how to adapt agricultural development to climate change.</p>
<p>"I was completely surprised by this recognition, but am really excited by the opportunity it presents," said Lobell, who in addition to his faculty position is associate director of the Center on Food Security and the Environment at Stanford, a joint center of the Freeman Spogli Institute and the Stanford Woods Institute for the Environment.  "To have the MacArthur Foundation recognize the value of taking new approaches and the importance of the topics of hunger and food production is deeply gratifying."</p>
<p>Lobell\'s research focuses on identifying opportunities to increase yields of crops including wheat and corn in major agricultural regions, with projects currently underway in Africa, South Asia, Mexico and the United States.  "I\'m interested in how to feed the world and protect the environment at the same time," he said. "While there are many theories about how to do that, my work tries to test these theories, often using data that were collected for completely different reasons."</p>
<p>The citation emphasized Lobell\'s work on understanding the risks of climate change, and options for adaptation. "Climate change is one of the reasons for concern about feeding people in the future, but it\'s not insurmountable if good decisions are made," he said. </p>
<p>When asked how he would use the funding, Lobell said he would not rush the decision. He said that some of the award would likely relieve him of writing grant proposals. In addition, he said he would consider using some toward more travel. "A lot of my better ideas in the past have started with travel and interactions with international collaborations," he said.  "And there\'s always a tradeoff between my work travel and family.  I now might take my wife and young sons with me on some extended trips."</p>
<p>Widely sought throughout the world to provide expert advice, Lobell is a lead author for the Intergovernmental Panel on Climate Change Fifth Assessment Report chapter on food security, to be published in 2014. </p>
<p>Lobell studied applied mathematics at Brown University, and before receiving his bachelor\'s degree in 2000, he spent the summer of 1999 as a research intern at Stanford, developing remote sensing algorithms. He then pursued graduate studies at Stanford, receiving his doctorate in geological and environmental sciences in 2005. He was a postdoctoral fellow at Lawrence Livermore National Laboratory from 2005-2007, and returned to Stanford as a senior research scholar in the Program on Food Security and the Environment in 2008-2009.  He accepted an appointment as assistant professor in the Stanford School of Earth Sciences in 2009. </p>
<p>In addition to his research, Lobell teaches several courses open to both undergraduates and graduate students, including "Feeding Nine Billion," "Climate and Agriculture," and "Global Land Use to 2050," as well as modeling and statistical methods classes.</p>
<p>Lobell received a NASA New Investigator Program Award for 2008-2011. He received the James B. Macelwane Medal from the American Geophysical Union in 2010, awarded for significant contributions to the geophysical sciences by an outstanding scientist under the age of 36.</p>
<p>Kevin Boyce: "The evolution of plants is the evolution of the Earth\'s surface."</p>
<p>Boyce is a paleontologist whose studies of both extinct and living plants across multiple timescales are establishing direct links between ancient remains and present-day ecosystems and advancing the understanding of potential ecological changes.  He has emerged as a leader in a new subfield of paleontology that brings patterns of development and physiological processes of living organisms to bear on the study of fossils.</p>
<p>"Plants represent most of the Earth\'s biomass and they strongly influence global chemical cycling, climate, atmospheric composition, sedimentary processes, etc.," Boyce said.  "So, in a real sense, the evolution of plants is the evolution of the Earth\'s surface."</p>
<p>In collaboration with colleagues in plant physiology, and climate science, Boyce has advanced interpretations of how major plant components have evolved by using such modern technology as X-ray spectromicroscopy to examine plant specimens at the tissue and cellular level. The MacArthur award cited Boyce for solving mysteries about the morphology of plants that have puzzled scientists for decades and establishing macroecological perspectives of emergent biodiversity, while also challenging evolutionary scientists to embrace new angles of research to advance knowledge and discovery.</p>
<p>"I am surprised to receive the MacArthur fellowship, but am happy to see geobiology and the plant fossil record get attention," Boyce said.  "Often the most interesting projects are the ones that can\'t be funded directly because they are riskier and there is no guaranteed outcome.  An award such as this allows you to focus on the fun stuff."</p>
<p>Boyce received dual degrees in literature and biology from the California Institute of Technology in 1995. He received his doctorate in paleontology in 2001 from Harvard University. From 2001 to 2003, he held a National Research Council Associateship with the NASA Astrobiology Institute. Prior to joining Stanford, he was on the faculty of the University of Chicago from 2003-13, most recently as an associate professor of geophysical sciences.</p>
<p>In the next academic year, he is planning to teach courses including "Evolution of Terrestrial Ecosystems" and "The Evolution of Plant Form and Function."</p>
<p>In 2011, Boyce received the Charles Schuchert Award from the Paletontological Society, presented to scientists under age 40 for early career work reflecting excellence and promise in the science of paleontology.  Concurrently he was named a fellow of the Paleontological Society. He received the William S. Cooper Award from the Ecological Society of America in 2012 in honor of outstanding contributions in the field of biogeography.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 1,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
        'title' => 'Stanford Report',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 72,
        'uuid' => 'dad41187-6745-43bc-b95a-7851a7b2c825',
      ),
      1 => array(
        'tid' => 71,
        'uuid' => 'aaa4a1c8-fb65-4eeb-9bfe-909031f5e18b',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 29,
        'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
      ),
    ),
  ),
  'field_slac_news_date' => array(
    'und' => array(
      0 => array(
        'value' => '2013-04-07 00:00:00',
        'timezone' => 'America/Los_Angeles',
        'timezone_db' => 'America/Los_Angeles',
        'date_type' => 'datetime',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-09-23 13:45:15 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  return $nodes;
}
