<?php
/**
 * @file
 * slac_news_demo.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function slac_news_demo_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'title' => 'World\'s Most Powerful X-ray Laser Beam Refined to Scalpel Precision',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8db12f61-7ae0-42fd-9e69-cbcef31ed24e',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1350157617,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '2cca6931-0a7b-4b97-b003-2f69ec11e8ca',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><strong>Menlo Park, Calif.&nbsp;</strong>&mdash; With a thin sliver of diamond, scientists at the U.S. Department of Energy&rsquo;s (DOE) SLAC National Accelerator Laboratory have transformed the&nbsp;<u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u>&nbsp;into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>

<p>In a process called &ldquo;self-seeding,&rdquo; the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>

<p>&ldquo;The more control you have, the finer the details you can see,&rdquo; said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. &ldquo;People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.&rdquo; Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>

<p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>

<p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>

<p>Without self-seeding these X-ray laser pulses contain&nbsp;<u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u>&nbsp;(or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>

<p>To create a precise X-ray wavelength band and make the LCLS even more &ldquo;laser-like,&rdquo; researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>

<p>Producing the narrower wavelength band is just the beginning. &ldquo;The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators,&quot; said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>

<p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>

<p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>

<p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, &ldquo;the entire group of observers was smiling from ear to ear.&quot; Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, &quot;I was very happy to see it work.&quot;</p>

<p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE&rsquo;s Office of Science.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><strong>Menlo Park, Calif. </strong>— With a thin sliver of diamond, scientists at the U.S. Department of Energy’s (DOE) SLAC National Accelerator Laboratory have transformed the <u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u> into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>
<p>In a process called “self-seeding,” the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>
<p>“The more control you have, the finer the details you can see,” said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. “People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.” Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>
<p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>
<p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>
<p>Without self-seeding these X-ray laser pulses contain <u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u> (or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>
<p>To create a precise X-ray wavelength band and make the LCLS even more “laser-like,” researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>
<p>Producing the narrower wavelength band is just the beginning. “The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators," said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>
<p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>
<p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>
<p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, “the entire group of observers was smiling from ear to ear." Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, "I was very happy to see it work."</p>
<p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE’s Office of Science.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Andy Freeberg, Media Relations Manager
SLAC National Accelerator Laboratory
Office: 650-926-4359
afreeberg@slac.stanford.edu',
        'format' => NULL,
        'safe_value' => 'Andy Freeberg, Media Relations Manager
SLAC National Accelerator Laboratory
Office: 650-926-4359
afreeberg@slac.stanford.edu',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 2,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
        'title' => 'Nature Photonics',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 43,
        'uuid' => '0ce6dd19-dde1-4daa-ae83-1879947970ac',
      ),
      1 => array(
        'tid' => 44,
        'uuid' => '98be32f4-4f1a-4cbc-98be-01c4fc935bf8',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 3,
        'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-10-13 13:46:57 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
    'title' => 'World\'s Most Powerful X-ray Laser Beam Refined to Scalpel Precision',
    'log' => '',
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
    'sticky' => 0,
    'vuuid' => '8db12f61-8ae0-42fd-9e69-cbcef31ed24e',
    'type' => 'slac_news',
    'language' => 'und',
    'created' => 1350157617,
    'tnid' => 0,
    'translate' => 0,
    'uuid' => '2cca6931-8a7b-4b97-b003-2f69ec11e8ca',
    'revision_uid' => 1,
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p><strong>Menlo Park, Calif.&nbsp;</strong>&mdash; With a thin sliver of diamond, scientists at the U.S. Department of Energy&rsquo;s (DOE) SLAC National Accelerator Laboratory have transformed the&nbsp;<u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u>&nbsp;into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>

  <p>In a process called &ldquo;self-seeding,&rdquo; the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>

  <p>&ldquo;The more control you have, the finer the details you can see,&rdquo; said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. &ldquo;People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.&rdquo; Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>

  <p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>

  <p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>

  <p>Without self-seeding these X-ray laser pulses contain&nbsp;<u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u>&nbsp;(or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>

  <p>To create a precise X-ray wavelength band and make the LCLS even more &ldquo;laser-like,&rdquo; researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>

  <p>Producing the narrower wavelength band is just the beginning. &ldquo;The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators,&quot; said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>

  <p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>

  <p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>

  <p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, &ldquo;the entire group of observers was smiling from ear to ear.&quot; Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, &quot;I was very happy to see it work.&quot;</p>

  <p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE&rsquo;s Office of Science.</p>
  ',
          'summary' => '',
          'format' => 'full_html',
          'safe_value' => ' <p><strong>Menlo Park, Calif. </strong>— With a thin sliver of diamond, scientists at the U.S. Department of Energy’s (DOE) SLAC National Accelerator Laboratory have transformed the <u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u> into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>
  <p>In a process called “self-seeding,” the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>
  <p>“The more control you have, the finer the details you can see,” said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. “People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.” Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>
  <p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>
  <p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>
  <p>Without self-seeding these X-ray laser pulses contain <u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u> (or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>
  <p>To create a precise X-ray wavelength band and make the LCLS even more “laser-like,” researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>
  <p>Producing the narrower wavelength band is just the beginning. “The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators," said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>
  <p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>
  <p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>
  <p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, “the entire group of observers was smiling from ear to ear." Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, "I was very happy to see it work."</p>
  <p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE’s Office of Science.</p>
   ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_slac_news_citation' => array(),
    'field_slac_news_contact' => array(
      'und' => array(
        0 => array(
          'value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
          'format' => NULL,
          'safe_value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
        ),
      ),
    ),
    'field_slac_news_media' => array(
      'und' => array(
        0 => array(
          'fid' => 2,
          'title' => NULL,
          'data' => NULL,
        ),
      ),
    ),
    'field_slac_news_source' => array(
      'und' => array(
        0 => array(
          'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
          'title' => 'Nature Photonics',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slac_news_tags' => array(
      'und' => array(
        0 => array(
          'tid' => 43,
          'uuid' => '0ce6dd19-dde1-4daa-ae83-1879947970ac',
        ),
        1 => array(
          'tid' => 44,
          'uuid' => '98be32f4-4f1a-4cbc-98be-01c4fc935bf8',
        ),
      ),
    ),
    'field_slac_news_type' => array(
      'und' => array(
        0 => array(
          'tid' => 3,
          'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
        ),
      ),
    ),
    'metatags' => array(),
    'rdf_mapping' => array(
      'rdftype' => array(
        0 => 'sioc:Item',
        1 => 'foaf:Document',
      ),
      'title' => array(
        'predicates' => array(
          0 => 'dc:title',
        ),
      ),
      'created' => array(
        'predicates' => array(
          0 => 'dc:date',
          1 => 'dc:created',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'changed' => array(
        'predicates' => array(
          0 => 'dc:modified',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'body' => array(
        'predicates' => array(
          0 => 'content:encoded',
        ),
      ),
      'uid' => array(
        'predicates' => array(
          0 => 'sioc:has_creator',
        ),
        'type' => 'rel',
      ),
      'name' => array(
        'predicates' => array(
          0 => 'foaf:name',
        ),
      ),
      'comment_count' => array(
        'predicates' => array(
          0 => 'sioc:num_replies',
        ),
        'datatype' => 'xsd:integer',
      ),
      'last_activity' => array(
        'predicates' => array(
          0 => 'sioc:last_activity_date',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
    ),
    'cid' => 0,
    'last_comment_name' => NULL,
    'last_comment_uid' => 0,
    'comment_count' => 0,
    'name' => 'James Smith',
    'picture' => 0,
    'date' => '2012-10-13 13:46:57 -0600',
    'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
  );
  $nodes[] = array(
    'title' => 'World\'s Most Powerful X-ray Laser Beam Refined to Scalpel Precision',
    'log' => '',
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
    'sticky' => 0,
    'vuuid' => '8db32f61-8ae0-42fd-9e69-cbcef31ed24e',
    'type' => 'slac_news',
    'language' => 'und',
    'created' => 1350157617,
    'tnid' => 0,
    'translate' => 0,
    'uuid' => '2cca6331-8a7b-4b97-b003-2f69ec11e8ca',
    'revision_uid' => 1,
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p><strong>Menlo Park, Calif.&nbsp;</strong>&mdash; With a thin sliver of diamond, scientists at the U.S. Department of Energy&rsquo;s (DOE) SLAC National Accelerator Laboratory have transformed the&nbsp;<u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u>&nbsp;into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>

  <p>In a process called &ldquo;self-seeding,&rdquo; the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>

  <p>&ldquo;The more control you have, the finer the details you can see,&rdquo; said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. &ldquo;People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.&rdquo; Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>

  <p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>

  <p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>

  <p>Without self-seeding these X-ray laser pulses contain&nbsp;<u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u>&nbsp;(or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>

  <p>To create a precise X-ray wavelength band and make the LCLS even more &ldquo;laser-like,&rdquo; researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>

  <p>Producing the narrower wavelength band is just the beginning. &ldquo;The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators,&quot; said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>

  <p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>

  <p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>

  <p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, &ldquo;the entire group of observers was smiling from ear to ear.&quot; Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, &quot;I was very happy to see it work.&quot;</p>

  <p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE&rsquo;s Office of Science.</p>
  ',
          'summary' => '',
          'format' => 'full_html',
          'safe_value' => ' <p><strong>Menlo Park, Calif. </strong>— With a thin sliver of diamond, scientists at the U.S. Department of Energy’s (DOE) SLAC National Accelerator Laboratory have transformed the <u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u> into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>
  <p>In a process called “self-seeding,” the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>
  <p>“The more control you have, the finer the details you can see,” said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. “People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.” Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>
  <p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>
  <p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>
  <p>Without self-seeding these X-ray laser pulses contain <u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u> (or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>
  <p>To create a precise X-ray wavelength band and make the LCLS even more “laser-like,” researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>
  <p>Producing the narrower wavelength band is just the beginning. “The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators," said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>
  <p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>
  <p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>
  <p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, “the entire group of observers was smiling from ear to ear." Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, "I was very happy to see it work."</p>
  <p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE’s Office of Science.</p>
   ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_slac_news_citation' => array(),
    'field_slac_news_contact' => array(
      'und' => array(
        0 => array(
          'value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
          'format' => NULL,
          'safe_value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
        ),
      ),
    ),
    'field_slac_news_media' => array(
      'und' => array(
        0 => array(
          'fid' => 2,
          'title' => NULL,
          'data' => NULL,
        ),
      ),
    ),
    'field_slac_news_source' => array(
      'und' => array(
        0 => array(
          'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
          'title' => 'Nature Photonics',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slac_news_tags' => array(
      'und' => array(
        0 => array(
          'tid' => 43,
          'uuid' => '0ce6dd19-dde1-4daa-ae83-1879947970ac',
        ),
        1 => array(
          'tid' => 44,
          'uuid' => '98be32f4-4f1a-4cbc-98be-01c4fc935bf8',
        ),
      ),
    ),
    'field_slac_news_type' => array(
      'und' => array(
        0 => array(
          'tid' => 3,
          'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
        ),
      ),
    ),
    'metatags' => array(),
    'rdf_mapping' => array(
      'rdftype' => array(
        0 => 'sioc:Item',
        1 => 'foaf:Document',
      ),
      'title' => array(
        'predicates' => array(
          0 => 'dc:title',
        ),
      ),
      'created' => array(
        'predicates' => array(
          0 => 'dc:date',
          1 => 'dc:created',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'changed' => array(
        'predicates' => array(
          0 => 'dc:modified',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'body' => array(
        'predicates' => array(
          0 => 'content:encoded',
        ),
      ),
      'uid' => array(
        'predicates' => array(
          0 => 'sioc:has_creator',
        ),
        'type' => 'rel',
      ),
      'name' => array(
        'predicates' => array(
          0 => 'foaf:name',
        ),
      ),
      'comment_count' => array(
        'predicates' => array(
          0 => 'sioc:num_replies',
        ),
        'datatype' => 'xsd:integer',
      ),
      'last_activity' => array(
        'predicates' => array(
          0 => 'sioc:last_activity_date',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
    ),
    'cid' => 0,
    'last_comment_name' => NULL,
    'last_comment_uid' => 0,
    'comment_count' => 0,
    'name' => 'James Smith',
    'picture' => 0,
    'date' => '2012-10-13 13:46:57 -0600',
    'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
  );
  $nodes[] = array(
    'title' => 'World\'s Most Powerful X-ray Laser Beam Refined to Scalpel Precision',
    'log' => '',
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
    'sticky' => 0,
    'vuuid' => '8db32f11-8ae0-42fd-9e69-cbcef31ed24e',
    'type' => 'slac_news',
    'language' => 'und',
    'created' => 1350157617,
    'tnid' => 0,
    'translate' => 0,
    'uuid' => '2cca6331-8a1b-4b97-b003-2f69ec11e8ca',
    'revision_uid' => 1,
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p><strong>Menlo Park, Calif.&nbsp;</strong>&mdash; With a thin sliver of diamond, scientists at the U.S. Department of Energy&rsquo;s (DOE) SLAC National Accelerator Laboratory have transformed the&nbsp;<u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u>&nbsp;into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>

  <p>In a process called &ldquo;self-seeding,&rdquo; the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>

  <p>&ldquo;The more control you have, the finer the details you can see,&rdquo; said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. &ldquo;People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.&rdquo; Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>

  <p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>

  <p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>

  <p>Without self-seeding these X-ray laser pulses contain&nbsp;<u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u>&nbsp;(or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>

  <p>To create a precise X-ray wavelength band and make the LCLS even more &ldquo;laser-like,&rdquo; researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>

  <p>Producing the narrower wavelength band is just the beginning. &ldquo;The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators,&quot; said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>

  <p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>

  <p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>

  <p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, &ldquo;the entire group of observers was smiling from ear to ear.&quot; Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, &quot;I was very happy to see it work.&quot;</p>

  <p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE&rsquo;s Office of Science.</p>
  ',
          'summary' => '',
          'format' => 'full_html',
          'safe_value' => ' <p><strong>Menlo Park, Calif. </strong>— With a thin sliver of diamond, scientists at the U.S. Department of Energy’s (DOE) SLAC National Accelerator Laboratory have transformed the <u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u> into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>
  <p>In a process called “self-seeding,” the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>
  <p>“The more control you have, the finer the details you can see,” said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. “People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.” Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>
  <p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>
  <p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>
  <p>Without self-seeding these X-ray laser pulses contain <u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u> (or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>
  <p>To create a precise X-ray wavelength band and make the LCLS even more “laser-like,” researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>
  <p>Producing the narrower wavelength band is just the beginning. “The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators," said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>
  <p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>
  <p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>
  <p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, “the entire group of observers was smiling from ear to ear." Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, "I was very happy to see it work."</p>
  <p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE’s Office of Science.</p>
   ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_slac_news_citation' => array(),
    'field_slac_news_contact' => array(
      'und' => array(
        0 => array(
          'value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
          'format' => NULL,
          'safe_value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
        ),
      ),
    ),
    'field_slac_news_media' => array(
      'und' => array(
        0 => array(
          'fid' => 2,
          'title' => NULL,
          'data' => NULL,
        ),
      ),
    ),
    'field_slac_news_source' => array(
      'und' => array(
        0 => array(
          'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
          'title' => 'Nature Photonics',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slac_news_tags' => array(
      'und' => array(
        0 => array(
          'tid' => 43,
          'uuid' => '0ce6dd19-dde1-4daa-ae83-1879947970ac',
        ),
        1 => array(
          'tid' => 44,
          'uuid' => '98be32f4-4f1a-4cbc-98be-01c4fc935bf8',
        ),
      ),
    ),
    'field_slac_news_type' => array(
      'und' => array(
        0 => array(
          'tid' => 3,
          'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
        ),
      ),
    ),
    'metatags' => array(),
    'rdf_mapping' => array(
      'rdftype' => array(
        0 => 'sioc:Item',
        1 => 'foaf:Document',
      ),
      'title' => array(
        'predicates' => array(
          0 => 'dc:title',
        ),
      ),
      'created' => array(
        'predicates' => array(
          0 => 'dc:date',
          1 => 'dc:created',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'changed' => array(
        'predicates' => array(
          0 => 'dc:modified',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'body' => array(
        'predicates' => array(
          0 => 'content:encoded',
        ),
      ),
      'uid' => array(
        'predicates' => array(
          0 => 'sioc:has_creator',
        ),
        'type' => 'rel',
      ),
      'name' => array(
        'predicates' => array(
          0 => 'foaf:name',
        ),
      ),
      'comment_count' => array(
        'predicates' => array(
          0 => 'sioc:num_replies',
        ),
        'datatype' => 'xsd:integer',
      ),
      'last_activity' => array(
        'predicates' => array(
          0 => 'sioc:last_activity_date',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
    ),
    'cid' => 0,
    'last_comment_name' => NULL,
    'last_comment_uid' => 0,
    'comment_count' => 0,
    'name' => 'James Smith',
    'picture' => 0,
    'date' => '2012-10-13 13:46:57 -0600',
    'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
  );
  $nodes[] = array(
    'title' => 'World\'s Most Powerful X-ray Laser Beam Refined to Scalpel Precision',
    'log' => '',
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
    'sticky' => 0,
    'vuuid' => '8db32f11-0ae0-42fd-9e69-cbcef31ed24e',
    'type' => 'slac_news',
    'language' => 'und',
    'created' => 1350157617,
    'tnid' => 0,
    'translate' => 0,
    'uuid' => '2cca6331-8a1b-0b97-b003-2f69ec11e8ca',
    'revision_uid' => 1,
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p><strong>Menlo Park, Calif.&nbsp;</strong>&mdash; With a thin sliver of diamond, scientists at the U.S. Department of Energy&rsquo;s (DOE) SLAC National Accelerator Laboratory have transformed the&nbsp;<u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u>&nbsp;into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>

  <p>In a process called &ldquo;self-seeding,&rdquo; the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>

  <p>&ldquo;The more control you have, the finer the details you can see,&rdquo; said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. &ldquo;People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.&rdquo; Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>

  <p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>

  <p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>

  <p>Without self-seeding these X-ray laser pulses contain&nbsp;<u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u>&nbsp;(or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>

  <p>To create a precise X-ray wavelength band and make the LCLS even more &ldquo;laser-like,&rdquo; researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>

  <p>Producing the narrower wavelength band is just the beginning. &ldquo;The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators,&quot; said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>

  <p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>

  <p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>

  <p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, &ldquo;the entire group of observers was smiling from ear to ear.&quot; Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, &quot;I was very happy to see it work.&quot;</p>

  <p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE&rsquo;s Office of Science.</p>
  ',
          'summary' => '',
          'format' => 'full_html',
          'safe_value' => ' <p><strong>Menlo Park, Calif. </strong>— With a thin sliver of diamond, scientists at the U.S. Department of Energy’s (DOE) SLAC National Accelerator Laboratory have transformed the <u><a href="http://www-public.slac.stanford.edu/lcls/aboutlcls.aspx" target="_blank">Linac Coherent Light Source (LCLS)</a></u> into an even more precise tool for exploring the nanoworld. The improvements yield laser pulses focused to higher intensity in a much narrower band of X-ray wavelengths, and may enable experiments that have never before been possible.</p>
  <p>In a process called “self-seeding,” the diamond filters the laser beam to a single X-ray color, which is then amplified. Like trading a hatchet for a scalpel, the advance will give researchers more control in studying and manipulating matter at the atomic level and will deliver sharper images of materials, molecules and chemical reactions.</p>
  <p>“The more control you have, the finer the details you can see,” said Jerry Hastings, a SLAC scientist and co-author on the research, published this week in Nature Photonics. “People have been talking about self-seeding for nearly 15 years. The method we incorporated at SLAC was proposed in 2010 by Gianluca Geloni, Vitali Kocharyan and Evgeni Saldin of the European XFEL and DESY research centers in Germany. When our team from SLAC and Argonne National Laboratory built it, we were surprised by how simple, robust and cost-effective the engineering turned out to be.” Hastings added that laboratories around the world are already planning to incorporate this important advance into their own X-ray laser facilities.</p>
  <p>Self-seeding has the potential to produce X-ray pulses with significantly higher intensity than the current LCLS performance. The increased intensity in each pulse could be used to probe deep into complex materials to help answer questions about exotic substances like high-temperature superconductors or intricate electronic states like those found in topological insulators.</p>
  <p>The LCLS generates its laser beam by accelerating bunches of electrons to nearly the speed of light and setting them on a zigzag path with a series of magnets. This forces the electrons to emit X-rays, which are gathered into laser pulses that are a billion times brighter than any available before, and fast enough to scan samples in quadrillionths of a second.</p>
  <p>Without self-seeding these X-ray laser pulses contain <u><a href="https://news.slac.stanford.edu/image/lcls-sase-v-seeded-pulse" target="_blank">a range of wavelengths</a></u> (or colors) in an unpredictable pattern, not all of which experimenters can use. Until now, creating a narrower wavelength band at LCLS meant subtracting the unwanted wavelengths, resulting in a substantial loss of intensity.</p>
  <p>To create a precise X-ray wavelength band and make the LCLS even more “laser-like,” researchers installed a slice of diamond crystal halfway down the 130-meter bank of magnets where the X-rays are generated.</p>
  <p>Producing the narrower wavelength band is just the beginning. “The resulting pulses could pack up to 10 times more intensity when we finish optimizing the system and add more undulators," said Zhirong Huang, a SLAC accelerator physicist and co-author, who has been a major contributor to the project.</p>
  <p>LCLS has already begun accepting proposals to use self-seeding for future experiments.</p>
  <p>The first tests of the LCLS self-seeding system have generated intense excitement among scientists the world over. Representatives from other X-ray laser facilities, including Swiss FEL, SACLA in Japan and the European XFEL, came to help, and also learn how to implement it at their own sites.</p>
  <p>According to Paul Emma, a co-author who was a key figure in the original commissioning of the LCLS and in implementing self-seeding, “the entire group of observers was smiling from ear to ear." Emma, now working at Lawrence Berkeley National Lab, has a history of making tough jobs look easy, but he would only say, "I was very happy to see it work."</p>
  <p>The team included collaborators from the Technical Institute for Superhard and Novel Carbon Materials in Troitsk, Russia, which supplied the diamond filter, and Argonne National Laboratory, which designed the vacuum chamber to house it and the precision motion controls to adjust it. The research was supported by the DOE’s Office of Science.</p>
   ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_slac_news_citation' => array(),
    'field_slac_news_contact' => array(
      'und' => array(
        0 => array(
          'value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
          'format' => NULL,
          'safe_value' => 'Andy Freeberg, Media Relations Manager
  SLAC National Accelerator Laboratory
  Office: 650-926-4359
  afreeberg@slac.stanford.edu',
        ),
      ),
    ),
    'field_slac_news_media' => array(
      'und' => array(
        0 => array(
          'fid' => 2,
          'title' => NULL,
          'data' => NULL,
        ),
      ),
    ),
    'field_slac_news_source' => array(
      'und' => array(
        0 => array(
          'url' => 'http://www.nature.com/nphoton/journal/vaop/ncurrent/pdf/nphoton.2012.180.pdf',
          'title' => 'Nature Photonics',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slac_news_tags' => array(
      'und' => array(
        0 => array(
          'tid' => 43,
          'uuid' => '0ce6dd19-dde1-4daa-ae83-1879947970ac',
        ),
        1 => array(
          'tid' => 44,
          'uuid' => '98be32f4-4f1a-4cbc-98be-01c4fc935bf8',
        ),
      ),
    ),
    'field_slac_news_type' => array(
      'und' => array(
        0 => array(
          'tid' => 3,
          'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
        ),
      ),
    ),
    'metatags' => array(),
    'rdf_mapping' => array(
      'rdftype' => array(
        0 => 'sioc:Item',
        1 => 'foaf:Document',
      ),
      'title' => array(
        'predicates' => array(
          0 => 'dc:title',
        ),
      ),
      'created' => array(
        'predicates' => array(
          0 => 'dc:date',
          1 => 'dc:created',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'changed' => array(
        'predicates' => array(
          0 => 'dc:modified',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'body' => array(
        'predicates' => array(
          0 => 'content:encoded',
        ),
      ),
      'uid' => array(
        'predicates' => array(
          0 => 'sioc:has_creator',
        ),
        'type' => 'rel',
      ),
      'name' => array(
        'predicates' => array(
          0 => 'foaf:name',
        ),
      ),
      'comment_count' => array(
        'predicates' => array(
          0 => 'sioc:num_replies',
        ),
        'datatype' => 'xsd:integer',
      ),
      'last_activity' => array(
        'predicates' => array(
          0 => 'sioc:last_activity_date',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
    ),
    'cid' => 0,
    'last_comment_name' => NULL,
    'last_comment_uid' => 0,
    'comment_count' => 0,
    'name' => 'James Smith',
    'picture' => 0,
    'date' => '2012-10-13 13:46:57 -0600',
    'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
  );
  $nodes[] = array(
  'title' => 'Will 2-D Tin be the Next Super Material?',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'd56d508d-12ea-49c5-a7bf-ca78cf591bd6',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1354436526,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'a2007803-a627-4cc4-9d06-51646486bbca',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><em>Menlo Park, Calif.</em> &mdash; A single layer of tin atoms could be the world&rsquo;s first material to conduct electricity with 100 percent efficiency at the temperatures that computer chips operate, according to a team of theoretical physicists led by researchers from the U.S. Department of Energy&rsquo;s (DOE) SLAC National Accelerator Laboratory and Stanford University.</p>

<p>Researchers call the new material &quot;stanene,&quot; combining the Latin name for tin (<em>stannum</em>) with the suffix used in graphene, another single-layer material whose novel electrical properties hold promise for a wide range of applications.</p>

<p>&quot;Stanene could increase the speed and lower the power needs of future generations of computer chips, if our prediction is confirmed by experiments that are underway in several laboratories around the world,&quot; said the team leader, Shoucheng Zhang, a physics professor at Stanford and the Stanford Institute for Materials and Energy Sciences (SIMES), a joint institute with SLAC. The team&rsquo;s work was <a href="http://prl.aps.org/abstract/PRL/v111/i13/e136804">published recently in <em>Physical Review Letters</em></a>.</p>

<p><strong>The Path to Stanene</strong></p>

<p>For the past decade, Zhang and colleagues have been calculating and predicting the electronic properties of a special class of materials known as topological insulators, which conduct electricity only on their outside edges or surfaces and not through their interiors. When topological insulators are just one atom thick, their edges conduct electricity with 100 percent efficiency. These unusual properties result from complex interactions between the electrons and nuclei of heavy atoms in the materials.</p>

<p>&ldquo;The magic of topological insulators is that by their very nature, they force electrons to move in defined lanes without any speed limit, like the German autobahn,&rdquo; Zhang said. &ldquo;As long as they&rsquo;re on the freeway &ndash; the edges or surfaces &ndash; the electrons will travel without resistance.&rdquo;</p>

<p>In 2006 and 2009, Zhang&rsquo;s group predicted that mercury telluride and several combinations of bismuth, antimony, selenium and tellurium should be topological insulators, and they were soon proven right in experiments performed by others. But none of those materials is a perfect conductor of electricity at room temperature, limiting their potential for commercial applications.</p>

<p>Earlier this year, visiting scientist Yong Xu, who is now at Tsinghua University in Beijing, collaborated with Zhang&rsquo;s group to consider the properties of a single layer of pure tin.</p>

<p><span>&ldquo;We knew we should be looking at elements in the lower-right portion of the periodic table,&rdquo; Xu said. &ldquo;All previous topological insulators have involved the heavy and electron-rich elements located there.&rdquo;</span></p>

<p>Their calculations indicated that a single layer of tin would be a topological insulator at and above room temperature, and that adding fluorine atoms to the tin would extend its operating range to at least 100 degrees Celsius (212 degrees Fahrenheit).</p>

<p><strong>Ultimately a Substitute for Silicon?</strong></p>

<p>Zhang said the first application for this stanene-fluorine combination could be in wiring that connects the many sections of a microprocessor, allowing electrons to flow as freely as cars on a highway. Traffic congestion would still occur at on- and off-ramps made of conventional conductors, he said. But stanene wiring should significantly reduce the power consumption and heat production of microprocessors.</p>

<p><span>Manufacturing challenges include ensuring that only a single layer of tin is deposited and keeping that single layer intact during high-temperature chip-making processes.</span></p>

<p>&ldquo;Eventually, we can imagine stanene being used for many more circuit structures, including replacing silicon in the hearts of transistors,&rdquo; Zhang said. &ldquo;Someday we might even call this area Tin Valley rather than Silicon Valley.&rdquo;</p>

<p>Additional contributors included researchers from Tsinghua University in Beijing and the Max Planck Institute for Chemical Physics of Solids in Dresden, Germany. The research was supported by the Mesodynamic Architectures program of the Defense Advanced Research Projects Agency.</p>

<p><em>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science. To learn more, please visit </em><a href="http://www.slac.stanford.edu"><em>www.slac.stanford.edu</em></a><em>.</em></p>

<p><em>The Stanford Institute for Materials and Energy Sciences (SIMES) is a joint institute of SLAC National Accelerator Laboratory and Stanford University. SIMES studies the nature, properties and synthesis of complex and novel materials in the effort to create clean, renewable energy technologies. For more information, please visit </em><a href="http://simes.slac.stanford.edu/"><em>simes.slac.stanford.edu</em></a><em>.</em></p>

<p><em>DOE&rsquo;s Office of Science is the single largest supporter of basic research in the physical sciences in the United States, and is working to address some of the most pressing challenges of our time. For more information, please visit </em><a href="http://science.energy.gov/"><em>science.energy.gov</em></a><em>.</em></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><em>Menlo Park, Calif.</em> — A single layer of tin atoms could be the world’s first material to conduct electricity with 100 percent efficiency at the temperatures that computer chips operate, according to a team of theoretical physicists led by researchers from the U.S. Department of Energy’s (DOE) SLAC National Accelerator Laboratory and Stanford University.</p>
<p>Researchers call the new material "stanene," combining the Latin name for tin (<em>stannum</em>) with the suffix used in graphene, another single-layer material whose novel electrical properties hold promise for a wide range of applications.</p>
<p>"Stanene could increase the speed and lower the power needs of future generations of computer chips, if our prediction is confirmed by experiments that are underway in several laboratories around the world," said the team leader, Shoucheng Zhang, a physics professor at Stanford and the Stanford Institute for Materials and Energy Sciences (SIMES), a joint institute with SLAC. The team’s work was <a href="http://prl.aps.org/abstract/PRL/v111/i13/e136804">published recently in <em>Physical Review Letters</em></a>.</p>
<p><strong>The Path to Stanene</strong></p>
<p>For the past decade, Zhang and colleagues have been calculating and predicting the electronic properties of a special class of materials known as topological insulators, which conduct electricity only on their outside edges or surfaces and not through their interiors. When topological insulators are just one atom thick, their edges conduct electricity with 100 percent efficiency. These unusual properties result from complex interactions between the electrons and nuclei of heavy atoms in the materials.</p>
<p>“The magic of topological insulators is that by their very nature, they force electrons to move in defined lanes without any speed limit, like the German autobahn,” Zhang said. “As long as they’re on the freeway – the edges or surfaces – the electrons will travel without resistance.”</p>
<p>In 2006 and 2009, Zhang’s group predicted that mercury telluride and several combinations of bismuth, antimony, selenium and tellurium should be topological insulators, and they were soon proven right in experiments performed by others. But none of those materials is a perfect conductor of electricity at room temperature, limiting their potential for commercial applications.</p>
<p>Earlier this year, visiting scientist Yong Xu, who is now at Tsinghua University in Beijing, collaborated with Zhang’s group to consider the properties of a single layer of pure tin.</p>
<p><span>“We knew we should be looking at elements in the lower-right portion of the periodic table,” Xu said. “All previous topological insulators have involved the heavy and electron-rich elements located there.”</span></p>
<p>Their calculations indicated that a single layer of tin would be a topological insulator at and above room temperature, and that adding fluorine atoms to the tin would extend its operating range to at least 100 degrees Celsius (212 degrees Fahrenheit).</p>
<p><strong>Ultimately a Substitute for Silicon?</strong></p>
<p>Zhang said the first application for this stanene-fluorine combination could be in wiring that connects the many sections of a microprocessor, allowing electrons to flow as freely as cars on a highway. Traffic congestion would still occur at on- and off-ramps made of conventional conductors, he said. But stanene wiring should significantly reduce the power consumption and heat production of microprocessors.</p>
<p><span>Manufacturing challenges include ensuring that only a single layer of tin is deposited and keeping that single layer intact during high-temperature chip-making processes.</span></p>
<p>“Eventually, we can imagine stanene being used for many more circuit structures, including replacing silicon in the hearts of transistors,” Zhang said. “Someday we might even call this area Tin Valley rather than Silicon Valley.”</p>
<p>Additional contributors included researchers from Tsinghua University in Beijing and the Max Planck Institute for Chemical Physics of Solids in Dresden, Germany. The research was supported by the Mesodynamic Architectures program of the Defense Advanced Research Projects Agency.</p>
<p><em>SLAC is a multi-program laboratory exploring frontier questions in photon science, astrophysics, particle physics and accelerator research. Located in Menlo Park, California, SLAC is operated by Stanford University for the U.S. Department of Energy Office of Science. To learn more, please visit </em><a href="http://www.slac.stanford.edu"><em>www.slac.stanford.edu</em></a><em>.</em></p>
<p><em>The Stanford Institute for Materials and Energy Sciences (SIMES) is a joint institute of SLAC National Accelerator Laboratory and Stanford University. SIMES studies the nature, properties and synthesis of complex and novel materials in the effort to create clean, renewable energy technologies. For more information, please visit </em><a href="http://simes.slac.stanford.edu/"><em>simes.slac.stanford.edu</em></a><em>.</em></p>
<p><em>DOE’s Office of Science is the single largest supporter of basic research in the physical sciences in the United States, and is working to address some of the most pressing challenges of our time. For more information, please visit </em><a href="http://science.energy.gov/"><em>science.energy.gov</em></a><em>.</em></p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(
    'und' => array(
      0 => array(
        'value' => '<p><a href="http://prl.aps.org/abstract/PRL/v111/i13/e136804">Yong Xu <em>et al</em>., <em>Physical Review Letters</em>, 27 Sept 2013 (10.1103/PhysRevLett.111.136804)</a></p>
',
        'format' => 'full_html',
        'safe_value' => ' <p><a href="http://prl.aps.org/abstract/PRL/v111/i13/e136804">Yong Xu <em>et al</em>., <em>Physical Review Letters</em>, 27 Sept 2013 (10.1103/PhysRevLett.111.136804)</a></p>
 ',
      ),
    ),
  ),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Shoucheng Zhang, SLAC / Stanford University: sczhang@stanford.edu, (650) 723-2894 ',
        'format' => NULL,
        'safe_value' => 'Shoucheng Zhang, SLAC / Stanford University: sczhang@stanford.edu, (650) 723-2894 ',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 1,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'https://www6.slac.stanford.edu/news/2013-11-21-tin-super-material-stanene.aspx',
        'title' => 'SLAC',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 4,
        'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2012-12-02 01:22:06 -0700',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Scientists Prove X-ray Laser Can Solve Protein Structures from Scratch',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '6c5ef37d-c299-4397-b2fd-2e589faca227',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1385972261,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'da567b81-da7d-48ac-ac1a-bc1e51e5478b',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><em>Menlo Park, Calif. &mdash;</em> A study shows for the first time that X-ray lasers can be used to generate a complete 3-D model of a protein without any prior knowledge of its structure.</p>

<p>An international team of researchers working at the Department of Energy&#39;s (DOE) SLAC National Accelerator Laboratory produced from scratch an accurate model of lysozyme, a well-studied enzyme found in egg whites, using the Linac Coherent Light Source (LCLS) X-ray laser and sophisticated computer analysis tools.</p>

<p>The experiment proves that X-ray lasers can play a leading role in studying important biomolecules of unknown structure. The special attributes of LCLS, which allow the study of very small crystals, could cement its role in hunting down many important biological structures that have so far remained out of reach because they form crystals too small for analysis with conventional X-ray sources.</p>

<p>&quot;Determining protein structures using X-ray lasers requires averaging a gigantic amount of data to get a sufficiently accurate signal, and people wondered if this really could be done,&rdquo; said Thomas Barends, a staff scientist at the Max Planck Institute for Medical Research in Germany who participated in the research. &quot;Now we have experimental evidence. This really opens the door to new discoveries.&quot;</p>

<p>Collaborators from SLAC and Arizona State University also participated in the research, which was <a href="http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12773.html" target="_blank">published Nov. 24 in <em>Nature</em></a><em>.</em></p>

<p>The underlying technique, called X-ray crystallography, is credited with solving the vast majority of all known protein structures and is <a href="http://www.iucr.org/people/nobel-prize">associated with numerous Nobel Prizes</a> since its first use just over a century ago.</p>

<p>Protein structures tie directly to their functions, such as how they bind and interact with other molecules, and thus provide vital details for developing highly targeted disease-fighting drugs. But many protein structures that are considered promising targets for new medicines remain unknown, mainly because they don&#39;t form crystals that can be deciphered with existing techniques.</p>

<p>This work is the latest in a rapid progression of important advances at LCLS, which began operations for users in 2010. For example, <a href="https://www6.slac.stanford.edu/news/2012-11-29-sleepingsickness.aspx">last year</a> researchers used LCLS to determine the structure of an enzyme that can hold African sleeping sickness in check, which makes it a promising drug target. However, those previous studies relied on data from similar, known structures to fill in common data gaps.</p>

<p>For this study the researchers chose lysozyme, whose structure has been known for decades, because it offered a good test of whether their method produced accurate results. They soaked lysozyme crystals in a solution containing gadolinium, a metal that bonded with the lysozyme to produce a strong signal when subjected to the intense X-ray light. It was this signal from the gadolinium atoms that enabled exact reconstruction of the lysozyme molecule.</p>

<p>The team hopes to adapt and refine the technique to explore more complex proteins such as membrane proteins, which serve a range of important cellular functions and are the target of more than half of all new drugs in development. Only a small fraction of the thousands of membrane proteins have been completely mapped.</p>

<p>&quot;This study is an important milestone on which the field will build further,&quot; said John R. Helliwell, emeritus professor of chemistry at the University of Manchester and formerly a director of the Synchrotron Radiation Source at Daresbury Laboratory in England. &quot;The X-ray laser is bringing new opportunities and new ideas for 3-D structure determination of ever-smaller samples. The use of computers to automate this process is a triumph.&quot;</p>

<p>Barends said the latest results are a remarkable achievement, given that it took just a few years for LCLS to reach this milestone. &quot;Further improvements in X-ray detectors, software and crystal formation and delivery techniques should enable more discoveries in the coming years,&quot; he said.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p><em>Menlo Park, Calif. —</em> A study shows for the first time that X-ray lasers can be used to generate a complete 3-D model of a protein without any prior knowledge of its structure.</p>
<p>An international team of researchers working at the Department of Energy\'s (DOE) SLAC National Accelerator Laboratory produced from scratch an accurate model of lysozyme, a well-studied enzyme found in egg whites, using the Linac Coherent Light Source (LCLS) X-ray laser and sophisticated computer analysis tools.</p>
<p>The experiment proves that X-ray lasers can play a leading role in studying important biomolecules of unknown structure. The special attributes of LCLS, which allow the study of very small crystals, could cement its role in hunting down many important biological structures that have so far remained out of reach because they form crystals too small for analysis with conventional X-ray sources.</p>
<p>"Determining protein structures using X-ray lasers requires averaging a gigantic amount of data to get a sufficiently accurate signal, and people wondered if this really could be done,” said Thomas Barends, a staff scientist at the Max Planck Institute for Medical Research in Germany who participated in the research. "Now we have experimental evidence. This really opens the door to new discoveries."</p>
<p>Collaborators from SLAC and Arizona State University also participated in the research, which was <a href="http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12773.html" target="_blank">published Nov. 24 in <em>Nature</em></a><em>.</em></p>
<p>The underlying technique, called X-ray crystallography, is credited with solving the vast majority of all known protein structures and is <a href="http://www.iucr.org/people/nobel-prize">associated with numerous Nobel Prizes</a> since its first use just over a century ago.</p>
<p>Protein structures tie directly to their functions, such as how they bind and interact with other molecules, and thus provide vital details for developing highly targeted disease-fighting drugs. But many protein structures that are considered promising targets for new medicines remain unknown, mainly because they don\'t form crystals that can be deciphered with existing techniques.</p>
<p>This work is the latest in a rapid progression of important advances at LCLS, which began operations for users in 2010. For example, <a href="https://www6.slac.stanford.edu/news/2012-11-29-sleepingsickness.aspx">last year</a> researchers used LCLS to determine the structure of an enzyme that can hold African sleeping sickness in check, which makes it a promising drug target. However, those previous studies relied on data from similar, known structures to fill in common data gaps.</p>
<p>For this study the researchers chose lysozyme, whose structure has been known for decades, because it offered a good test of whether their method produced accurate results. They soaked lysozyme crystals in a solution containing gadolinium, a metal that bonded with the lysozyme to produce a strong signal when subjected to the intense X-ray light. It was this signal from the gadolinium atoms that enabled exact reconstruction of the lysozyme molecule.</p>
<p>The team hopes to adapt and refine the technique to explore more complex proteins such as membrane proteins, which serve a range of important cellular functions and are the target of more than half of all new drugs in development. Only a small fraction of the thousands of membrane proteins have been completely mapped.</p>
<p>"This study is an important milestone on which the field will build further," said John R. Helliwell, emeritus professor of chemistry at the University of Manchester and formerly a director of the Synchrotron Radiation Source at Daresbury Laboratory in England. "The X-ray laser is bringing new opportunities and new ideas for 3-D structure determination of ever-smaller samples. The use of computers to automate this process is a triumph."</p>
<p>Barends said the latest results are a remarkable achievement, given that it took just a few years for LCLS to reach this milestone. "Further improvements in X-ray detectors, software and crystal formation and delivery techniques should enable more discoveries in the coming years," he said.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(
    'und' => array(
      0 => array(
        'value' => '<p><a href="http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12773.html" target="_blank">T. Barends et al., Nature, 24 November 2013 (10.1038/nature12773)</a></p>
',
        'format' => 'full_html',
        'safe_value' => ' <p><a href="http://www.nature.com/nature/journal/vaop/ncurrent/full/nature12773.html" target="_blank">T. Barends et al., Nature, 24 November 2013 (10.1038/nature12773)</a></p>
 ',
      ),
    ),
  ),
  'field_slac_news_contact' => array(
    'und' => array(
      0 => array(
        'value' => 'Thomas Barends, Max Planck Institute for Medical Research: Thomas.Barends@mpimf-heidelberg.mpg.de
Ilme Schlichting, Max Planck Institute for Medical Research: Ilme.Schlichting@mpimf-heidelberg.mpg.de
Sebastien Boutet, SLAC National Accelerator Laboratory: sboutet@slac.stanford.edu',
        'format' => NULL,
        'safe_value' => 'Thomas Barends, Max Planck Institute for Medical Research: Thomas.Barends@mpimf-heidelberg.mpg.de
Ilme Schlichting, Max Planck Institute for Medical Research: Ilme.Schlichting@mpimf-heidelberg.mpg.de
Sebastien Boutet, SLAC National Accelerator Laboratory: sboutet@slac.stanford.edu',
      ),
    ),
  ),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 2,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'https://www6.slac.stanford.edu/news/2013-11-24-x-ray-laser-solves-protein-structure-from-scratch.aspx',
        'title' => 'SLAC',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 3,
        'uuid' => '05339b25-6cf8-4e75-b4ea-f91d490f5b04',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2013-12-02 01:17:41 -0700',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
  $nodes[] = array(
  'title' => 'Disorder can improve the performance of plastic solar cells, Stanford scientists say',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8e26bc1e-be6e-47b2-af31-9780bb060506',
  'type' => 'slac_news',
  'language' => 'und',
  'created' => 1366055115,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'eb850fab-95d9-45dc-9e52-9c4901fbad53',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>

<p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers&#39; performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal&nbsp;<a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>

<p>&quot;People used to think that if you made the polymers more like silicon they would perform better,&quot; said study co-author&nbsp;<a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. &quot;But we found that polymers don&#39;t naturally form nice, well-ordered crystals. They form small, disordered ones, and that&#39;s perfectly fine.&quot;</p>

<p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>

<h3><strong>Speedy electrons</strong></h3>

<p><strong>&nbsp;</strong>In the study, the Stanford team focused on a class of organic materials known as&nbsp;<a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a>&nbsp;&ndash; chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>

<p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren&#39;t buildings today covered with plastic solar cells?</p>

<p>&quot;One reason they haven&#39;t been commercialized is because of poor performance,&quot; Salleo said. &quot;In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility.&quot;</p>

<p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. &quot;Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor,&quot; Salleo said. &quot;Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones.&quot;</p>

<h3><strong>X-ray analysis</strong></h3>

<p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the&nbsp;<a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a>&nbsp;for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>

<p>&quot;The crystals were so small and disordered you could barely infer their presence from X-rays,&quot; Salleo said. &quot;In fact, scientists had assumed they weren&#39;t there.&quot;</p>

<p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>

<p>&quot;Being small enables a charged electron to go through one crystal and rapidly move on to the next one,&quot; he said. &quot;The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals.&quot;</p>

<p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>

<p>&quot;Our conclusion is that you don&#39;t need to make something so rigid that it forms large crystals,&quot; Salleo said. &quot;You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>

<p>&quot;In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn&#39;t know why they worked so well,&quot; he said. &quot;Now that they know, they can go out and design even better ones.&quot;</p>

<p>And Salleo offered a final piece of advice. &quot;Try to design a material that can live with as much disorder as possible,&quot; he said. &quot;Take the disorder for granted. Personally, I really like disorder. Just look at my office.&quot;</p>

<p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of&nbsp;<a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of&nbsp;<a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC&nbsp;<a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>

<p>The study was supported by a Stanford&nbsp;<a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a>&nbsp;award from the King Abdullah University of Science and Technology; and by the&nbsp;<a href="http://erc.europa.eu/">European Research Council</a>.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>
<p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers\' performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal <a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>
<p>"People used to think that if you made the polymers more like silicon they would perform better," said study co-author <a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. "But we found that polymers don\'t naturally form nice, well-ordered crystals. They form small, disordered ones, and that\'s perfectly fine."</p>
<p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>
<h3><strong>Speedy electrons</strong></h3>
<p><strong> </strong>In the study, the Stanford team focused on a class of organic materials known as <a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a> – chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>
<p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren\'t buildings today covered with plastic solar cells?</p>
<p>"One reason they haven\'t been commercialized is because of poor performance," Salleo said. "In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility."</p>
<p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. "Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor," Salleo said. "Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones."</p>
<h3><strong>X-ray analysis</strong></h3>
<p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the <a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a> for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>
<p>"The crystals were so small and disordered you could barely infer their presence from X-rays," Salleo said. "In fact, scientists had assumed they weren\'t there."</p>
<p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>
<p>"Being small enables a charged electron to go through one crystal and rapidly move on to the next one," he said. "The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals."</p>
<p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>
<p>"Our conclusion is that you don\'t need to make something so rigid that it forms large crystals," Salleo said. "You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>
<p>"In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn\'t know why they worked so well," he said. "Now that they know, they can go out and design even better ones."</p>
<p>And Salleo offered a final piece of advice. "Try to design a material that can live with as much disorder as possible," he said. "Take the disorder for granted. Personally, I really like disorder. Just look at my office."</p>
<p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of <a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of <a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC <a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>
<p>The study was supported by a Stanford <a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a> award from the King Abdullah University of Science and Technology; and by the <a href="http://erc.europa.eu/">European Research Council</a>.</p>
 ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_slac_news_citation' => array(),
  'field_slac_news_contact' => array(),
  'field_slac_news_media' => array(
    'und' => array(
      0 => array(
        'fid' => 1,
        'title' => NULL,
        'data' => NULL,
      ),
    ),
  ),
  'field_slac_news_source' => array(
    'und' => array(
      0 => array(
        'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
        'title' => 'Stanford Report',
        'attributes' => array(),
      ),
    ),
  ),
  'field_slac_news_tags' => array(
    'und' => array(
      0 => array(
        'tid' => 46,
        'uuid' => 'dad41187-6745-43bc-b95a-7851a7b2c825',
      ),
      1 => array(
        'tid' => 45,
        'uuid' => 'aaa4a1c8-fb65-4eeb-9bfe-909031f5e18b',
      ),
    ),
  ),
  'field_slac_news_type' => array(
    'und' => array(
      0 => array(
        'tid' => 4,
        'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
      ),
    ),
  ),
  'metatags' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 0,
  'comment_count' => 0,
  'name' => 'James Smith',
  'picture' => 0,
  'date' => '2013-04-15 13:45:15 -0600',
  'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
);
    $nodes[] = array(
    'title' => 'Disorder can improve the performance of plastic solar cells, Stanford scientists say',
    'log' => '',
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
    'sticky' => 0,
    'vuuid' => '1e26bc1e-be6e-47b2-af31-9780bb060506',
    'type' => 'slac_news',
    'language' => 'und',
    'created' => 1366055115,
    'tnid' => 0,
    'translate' => 0,
    'uuid' => 'bb850fab-95d9-45dc-9e52-9c4901fbad53',
    'revision_uid' => 1,
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>

  <p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers&#39; performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal&nbsp;<a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>

  <p>&quot;People used to think that if you made the polymers more like silicon they would perform better,&quot; said study co-author&nbsp;<a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. &quot;But we found that polymers don&#39;t naturally form nice, well-ordered crystals. They form small, disordered ones, and that&#39;s perfectly fine.&quot;</p>

  <p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>

  <h3><strong>Speedy electrons</strong></h3>

  <p><strong>&nbsp;</strong>In the study, the Stanford team focused on a class of organic materials known as&nbsp;<a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a>&nbsp;&ndash; chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>

  <p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren&#39;t buildings today covered with plastic solar cells?</p>

  <p>&quot;One reason they haven&#39;t been commercialized is because of poor performance,&quot; Salleo said. &quot;In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility.&quot;</p>

  <p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. &quot;Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor,&quot; Salleo said. &quot;Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones.&quot;</p>

  <h3><strong>X-ray analysis</strong></h3>

  <p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the&nbsp;<a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a>&nbsp;for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>

  <p>&quot;The crystals were so small and disordered you could barely infer their presence from X-rays,&quot; Salleo said. &quot;In fact, scientists had assumed they weren&#39;t there.&quot;</p>

  <p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>

  <p>&quot;Being small enables a charged electron to go through one crystal and rapidly move on to the next one,&quot; he said. &quot;The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals.&quot;</p>

  <p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>

  <p>&quot;Our conclusion is that you don&#39;t need to make something so rigid that it forms large crystals,&quot; Salleo said. &quot;You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>

  <p>&quot;In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn&#39;t know why they worked so well,&quot; he said. &quot;Now that they know, they can go out and design even better ones.&quot;</p>

  <p>And Salleo offered a final piece of advice. &quot;Try to design a material that can live with as much disorder as possible,&quot; he said. &quot;Take the disorder for granted. Personally, I really like disorder. Just look at my office.&quot;</p>

  <p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of&nbsp;<a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of&nbsp;<a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC&nbsp;<a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>

  <p>The study was supported by a Stanford&nbsp;<a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a>&nbsp;award from the King Abdullah University of Science and Technology; and by the&nbsp;<a href="http://erc.europa.eu/">European Research Council</a>.</p>
  ',
          'summary' => '',
          'format' => 'full_html',
          'safe_value' => ' <p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>
  <p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers\' performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal <a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>
  <p>"People used to think that if you made the polymers more like silicon they would perform better," said study co-author <a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. "But we found that polymers don\'t naturally form nice, well-ordered crystals. They form small, disordered ones, and that\'s perfectly fine."</p>
  <p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>
  <h3><strong>Speedy electrons</strong></h3>
  <p><strong> </strong>In the study, the Stanford team focused on a class of organic materials known as <a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a> – chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>
  <p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren\'t buildings today covered with plastic solar cells?</p>
  <p>"One reason they haven\'t been commercialized is because of poor performance," Salleo said. "In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility."</p>
  <p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. "Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor," Salleo said. "Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones."</p>
  <h3><strong>X-ray analysis</strong></h3>
  <p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the <a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a> for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>
  <p>"The crystals were so small and disordered you could barely infer their presence from X-rays," Salleo said. "In fact, scientists had assumed they weren\'t there."</p>
  <p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>
  <p>"Being small enables a charged electron to go through one crystal and rapidly move on to the next one," he said. "The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals."</p>
  <p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>
  <p>"Our conclusion is that you don\'t need to make something so rigid that it forms large crystals," Salleo said. "You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>
  <p>"In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn\'t know why they worked so well," he said. "Now that they know, they can go out and design even better ones."</p>
  <p>And Salleo offered a final piece of advice. "Try to design a material that can live with as much disorder as possible," he said. "Take the disorder for granted. Personally, I really like disorder. Just look at my office."</p>
  <p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of <a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of <a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC <a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>
  <p>The study was supported by a Stanford <a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a> award from the King Abdullah University of Science and Technology; and by the <a href="http://erc.europa.eu/">European Research Council</a>.</p>
   ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_slac_news_citation' => array(),
    'field_slac_news_contact' => array(),
    'field_slac_news_media' => array(
      'und' => array(
        0 => array(
          'fid' => 1,
          'title' => NULL,
          'data' => NULL,
        ),
      ),
    ),
    'field_slac_news_source' => array(
      'und' => array(
        0 => array(
          'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
          'title' => 'Stanford Report',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slac_news_tags' => array(
      'und' => array(
        0 => array(
          'tid' => 46,
          'uuid' => 'dad41187-6745-43bc-b95a-7851a7b2c825',
        ),
        1 => array(
          'tid' => 45,
          'uuid' => 'aaa4a1c8-fb65-4eeb-9bfe-909031f5e18b',
        ),
      ),
    ),
    'field_slac_news_type' => array(
      'und' => array(
        0 => array(
          'tid' => 4,
          'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
        ),
      ),
    ),
    'metatags' => array(),
    'rdf_mapping' => array(
      'rdftype' => array(
        0 => 'sioc:Item',
        1 => 'foaf:Document',
      ),
      'title' => array(
        'predicates' => array(
          0 => 'dc:title',
        ),
      ),
      'created' => array(
        'predicates' => array(
          0 => 'dc:date',
          1 => 'dc:created',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'changed' => array(
        'predicates' => array(
          0 => 'dc:modified',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'body' => array(
        'predicates' => array(
          0 => 'content:encoded',
        ),
      ),
      'uid' => array(
        'predicates' => array(
          0 => 'sioc:has_creator',
        ),
        'type' => 'rel',
      ),
      'name' => array(
        'predicates' => array(
          0 => 'foaf:name',
        ),
      ),
      'comment_count' => array(
        'predicates' => array(
          0 => 'sioc:num_replies',
        ),
        'datatype' => 'xsd:integer',
      ),
      'last_activity' => array(
        'predicates' => array(
          0 => 'sioc:last_activity_date',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
    ),
    'cid' => 0,
    'last_comment_name' => NULL,
    'last_comment_uid' => 0,
    'comment_count' => 0,
    'name' => 'James Smith',
    'picture' => 0,
    'date' => '2013-04-15 13:45:15 -0600',
    'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
  );
  $nodes[] = array(
    'title' => 'Disorder can improve the performance of plastic solar cells, Stanford scientists say',
    'log' => '',
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
    'sticky' => 0,
    'vuuid' => '7a26bc1e-be6e-47b2-af31-9780bb060506',
    'type' => 'slac_news',
    'language' => 'und',
    'created' => 1366055115,
    'tnid' => 0,
    'translate' => 0,
    'uuid' => 'er850fab-95d9-45dc-9e52-9c4901fbad53',
    'revision_uid' => 1,
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>

  <p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers&#39; performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal&nbsp;<a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>

  <p>&quot;People used to think that if you made the polymers more like silicon they would perform better,&quot; said study co-author&nbsp;<a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. &quot;But we found that polymers don&#39;t naturally form nice, well-ordered crystals. They form small, disordered ones, and that&#39;s perfectly fine.&quot;</p>

  <p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>

  <h3><strong>Speedy electrons</strong></h3>

  <p><strong>&nbsp;</strong>In the study, the Stanford team focused on a class of organic materials known as&nbsp;<a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a>&nbsp;&ndash; chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>

  <p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren&#39;t buildings today covered with plastic solar cells?</p>

  <p>&quot;One reason they haven&#39;t been commercialized is because of poor performance,&quot; Salleo said. &quot;In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility.&quot;</p>

  <p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. &quot;Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor,&quot; Salleo said. &quot;Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones.&quot;</p>

  <h3><strong>X-ray analysis</strong></h3>

  <p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the&nbsp;<a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a>&nbsp;for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>

  <p>&quot;The crystals were so small and disordered you could barely infer their presence from X-rays,&quot; Salleo said. &quot;In fact, scientists had assumed they weren&#39;t there.&quot;</p>

  <p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>

  <p>&quot;Being small enables a charged electron to go through one crystal and rapidly move on to the next one,&quot; he said. &quot;The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals.&quot;</p>

  <p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>

  <p>&quot;Our conclusion is that you don&#39;t need to make something so rigid that it forms large crystals,&quot; Salleo said. &quot;You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>

  <p>&quot;In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn&#39;t know why they worked so well,&quot; he said. &quot;Now that they know, they can go out and design even better ones.&quot;</p>

  <p>And Salleo offered a final piece of advice. &quot;Try to design a material that can live with as much disorder as possible,&quot; he said. &quot;Take the disorder for granted. Personally, I really like disorder. Just look at my office.&quot;</p>

  <p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of&nbsp;<a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of&nbsp;<a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC&nbsp;<a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>

  <p>The study was supported by a Stanford&nbsp;<a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a>&nbsp;award from the King Abdullah University of Science and Technology; and by the&nbsp;<a href="http://erc.europa.eu/">European Research Council</a>.</p>
  ',
          'summary' => '',
          'format' => 'full_html',
          'safe_value' => ' <p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>
  <p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers\' performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal <a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>
  <p>"People used to think that if you made the polymers more like silicon they would perform better," said study co-author <a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. "But we found that polymers don\'t naturally form nice, well-ordered crystals. They form small, disordered ones, and that\'s perfectly fine."</p>
  <p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>
  <h3><strong>Speedy electrons</strong></h3>
  <p><strong> </strong>In the study, the Stanford team focused on a class of organic materials known as <a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a> – chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>
  <p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren\'t buildings today covered with plastic solar cells?</p>
  <p>"One reason they haven\'t been commercialized is because of poor performance," Salleo said. "In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility."</p>
  <p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. "Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor," Salleo said. "Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones."</p>
  <h3><strong>X-ray analysis</strong></h3>
  <p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the <a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a> for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>
  <p>"The crystals were so small and disordered you could barely infer their presence from X-rays," Salleo said. "In fact, scientists had assumed they weren\'t there."</p>
  <p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>
  <p>"Being small enables a charged electron to go through one crystal and rapidly move on to the next one," he said. "The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals."</p>
  <p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>
  <p>"Our conclusion is that you don\'t need to make something so rigid that it forms large crystals," Salleo said. "You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>
  <p>"In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn\'t know why they worked so well," he said. "Now that they know, they can go out and design even better ones."</p>
  <p>And Salleo offered a final piece of advice. "Try to design a material that can live with as much disorder as possible," he said. "Take the disorder for granted. Personally, I really like disorder. Just look at my office."</p>
  <p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of <a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of <a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC <a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>
  <p>The study was supported by a Stanford <a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a> award from the King Abdullah University of Science and Technology; and by the <a href="http://erc.europa.eu/">European Research Council</a>.</p>
   ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_slac_news_citation' => array(),
    'field_slac_news_contact' => array(),
    'field_slac_news_media' => array(
      'und' => array(
        0 => array(
          'fid' => 1,
          'title' => NULL,
          'data' => NULL,
        ),
      ),
    ),
    'field_slac_news_source' => array(
      'und' => array(
        0 => array(
          'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
          'title' => 'Stanford Report',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slac_news_tags' => array(
      'und' => array(
        0 => array(
          'tid' => 46,
          'uuid' => 'dad41187-6745-43bc-b95a-7851a7b2c825',
        ),
        1 => array(
          'tid' => 45,
          'uuid' => 'aaa4a1c8-fb65-4eeb-9bfe-909031f5e18b',
        ),
      ),
    ),
    'field_slac_news_type' => array(
      'und' => array(
        0 => array(
          'tid' => 4,
          'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
        ),
      ),
    ),
    'metatags' => array(),
    'rdf_mapping' => array(
      'rdftype' => array(
        0 => 'sioc:Item',
        1 => 'foaf:Document',
      ),
      'title' => array(
        'predicates' => array(
          0 => 'dc:title',
        ),
      ),
      'created' => array(
        'predicates' => array(
          0 => 'dc:date',
          1 => 'dc:created',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'changed' => array(
        'predicates' => array(
          0 => 'dc:modified',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'body' => array(
        'predicates' => array(
          0 => 'content:encoded',
        ),
      ),
      'uid' => array(
        'predicates' => array(
          0 => 'sioc:has_creator',
        ),
        'type' => 'rel',
      ),
      'name' => array(
        'predicates' => array(
          0 => 'foaf:name',
        ),
      ),
      'comment_count' => array(
        'predicates' => array(
          0 => 'sioc:num_replies',
        ),
        'datatype' => 'xsd:integer',
      ),
      'last_activity' => array(
        'predicates' => array(
          0 => 'sioc:last_activity_date',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
    ),
    'cid' => 0,
    'last_comment_name' => NULL,
    'last_comment_uid' => 0,
    'comment_count' => 0,
    'name' => 'James Smith',
    'picture' => 0,
    'date' => '2013-04-15 13:45:15 -0600',
    'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
  );
  $nodes[] = array(
    'title' => 'Disorder can improve the performance of plastic solar cells, Stanford scientists say',
    'log' => '',
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
    'sticky' => 0,
    'vuuid' => '7a26bc1e-be2e-47b2-af31-9780bb060506',
    'type' => 'slac_news',
    'language' => 'und',
    'created' => 1366055115,
    'tnid' => 0,
    'translate' => 0,
    'uuid' => 'er850fab-9ad9-45dc-9e52-9c4901fbad53',
    'revision_uid' => 1,
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>

  <p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers&#39; performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal&nbsp;<a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>

  <p>&quot;People used to think that if you made the polymers more like silicon they would perform better,&quot; said study co-author&nbsp;<a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. &quot;But we found that polymers don&#39;t naturally form nice, well-ordered crystals. They form small, disordered ones, and that&#39;s perfectly fine.&quot;</p>

  <p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>

  <h3><strong>Speedy electrons</strong></h3>

  <p><strong>&nbsp;</strong>In the study, the Stanford team focused on a class of organic materials known as&nbsp;<a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a>&nbsp;&ndash; chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>

  <p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren&#39;t buildings today covered with plastic solar cells?</p>

  <p>&quot;One reason they haven&#39;t been commercialized is because of poor performance,&quot; Salleo said. &quot;In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility.&quot;</p>

  <p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. &quot;Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor,&quot; Salleo said. &quot;Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones.&quot;</p>

  <h3><strong>X-ray analysis</strong></h3>

  <p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the&nbsp;<a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a>&nbsp;for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>

  <p>&quot;The crystals were so small and disordered you could barely infer their presence from X-rays,&quot; Salleo said. &quot;In fact, scientists had assumed they weren&#39;t there.&quot;</p>

  <p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>

  <p>&quot;Being small enables a charged electron to go through one crystal and rapidly move on to the next one,&quot; he said. &quot;The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals.&quot;</p>

  <p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>

  <p>&quot;Our conclusion is that you don&#39;t need to make something so rigid that it forms large crystals,&quot; Salleo said. &quot;You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>

  <p>&quot;In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn&#39;t know why they worked so well,&quot; he said. &quot;Now that they know, they can go out and design even better ones.&quot;</p>

  <p>And Salleo offered a final piece of advice. &quot;Try to design a material that can live with as much disorder as possible,&quot; he said. &quot;Take the disorder for granted. Personally, I really like disorder. Just look at my office.&quot;</p>

  <p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of&nbsp;<a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of&nbsp;<a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC&nbsp;<a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>

  <p>The study was supported by a Stanford&nbsp;<a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a>&nbsp;award from the King Abdullah University of Science and Technology; and by the&nbsp;<a href="http://erc.europa.eu/">European Research Council</a>.</p>
  ',
          'summary' => '',
          'format' => 'full_html',
          'safe_value' => ' <p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>
  <p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers\' performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal <a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>
  <p>"People used to think that if you made the polymers more like silicon they would perform better," said study co-author <a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. "But we found that polymers don\'t naturally form nice, well-ordered crystals. They form small, disordered ones, and that\'s perfectly fine."</p>
  <p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>
  <h3><strong>Speedy electrons</strong></h3>
  <p><strong> </strong>In the study, the Stanford team focused on a class of organic materials known as <a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a> – chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>
  <p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren\'t buildings today covered with plastic solar cells?</p>
  <p>"One reason they haven\'t been commercialized is because of poor performance," Salleo said. "In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility."</p>
  <p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. "Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor," Salleo said. "Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones."</p>
  <h3><strong>X-ray analysis</strong></h3>
  <p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the <a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a> for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>
  <p>"The crystals were so small and disordered you could barely infer their presence from X-rays," Salleo said. "In fact, scientists had assumed they weren\'t there."</p>
  <p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>
  <p>"Being small enables a charged electron to go through one crystal and rapidly move on to the next one," he said. "The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals."</p>
  <p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>
  <p>"Our conclusion is that you don\'t need to make something so rigid that it forms large crystals," Salleo said. "You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>
  <p>"In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn\'t know why they worked so well," he said. "Now that they know, they can go out and design even better ones."</p>
  <p>And Salleo offered a final piece of advice. "Try to design a material that can live with as much disorder as possible," he said. "Take the disorder for granted. Personally, I really like disorder. Just look at my office."</p>
  <p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of <a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of <a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC <a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>
  <p>The study was supported by a Stanford <a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a> award from the King Abdullah University of Science and Technology; and by the <a href="http://erc.europa.eu/">European Research Council</a>.</p>
   ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_slac_news_citation' => array(),
    'field_slac_news_contact' => array(),
    'field_slac_news_media' => array(
      'und' => array(
        0 => array(
          'fid' => 1,
          'title' => NULL,
          'data' => NULL,
        ),
      ),
    ),
    'field_slac_news_source' => array(
      'und' => array(
        0 => array(
          'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
          'title' => 'Stanford Report',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slac_news_tags' => array(
      'und' => array(
        0 => array(
          'tid' => 46,
          'uuid' => 'dad41187-6745-43bc-b95a-7851a7b2c825',
        ),
        1 => array(
          'tid' => 45,
          'uuid' => 'aaa4a1c8-fb65-4eeb-9bfe-909031f5e18b',
        ),
      ),
    ),
    'field_slac_news_type' => array(
      'und' => array(
        0 => array(
          'tid' => 4,
          'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
        ),
      ),
    ),
    'metatags' => array(),
    'rdf_mapping' => array(
      'rdftype' => array(
        0 => 'sioc:Item',
        1 => 'foaf:Document',
      ),
      'title' => array(
        'predicates' => array(
          0 => 'dc:title',
        ),
      ),
      'created' => array(
        'predicates' => array(
          0 => 'dc:date',
          1 => 'dc:created',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'changed' => array(
        'predicates' => array(
          0 => 'dc:modified',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'body' => array(
        'predicates' => array(
          0 => 'content:encoded',
        ),
      ),
      'uid' => array(
        'predicates' => array(
          0 => 'sioc:has_creator',
        ),
        'type' => 'rel',
      ),
      'name' => array(
        'predicates' => array(
          0 => 'foaf:name',
        ),
      ),
      'comment_count' => array(
        'predicates' => array(
          0 => 'sioc:num_replies',
        ),
        'datatype' => 'xsd:integer',
      ),
      'last_activity' => array(
        'predicates' => array(
          0 => 'sioc:last_activity_date',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
    ),
    'cid' => 0,
    'last_comment_name' => NULL,
    'last_comment_uid' => 0,
    'comment_count' => 0,
    'name' => 'James Smith',
    'picture' => 0,
    'date' => '2013-04-15 13:45:15 -0600',
    'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
  );
  $nodes[] = array(
    'title' => 'Disorder can improve the performance of plastic solar cells, Stanford scientists say',
    'log' => '',
    'status' => 1,
    'comment' => 1,
    'promote' => 0,
    'sticky' => 0,
    'vuuid' => '1226bc1e-be2e-47b2-af31-9780bb060506',
    'type' => 'slac_news',
    'language' => 'und',
    'created' => 1366055115,
    'tnid' => 0,
    'translate' => 0,
    'uuid' => '9r850fab-9ad9-45dc-9e52-9c4901fbad53',
    'revision_uid' => 1,
    'body' => array(
      'und' => array(
        0 => array(
          'value' => '<p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>

  <p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers&#39; performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal&nbsp;<a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>

  <p>&quot;People used to think that if you made the polymers more like silicon they would perform better,&quot; said study co-author&nbsp;<a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. &quot;But we found that polymers don&#39;t naturally form nice, well-ordered crystals. They form small, disordered ones, and that&#39;s perfectly fine.&quot;</p>

  <p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>

  <h3><strong>Speedy electrons</strong></h3>

  <p><strong>&nbsp;</strong>In the study, the Stanford team focused on a class of organic materials known as&nbsp;<a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a>&nbsp;&ndash; chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>

  <p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren&#39;t buildings today covered with plastic solar cells?</p>

  <p>&quot;One reason they haven&#39;t been commercialized is because of poor performance,&quot; Salleo said. &quot;In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility.&quot;</p>

  <p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. &quot;Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor,&quot; Salleo said. &quot;Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones.&quot;</p>

  <h3><strong>X-ray analysis</strong></h3>

  <p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the&nbsp;<a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a>&nbsp;for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>

  <p>&quot;The crystals were so small and disordered you could barely infer their presence from X-rays,&quot; Salleo said. &quot;In fact, scientists had assumed they weren&#39;t there.&quot;</p>

  <p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>

  <p>&quot;Being small enables a charged electron to go through one crystal and rapidly move on to the next one,&quot; he said. &quot;The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals.&quot;</p>

  <p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>

  <p>&quot;Our conclusion is that you don&#39;t need to make something so rigid that it forms large crystals,&quot; Salleo said. &quot;You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>

  <p>&quot;In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn&#39;t know why they worked so well,&quot; he said. &quot;Now that they know, they can go out and design even better ones.&quot;</p>

  <p>And Salleo offered a final piece of advice. &quot;Try to design a material that can live with as much disorder as possible,&quot; he said. &quot;Take the disorder for granted. Personally, I really like disorder. Just look at my office.&quot;</p>

  <p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of&nbsp;<a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of&nbsp;<a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC&nbsp;<a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>

  <p>The study was supported by a Stanford&nbsp;<a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a>&nbsp;award from the King Abdullah University of Science and Technology; and by the&nbsp;<a href="http://erc.europa.eu/">European Research Council</a>.</p>
  ',
          'summary' => '',
          'format' => 'full_html',
          'safe_value' => ' <p>Scientists have spent decades trying to build flexible plastic solar cells efficient enough to compete with conventional cells made of silicon. To boost performance, research groups have tried creating new plastic materials that enhance the flow of electricity through the solar cell. Several groups expected to achieve good results by redesigning pliant polymers of plastic into orderly, silicon-like crystals, but the flow of electricity did not improve.</p>
  <p>Recently, scientists discovered that disorder at the molecular level actually improves the polymers\' performance. Now Stanford University researchers have an explanation for this surprising result. Their findings, published in the Aug. 4 online edition of the journal <a href="http://www.nature.com/nmat/index.html"><em>Nature Materials</em></a>, could speed up the development of low-cost, commercially available plastic solar cells.</p>
  <p>"People used to think that if you made the polymers more like silicon they would perform better," said study co-author <a href="http://salleo.stanford.edu/">Alberto Salleo</a>, an associate professor of materials science and engineering at Stanford. "But we found that polymers don\'t naturally form nice, well-ordered crystals. They form small, disordered ones, and that\'s perfectly fine."</p>
  <p>Instead of trying to mimic the rigid structure of silicon, Salleo and his colleagues recommend that scientists learn to cope with the inherently disordered nature of plastics.</p>
  <h3><strong>Speedy electrons</strong></h3>
  <p><strong> </strong>In the study, the Stanford team focused on a class of organic materials known as <a href="http://www.nobelprize.org/nobel_prizes/chemistry/laureates/2000/popular.html">conjugated or semiconducting polymers</a> – chains of carbon atoms that have the properties of plastic, and the ability to absorb sunlight and conduct electricity.</p>
  <p>Discovered nearly 40 years ago, semiconducting polymers have long been considered ideal candidates for ultrathin solar cells, light-emitting diodes and transistors. Unlike silicon crystals used in rooftop solar panels, semiconducting polymers are lightweight and can be processed at room temperature with ink-jet printers and other inexpensive techniques. So why aren\'t buildings today covered with plastic solar cells?</p>
  <p>"One reason they haven\'t been commercialized is because of poor performance," Salleo said. "In a solar cell, electrons need to move through the materials fast, but semiconducting polymers have poor electron mobility."</p>
  <p>To find out why, Salleo joined Rodrigo Noriega and Jonathan Rivnay, who were Stanford graduate students at the time, in analyzing more than two decades of experimental data. "Over the years, many people designed stiffer polymers with the goal of making highly organized crystals, but the charge mobility remained relatively poor," Salleo said. "Then several labs created polymers that looked disordered and yet had very high charge mobility. It was a puzzle why these new materials worked better than the more structured crystalline ones."</p>
  <h3><strong>X-ray analysis</strong></h3>
  <p>To observe the disordered materials at the microscopic level, the Stanford team took samples to the <a href="http://slac.stanford.edu/">SLAC National Accelerator Laboratory</a> for X-ray analysis. The X-rays revealed a molecular structure resembling a fingerprint gone awry. Some polymers looked like amorphous strands of spaghetti, while others formed tiny crystals just a few molecules long.</p>
  <p>"The crystals were so small and disordered you could barely infer their presence from X-rays," Salleo said. "In fact, scientists had assumed they weren\'t there."</p>
  <p>By analyzing light emissions from electricity flowing through the samples, the Stanford team determined that numerous small crystals were scattered throughout the material and connected by long polymer chains, like beads in a necklace. The small size of the crystals was a crucial factor in improving overall performance, Salleo said.</p>
  <p>"Being small enables a charged electron to go through one crystal and rapidly move on to the next one," he said. "The long polymer chain then carries the electron quickly through the material. That explains why they have a much higher charge mobility than larger, unconnected crystals."</p>
  <p>Another disadvantage of large crystalline polymers is that they tend to be insoluble and therefore cannot be produced by ink-jet printing or other cheap processing technologies, he added.</p>
  <p>"Our conclusion is that you don\'t need to make something so rigid that it forms large crystals," Salleo said. "You need to design something with small, disordered crystals packed close together and connected by polymer chains. Electrons will move through the crystals like on a superhighway, ignoring the rest of the plastic material, which is amorphous and poorly conducting.</p>
  <p>"In some sense, the synthetic chemists were ahead of us, because they made these new materials but didn\'t know why they worked so well," he said. "Now that they know, they can go out and design even better ones."</p>
  <p>And Salleo offered a final piece of advice. "Try to design a material that can live with as much disorder as possible," he said. "Take the disorder for granted. Personally, I really like disorder. Just look at my office."</p>
  <p>Other authors of the study are postdoctoral scholar Koen Vandewal of Stanford; Felix Koch and Paul Smith of <a href="http://www.polytech.mat.ethz.ch/">ETH Zurich</a>; Natalie Stingelin of <a href="http://www3.imperial.ac.uk/materials">Imperial College London</a>; and Michael Toney of the SLAC <a href="http://ssrl.slac.stanford.edu/">Stanford Synchrotron Radiation Lightsource</a>.</p>
  <p>The study was supported by a Stanford <a href="http://camp.stanford.edu/">Center for Advanced Molecular Photovoltaics</a> award from the King Abdullah University of Science and Technology; and by the <a href="http://erc.europa.eu/">European Research Council</a>.</p>
   ',
          'safe_summary' => '  ',
        ),
      ),
    ),
    'field_slac_news_citation' => array(),
    'field_slac_news_contact' => array(),
    'field_slac_news_media' => array(
      'und' => array(
        0 => array(
          'fid' => 1,
          'title' => NULL,
          'data' => NULL,
        ),
      ),
    ),
    'field_slac_news_source' => array(
      'und' => array(
        0 => array(
          'url' => 'http://news.stanford.edu/news/2013/august/disorder-solar-cells-080413.html',
          'title' => 'Stanford Report',
          'attributes' => array(),
        ),
      ),
    ),
    'field_slac_news_tags' => array(
      'und' => array(
        0 => array(
          'tid' => 46,
          'uuid' => 'dad41187-6745-43bc-b95a-7851a7b2c825',
        ),
        1 => array(
          'tid' => 45,
          'uuid' => 'aaa4a1c8-fb65-4eeb-9bfe-909031f5e18b',
        ),
      ),
    ),
    'field_slac_news_type' => array(
      'und' => array(
        0 => array(
          'tid' => 4,
          'uuid' => '47c46adc-4bf5-41cc-91a2-96c057b16297',
        ),
      ),
    ),
    'metatags' => array(),
    'rdf_mapping' => array(
      'rdftype' => array(
        0 => 'sioc:Item',
        1 => 'foaf:Document',
      ),
      'title' => array(
        'predicates' => array(
          0 => 'dc:title',
        ),
      ),
      'created' => array(
        'predicates' => array(
          0 => 'dc:date',
          1 => 'dc:created',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'changed' => array(
        'predicates' => array(
          0 => 'dc:modified',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
      'body' => array(
        'predicates' => array(
          0 => 'content:encoded',
        ),
      ),
      'uid' => array(
        'predicates' => array(
          0 => 'sioc:has_creator',
        ),
        'type' => 'rel',
      ),
      'name' => array(
        'predicates' => array(
          0 => 'foaf:name',
        ),
      ),
      'comment_count' => array(
        'predicates' => array(
          0 => 'sioc:num_replies',
        ),
        'datatype' => 'xsd:integer',
      ),
      'last_activity' => array(
        'predicates' => array(
          0 => 'sioc:last_activity_date',
        ),
        'datatype' => 'xsd:dateTime',
        'callback' => 'date_iso8601',
      ),
    ),
    'cid' => 0,
    'last_comment_name' => NULL,
    'last_comment_uid' => 0,
    'comment_count' => 0,
    'name' => 'James Smith',
    'picture' => 0,
    'date' => '2013-04-15 13:45:15 -0600',
    'author_uuid' => '7588442f-2b14-42b8-b4f2-cb90accaad0d',
  );
  return $nodes;
}
