<?php

/**
 * Imlements hook_panels_pre_render().
 */
function panels_menu_active_trail_panels_pre_render($panel_display, $renderer) {
  if (!isset($panel_display->cache_key)) {
    return;
  }

  $current_page = page_manager_get_current_page();

  if (isset($current_page['handler'])) {
    $handler = $current_page['handler'];

    $active_path = '';
    if (isset($handler->conf['panels_menu_active_trail']) && $handler->conf['panels_menu_active_trail']) {
      list($menu_name, $mlid) = explode(':', $handler->conf['panels_menu_active_trail']);
      $menu_link = menu_link_load($mlid);
      $active_path = $menu_link['link_path'];
    }

    if (!empty($active_path)) {
      $original_path = &drupal_static(__FUNCTION__, array());
      $original_path[$panel_display->cache_key] = current_path();

      menu_tree_set_path($menu_name, $active_path);
    }
  }
}

/**
 * Implements hook_panels_post_render().
 */
function panels_menu_active_trail_panels_post_render($panel_display, $renderer) {
  if (!isset($panel_display->cache_key)) {
    return;
  }

  if (!isset($current_page['handler'])) {
    return;
  }
  
  $current_page = page_manager_get_current_page();
  $handler = $current_page['handler'];
  if (isset($handler->conf['panels_menu_active_trail']) && $handler->conf['panels_menu_active_trail']) {
    $menu_info = explode(':', $handler->conf['panels_menu_active_trail']);
    $menu_name = $menu_info[0];
  }

  $original_path = drupal_static('panels_menu_active_trail_panels_pre_render', array());
  if (is_array($original_path) && isset($original_path[$panel_display->cache_key])) {
    menu_set_active_item($menu_name, $original_path[$panel_display->cache_key]);
  }
}

/**
 * Implements hook_page_manager_variant_operations_alter().
 *
 * This adds our configuration form as a tab on each variant.
 */
function panels_menu_active_trail_page_manager_variant_operations_alter(&$operations, $handler) {
  // Use this obnoxious construct to safely insert our item on the right place.
  // There is no cleaner way of doing this, since the order of the tabs depends
  // on the order of the keys in the array.
  reset($operations['children']);
  $children_operations = array();
  while (list($key, $value) = each($operations['children'])) {
    $children_operations[$key] = $value;
    if ($key == 'context') {
      $children_operations['menu_active_trail'] = array(
        'title' => t('Menu Active Trail'),
        'description' => t('Choose menu item for active trail.'),
        'form' => 'panels_menu_active_trail_config_form',
      );
    }
  }
  $operations['children'] = $children_operations;
}

/**
 * Configuration form.
 */
function panels_menu_active_trail_config_form($form, &$form_state) {
  $handler = $form_state['handler'];

  $panels_menu_active_trail_mlid = isset($handler->conf['panels_menu_active_trail']) ? $handler->conf['panels_menu_active_trail'] : 0;
  $options = menu_parent_options(menu_get_menus(), array('mlid' => 0));

  $form['panels_menu_active_trail'] = array(
    '#type' => 'select',
    '#title' => t('Menu items'),
    '#default_value' => $panels_menu_active_trail_mlid,
    '#options' => $options,
  );

  return $form;
}

/**
 * Submit handler for our configuration form.
 */
function panels_menu_active_trail_config_form_submit(&$form, &$form_state) {
  $form_state['handler']->conf['panels_menu_active_trail'] = $form_state['values']['panels_menu_active_trail'];
}
