<?php

/**
 * @file
 * Field formatter to expand and collapse text of a field.
 */

/**
 * Implement hook_field_formatter_info().
 */
function jquery_expander_field_formatter_info() {
  return array(
    'jquery_expander' => array(
      'label' => t('Expander'),
      'field types' => array('text', 'text_long', 'text_with_summary'),
      'settings' => array(
        // Add default settings with text, so we can wrap them in t().
        'expandText' => t('Expand') . ' »',
        'expandPrefix' => '...',
        'collapseTimer' => FALSE,
        'slicePoint' => 50,
        'userCollapseText' => t('Collapse'),
        'userCollapsePrefix' => '',
        'expandEffect' => 'slideDown',
        'expandSpeed' => 250,
        'collapseEffect' => 'slideUp',
        'collapseSpeed' => 200
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function jquery_expander_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();

  $element['expandText'] = array(
    '#type' => 'textfield',
    '#title' => t('Expand text'),
    '#description' => t('Text displayed in a link instead of the hidden part of the element. Clicking this will expand/show the hidden/collapsed text.'),
    '#default_value' => $settings['expandText'],
  );

  $element['expandPrefix'] = array(
    '#type' => 'textfield',
    '#title' => t('Expand prefix'),
    '#description' => t('Text to come before the expand link.'),
    '#default_value' => $settings['expandPrefix'],
  );

  $element['slicePoint'] = array(
    '#type' => 'textfield',
    '#title' => t('Slice point'),
    '#description' => t('Text size in charachters before the expand link.'),
    '#default_value' => $settings['slicePoint'],
    '#element_validate' => array('_element_validate_integer_positive'),
  );

  $element['collapseTimer'] = array(
    '#type' => 'textfield',
    '#title' => t('Collapse timer'),
    '#description' => t('Number of milliseconds after text has been expanded at which to collapse the text again.'),
    '#default_value' => $settings['collapseTimer'],
    '#element_validate' => array('_element_validate_integer_positive'),
  );

  $element['userCollapseText'] = array(
    '#type' => 'textfield',
    '#title' => t('Collapse text'),
    '#description' => t('Text to use for the link to re-collapse the text.'),
    '#default_value' => $settings['userCollapseText'],
  );

  $element['userCollapsePrefix'] = array(
    '#type' => 'textfield',
    '#title' => t('Collapse prefix'),
    '#description' => t('Text to come before the re-collapse link.'),
    '#default_value' => $settings['userCollapsePrefix'],
  );

  $element['expandEffect'] = array(
    '#type' => 'textfield',
    '#title' => t('Expand effect'),
    '#description' => t('Can be slideDown, show, fadeIn, etc.'),
    '#default_value' => $settings['expandEffect'],
  );

  $element['expandSpeed'] = array(
    '#type' => 'textfield',
    '#title' => t('Expand speed'),
    '#description' => t('Provide an integer.'),
    '#default_value' => $settings['expandSpeed'],
  );

  $element['collapseEffect'] = array(
    '#type' => 'textfield',
    '#title' => t('Collapse effect'),
    '#description' => t('Can be slideUp, hide, fadeOut, etc.'),
    '#default_value' => $settings['collapseEffect'],
  );

  $element['collapseSpeed'] = array(
    '#type' => 'textfield',
    '#title' => t('Collpase speed'),
    '#description' => t('Provide an integer.'),
    '#default_value' => $settings['collapseSpeed'],
  );

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function jquery_expander_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = t('Expander set');

  return $summary;
}


/**
 * Implements hook_field_formatter_view().
 */
function jquery_expander_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  static $delta = array();
  $settings = $display['settings'];

  // Make sure speeds are given as integers not strings
  $settings['collapseSpeed'] = (int) $settings['collapseSpeed'];
  $settings['expandSpeed'] = (int) $settings['expandSpeed'];

  // Translate expand and collapse text if the i18n_field module is enabled.
  // At the moment we only have one string for all view modes as we cannot
  // access the current view mode in this hook.
  if (module_exists('i18n_field')) {
    $translatable_settings = array('expandText', 'userCollapseText');
    foreach ($translatable_settings as $key) {
      $settings[$key] = i18n_string_translate('field:' . $instance['field_name'] . ':' . $instance['bundle'] . ':' . $key . ':default', $settings[$key]);
    }
  }

  foreach ($items as $delta => $item) {
    $output = _text_sanitize($instance, $langcode, $item, 'value');
    $element[$delta] = array(
      '#markup' => $output,
      '#prefix' => '<div class="field-expander field-expander-' . $delta . '">',
      '#suffix' => '</div>'
    );
    $element[$delta]['#attached']['js'] = array(
      drupal_get_path('module', 'jquery_expander') . '/js/jquery_expander.js' => array('type' => 'file'),
      libraries_get_path('jquery.expander') . '/jquery.expander.js' => array('type' => 'file'),
      array('data' => array('jqueryExpander' => array($delta => $settings)), 'type' => 'setting'),
    );
    ++$delta;
  }

  return $element;
}

/**
 * Implements hook_i18n_string_list_TEXTGROUP_alter().
 */
function jquery_expander_i18n_string_list_field_alter(&$strings, $type = NULL, $instance = NULL) {
  // Register expand and collapse strings.
  // At the moment we only have one string for all view modes as we cannot
  // access the current view mode in this hook_field_formatter_view().
  if (isset($instance['widget']['module']) && $instance['widget']['module'] == 'text' && isset($instance['display']['default']['type']) && $instance['display']['default']['type'] == 'jquery_expander') {
    $field_strings = &$strings['field'][$instance['field_name']][$instance['bundle']];
    $field_strings['expandText:default'] = array(
      'title' => t('Expand text'),
      'string' => $instance['display']['default']['settings']['expandText'],
    );
    $field_strings['userCollapseText:default'] = array(
      'title' => t('Collapse text'),
      'string' => $instance['display']['default']['settings']['userCollapseText'],
    );
  }
}
